### ISSUE TITLE
Double-tap does not disable when letting go of DT key, despite being set to "On Key" 

### ISSUE THREAD

**Issue by SylveonBottle** [tf2cheater2013/Fedoraware#101]
**Fedoraware Version Date:**  e978479

## Config used:

https://files.catbox.moe/r1y8i0.fed

## Description:  
Enabling DTap with a key allows you to use doubletap on your next shot.
Pressing the key enables DT, as the setting says in "DT Mode", "on key".
Holding the DT key is expected to activate DT. This is as expected.
Letting go of the DT key does not disable DT. Your next shot will still activate DT, even if you let go of the key. I expected DT to not fire when letting go of the DT key.

Due to this problem, DT Mode to "Disable on key" does not work at all. You still doubletap despite holding the DT key, even though it's supposed to "disable on key".

## Steps to reproduce:  
- [x] I am able to consistently reproduce this error

1. Enable DT, set DT key to Ctrl
2. Tap Ctrl once
3. Wait however long you wish
4. Fire a single shot
5. Notice how DT activated, despite no longer holding Ctrl

- [x] I have included the steps to reproduce to the best I am able to share.

**Comment by xxmyn** [comment]
This has been a long term issue with a number of "on hold" binds in the cheat (edge jump for example)

**Comment by SylveonBottle** [comment]
After changing DT to "disable on key", then back to "on key", I am suddenly unable to reproduce this issue. DT Mode is working fine now.
I suppose if this is a known issue, and I'm no longer experiencing the issue, we could close this.

**Comment by xxmyn** [comment]
I have fixed the issue I believed this to be, good to hear your problem is fixed as well.
