### ISSUE TITLE
Crithack not working

### ISSUE THREAD

**Issue by n4zzu** [tf2cheater2013/Fedoraware#102]
**Fedoraware Version Date:**  

## Config used:
https://files.catbox.moe/e9nll5.fed

## Description:  

Crithack does not work.

## Steps to reproduce:  
- [x] I am able to consistently reproduce this error

1. Enable crit hack
2. Watch as bucket and cmdnum value rises
3. hold crit key
4. shoot
5. no crit ):

- [x] I have included the steps to reproduce to the best I am able to share.

**Comment by idiotwithgun** [comment]
its got (not working) at the end of its description
but i wish it did worked :(

**Comment by wsock** [comment]
just remove the 'not working' comment, it should work perfectly fine then! 

Source: Trust me.
