### ISSUE TITLE
bot detection

### ISSUE THREAD

**Issue by j4kst3r** [tf2cheater2013/Fedoraware#11]
detection doesnt log to chat properly, but logs fine to onscreen logger

**Comment by tf2cheater2013** [comment]
How is it supposed to log?

**Comment by tf2cheater2013** [comment]
Bot detection isn't great, it only works if the bot is not f2p, and if they are using the achievement method to identify & mark.

It does look like it gets printed to chat and in my experience with it, works fine, vote logger does not log to chat, and logs all votes to console as well as to g_notify.
