### ISSUE TITLE
Bugs with crithack

### ISSUE THREAD

**Issue by canedoly** [tf2cheater2013/Fedoraware#110]
So I've used crithack for the last 1 hour and I've experienced some bugs.
- Holding crithack while shooting with pistols & mini guns, causes your game to lag slightly. (Depends on the pc)
- Using a bind to fix invisible players (record fix;stop) causes the bucket to reset back to 300
- Pressing the crit key once causes it to force crits everytime, (doesn't happen while using aimbot) so farming crits is kinda harder.

Other than that, the crithack works great.

**Comment by cOpEtriNe** [comment]
it doesn't work

**Comment by canedoly** [comment]
wdym it doesn't work? I literally used it both in casual and local server and it works fine

**Comment by cOpEtriNe** [comment]
I've not used this cheat for a while so Idk

**Comment by canedoly** [comment]
The crithack recently got fixed and it works great

**Comment by AXDWT** [comment]
yeah uh its not working that well i was testing

**Comment by cOpEtriNe** [comment]
just tested it, it does work, I also get some issues too.

**Comment by xxmyn** [comment]
are you sure on the last bug, ive done some testing with it but i dont use crithack a lot and it seemed fine with having normal crits when i wasnt holding the button

**Comment by johnathon-walnut** [comment]
@xxmyn he means the bug where you press a key and it still does the thing after you release it until the thing it does has been done

**Comment by xxmyn** [comment]
That occurs case by case, and I fixed it on edge jump earlier which was the only case of it I know of.

**Comment by johnathon-walnut** [comment]
It happens with DT, crits and warp (when 0 charge)

**Comment by xxmyn** [comment]
I just tested DT, warp and the crit key in a local server and had no issues with any of them.

**Comment by johnathon-walnut** [comment]
Well it's happened to me regardless. Not an issue, but put DT on key, press your key but don't shoot, move around a bit then shoot while not holding your key. It will DT.

**Comment by xxmyn** [comment]
I've tested all of the issues you've described in the post, the only one I can recreate is the "demo record" one, this occurs in nullcore from memory and isn't really a problem imo as if you're having to use that ghetto bind to fix invis players you are going to have bigger issues than your crit bucket indicator being inaccurate.

**Comment by johnathon-walnut** [comment]
The crit bucket is inaccurate anyway.

**Comment by xxmyn** [comment]
i thought i closed this

**Comment by Umbrozium** [comment]
here's my config
https://anonfiles.com/FcD9M6R9x3/sexer_fed
