### ISSUE TITLE
Crithack

### ISSUE THREAD

**Issue by FilippoFerarri** [tf2cheater2013/Fedoraware#112]
## Description:  
The crithack is working but the bucket state is always on 1000 no matter what I do after I fill it. It also sometimes random crit even without me holding the button.

## Steps to reproduce:  
- [x] I am able to consistently reproduce this error

1. Enable crithack
2. Shoot a crit (works as normal) but the bucket state will not change
3. After 1 crit the bucket will always show full even nomatter if it is not currently able to crit or it is able to.

- [ ] I have included the steps to reproduce to the best I am able to share.

**Comment by HARrhhv1** [comment]
they need a better indicator

**Comment by johnathon-walnut** [comment]
Ignore what the bucket says - it isn't accurate and I want you to know that its value is literally nonsense. Stop looking at it, stop thinking it impacts anything, and you will enjoy the crit hack much more.

**Comment by Fowgzu** [comment]
Bootleg crithack is better than no crithack, same for bootleg DT. I've been dreaming of crithack ever since it got added, best feature 10/10
