### ISSUE TITLE
FPS drop when crithack indicator shows that I'm crit banned.

### ISSUE THREAD

**Issue by Umbrozium** [tf2cheater2013/Fedoraware#117]
Just as the title says, when I was playing the game and forced crits until I got crit banned, it started lagging really badly for some reason.

**Comment by xxmyn** [comment]
I'm unable to recreate this, please try to recreate it and then upload the config if you are able to.

**Comment by HARrhhv1** [comment]
nice pc

**Comment by johnathon-walnut** [comment]
This happened to me with the market gardener too

**Comment by Umbrozium** [comment]
> I'm unable to recreate this, please try to recreate it and then upload the config if you are able to.

As always, here's my config, and I also here's a clip showing exactly what's happening.

https://anonfiles.com/FbS8WfR6xc/sexer_fed

https://user-images.githubusercontent.com/38528831/160764925-16c7c310-e757-4de4-8a29-fc8a15c51968.mp4

**Comment by xxmyn** [comment]
i was running on an older build and could not figure out why crit banned was even showing up...

either way, even with the config I'm unable to recreate this issue.

**Comment by FilippoFerarri** [comment]
I also randomly drop fps when having crithack enabled. After turning it off I do not have the issue.

**Comment by lnx00** [comment]
Should be fixed now
