### ISSUE TITLE
add auto melee

### ISSUE THREAD

**Issue by ok1253** [tf2cheater2013/Fedoraware#118]
it will be very helpful for demoknight and market gardening

**Comment by lnx00** [comment]
You mean a feature that automatically switches to melee on close range?

**Comment by ShiroSeby** [comment]
> You mean a feature that automatically switches to melee on close range? Or a melee aimbot?

I think he meant a separate triggerbot for melee

**Comment by n4zzu** [comment]
> You mean a feature that automatically switches to melee on close range? Or a melee aimbot?

i think whats he means is if enemy is hittable with melee, and melee is currently being held, then hit them :)

**Comment by lnx00** [comment]
> > You mean a feature that automatically switches to melee on close range? Or a melee aimbot?
> 
> i think whats he means is if enemy is hittable with melee, and melee is currently being held, then hit them :)

We have that already

**Comment by xxmyn** [comment]
yes auto melee such a helpful suggestion so helpful in fact that there are 4 comments dedicated to figuring out what the fuck you mean.
