### ISSUE TITLE
It's crashing randomly

### ISSUE THREAD

**Issue by LukeHenson18** [tf2cheater2013/Fedoraware#12]
It crashes randomly whether I press the 3rd loadout slot bind key or it just crashes at the middle of the match

**Comment by canedoly** [comment]
i don't have this issue

**Comment by frel0** [comment]
dogshit pc

**Comment by M-F3D** [comment]
Attach a debugger

**Comment by lnx00** [comment]
This should hopefully be fixed in 85efb6346a751261bc438317927183567cf264c8

**Comment by M-F3D** [comment]
No response in 3 days so I'm closing this
