### ISSUE TITLE
anti aim indicator

### ISSUE THREAD

**Issue by HARrhhv1** [tf2cheater2013/Fedoraware#121]
![image](https://user-images.githubusercontent.com/102487175/160962607-98e98eb4-2974-48de-a6c0-5461de4a7810.png)
when this gonna be added?¿

**Comment by HARrhhv1** [comment]
also why when i have anti aim on with heavy start tap firing?

**Comment by lbydesync** [comment]
go fix it yourself it's in the code.

**Comment by xxmyn** [comment]
Maybe never :DDD
