### ISSUE TITLE
Health bar is broken

### ISSUE THREAD

**Issue by Fowgzu** [tf2cheater2013/Fedoraware#124]
Screenshot :![image](https://user-images.githubusercontent.com/36936588/161112931-cb1f39ce-8e13-4b16-b261-9cddb3b3aa14.png)

Basically it shows everyone as if they have uber, the health values are working, only the health bar is broken.

Also crit info is worse than before but atleast it fixed the fps issue, sort of.

**Comment by johnathon-walnut** [comment]
The crit info before was still nonsense.

**Comment by johnathon-walnut** [comment]
And that is a very strange bug, mind attaching a config?

**Comment by johnathon-walnut** [comment]
Also, you can upload images directly to GitHub.

**Comment by NotAnUser1** [comment]
[mhmm very strange bug indeed veeery strange](https://github.com/tf2cheater2013/Fedoraware/blob/main/Fedoraware/TeamFortress2/TeamFortress2/SDK/Main/BaseEntity/BaseEntity.h#L209=)

**Comment by Fowgzu** [comment]
Well it happens with all my configs, i can just send you one of them if you want but i dont see how that could help

**Comment by Fowgzu** [comment]
Also happens since latest build, never had this issue before

**Comment by johnathon-walnut** [comment]
> [mhmm very strange bug indeed veeery strange](https://github.com/tf2cheater2013/Fedoraware/blob/main/Fedoraware/TeamFortress2/TeamFortress2/SDK/Main/BaseEntity/BaseEntity.h#L209=)

Outdated? Is this due to a recent update?

**Comment by lnx00** [comment]
> > [mhmm very strange bug indeed veeery strange](https://github.com/tf2cheater2013/Fedoraware/blob/main/Fedoraware/TeamFortress2/TeamFortress2/SDK/Main/BaseEntity/BaseEntity.h#L209=)
> 
> Outdated? Is this due to a recent update?

baan changed it to "bool" instead of "int"

**Comment by johnathon-walnut** [comment]
> > > [mhmm very strange bug indeed veeery strange](https://github.com/tf2cheater2013/Fedoraware/blob/main/Fedoraware/TeamFortress2/TeamFortress2/SDK/Main/BaseEntity/BaseEntity.h#L209=)
> > 
> > 
> > Outdated? Is this due to a recent update?
> 
> baan changed it to "bool" instead of "int"

... Why? @xxmyn

**Comment by johnathon-walnut** [comment]
Reverted it, try latest build and report back ( I did not test it, but i don't see why it wouldn't work )
