### ISSUE TITLE
NICE VAC WAVE

### ISSUE THREAD

**Issue by HARrhhv1** [tf2cheater2013/Fedoraware#125]
half of the ppl are getting vacbanned for using fware lmfao

**Comment by idiotwithgun** [comment]
LETS FUCKING GOOOOO

**Comment by johnathon-walnut** [comment]
Just lost my $500 backpack cos of this, VAC bypass isn't working... Trade all your stuff if you aren't banned yet.

**Comment by FFJ11** [comment]
Is fedoraloader's Vac bypass not working?

**Comment by johnathon-walnut** [comment]
Vac bypass in general isn't working.

**Comment by FFJ11** [comment]
i just played tf2 with it recently but Didn't get affected though.

**Comment by FFJ11** [comment]
Is the ban wave over or is there more?

**Comment by FFJ11** [comment]
Welp, don't use tf2 for months then, simple or just play on a decoy account.

**Comment by wsock** [comment]
DO NOT GO ON A VACATION, WORST WAVES EVER.

**Comment by FFJ11** [comment]
I think this is an april fool's joke

**Comment by wayven** [comment]
i recoverec my itemzzzz with item generator by osamabinladen666t luuuuuuuuuuu2193888888888888888888888888888888888 getting collector's australium mingun rn while u guys get banned losing 9 kwanza invXDDDDDDDDDDDDDDDDDD
