### ISSUE TITLE
Unable to join servers with Fedware injected

### ISSUE THREAD

**Issue by sudoboys** [tf2cheater2013/Fedoraware#13]
**Fedoraware Version Date:**  
2/7/2022

## Config used:
https://files.catbox.moe/exe07v.fed

## Description:  
When injected with Fedware I get booted out of it, error message here https://dude.bruh.media/VKRAYLdi

1. Inject Fedware
2. Attempt to load into any server (even local ones)

## Additional context 
Dual injected with LMAObox, using Xenos injector for Fedware.

## Screenshot of cheats enabled  
https://dude.bruh.media/BThjzKVF

**Comment by M-F3D** [comment]
Does this happen when you don't inject lmaobox with it?

**Comment by sudoboys** [comment]
I've attempted restarting and injecting without lmaobox but the game and injector both crash.

**Comment by lnx00** [comment]
Tried the config with latest Fedoraware and Xenos and it's working fine. What injection method and settings are you using on Xenos?

**Comment by sudoboys** [comment]
> Tried the config with latest Fedoraware and Xenos and it's working fine. What injection method and settings are you using on Xenos?

https://dude.bruh.media/lOiRAmqz I believe these are the defaults

**Comment by lnx00** [comment]
Enable "Use existing thread". If that doesn't work, try "Manual map" with "Erase PE headers" and "Ignore TLS"

**Comment by sudoboys** [comment]
> Enable "Use existing thread". If that doesn't work, try injection type "Manual map" with "Erase PE headers" and "Ignore TLS"

Neither of those worked, however with the latter TF2 crashes and not Xenos.

**Comment by lnx00** [comment]
Are you using the official Xenos or some some fork of it?

**Comment by sudoboys** [comment]
> Are you using the official Xenos or some some fork of it?

Nope I'm using the official one https://github.com/relaxtakenotes/xenos/releases/tag/1.1.2

**Comment by lnx00** [comment]
This is the official injector: https://github.com/DarthTon/Xenos
Try it with this one.

**Comment by sudoboys** [comment]
> This is the official injector: https://github.com/DarthTon/Xenos Try it with this one.

its still not working

**Comment by sudoboys** [comment]
After restarting my pc it works fine, however, if I close out the game and inject again the crashing problem returns.

**Comment by tf2cheater2013** [comment]
manual map with no other settings enabled.
