### ISSUE TITLE
DT Fires when the key is not pressed

### ISSUE THREAD

**Issue by wayven** [tf2cheater2013/Fedoraware#131]
so faggot, i am using lastest version rn and this shit is since the past updates.
resuming the dt has a weird gay nigger bug wich it uses itself sometimes when I'M NOT pressing the key
there is no record of it , but happened trust me pinky promise!

**Comment by HARrhhv1** [comment]
![image](https://user-images.githubusercontent.com/102487175/161417169-3b717279-1ef9-4214-bb23-fcb44384364c.png)

**Comment by wayven** [comment]
me irl

> ![image](https://user-images.githubusercontent.com/102487175/161417169-3b717279-1ef9-4214-bb23-fcb44384364c.png)
