### ISSUE TITLE
stuck at a loading screen

### ISSUE THREAD

**Issue by FFJ11** [tf2cheater2013/Fedoraware#133]
im stuck at a loading screen when joining a match
anway to fix it?

**Comment by FFJ11** [comment]
![image](https://user-images.githubusercontent.com/102504389/161459557-b762c4dd-3727-46f1-ab5b-ba1a051ddc1f.png)

**Comment by HARrhhv1** [comment]
yeah i cant load

**Comment by HARrhhv1** [comment]
i need to uninject and inject

**Comment by SylveonBottle** [comment]
Press D on your keyboard.
It's the MOTD failing to load.
If D doesn't work, try installing ToonHud (or similar) that provides the option of pressing D go to next.

**Comment by johnathon-walnut** [comment]
This is the MOTD removal thing I added, I didn't really test it much but I spam E instinctively when I join a game anyway, so I didn't notice :trollface:

**Comment by awesome20222** [comment]
@johnathon-walnut need to improve this feature

**Comment by XenoxUSser** [comment]
and how do i fix this now cant find anywhere to turn that feature off

**Comment by johnathon-walnut** [comment]
i didnt add a toggle either :trollface: 
just press E

**Comment by XenoxUSser** [comment]
> i didnt add a toggle either :trollface: just press E

doesent fix it since i dont use any hud that allows it
i use cool hud

**Comment by gayblackirony** [comment]
loser

> > i didnt add a toggle either :trollface: just press E
> 
> doesent fix it since i dont use any hud that allows it i use cool hud

**Comment by XenoxUSser** [comment]
> > > i didnt add a toggle either :trollface: just press E
> > 
> > 
> > doesent fix it since i dont use any hud that allows it i use cool hud
> 
> loser

your name says it all bruh

**Comment by johnathon-walnut** [comment]
> > i didnt add a toggle either :trollface: just press E
> 
> doesent fix it since i dont use any hud that allows it i use cool hud

stop using that hud then or just remove it from your build??? (PanelHook.cpp)

**Comment by xxmyn** [comment]
Issue has been solved, sorry it was added but you're just gonna have to deal with it ig :D
