### ISSUE TITLE
Replace Choke ESP value with Choke/Lagging warning

### ISSUE THREAD

**Issue by SylveonBottle** [tf2cheater2013/Fedoraware#135]
Having `C: 0` and `C:1` flashing back and forth is very annoying and provides little to no feedback.

If possible, can we make it so it only shows when Choke is >4? 

It could then replaced with "Choking (5)" or "Lagging (5)" for further information without cluttering the screen unless it's necessary.

Tl;dr only show Choke value for people who are actually choking packets

**Comment by xxmyn** [comment]
I looked at it, I didn't like it.

**Comment by johnathon-walnut** [comment]
What about a triangle thing, with the number in the middle, could look cool ⚠️

**Comment by tf2cheater2013** [comment]
I've changed this to a bar with customisable colours and am looking at Mr Walnuts triangle idea.

ty for the suggestion.

**Comment by SylveonBottle** [comment]
Not a fan of the bar, it flushes too easily with health and just seems annoying constantly being on 24/7.
Again, having an alert for when somebody is _actually_ chocking packets would be great.

**Comment by xxmyn** [comment]
unless i add something to make it fade out, pretty much any value just makes it look bad.

**Comment by xxmyn** [comment]
no, the overlay uses your outline colour as i was lazy, go to your config and make sure it has full alpha instead of 220 which was the default before iirc.

i will fix sooner or later.
