### ISSUE TITLE
Aimbot problem

### ISSUE THREAD

**Issue by awesome20222** [tf2cheater2013/Fedoraware#139]
Problem: Aimbot misses sometime soldiers and demomans

**Comment by awesome20222** [comment]
> just don't miss lol

i do it

**Comment by tf2cheater2013** [comment]
Please upload your config.

I've had very little issue with the aimbot missing so I'd prefer to fix this if possible.

**Comment by awesome20222** [comment]
@tf2cheater2013 config https://pastebin.com/DHjWYYV5

**Comment by xxmyn** [comment]
your config sucks.

[aimbot isnt missing](https://youtu.be/395dMKNdVw4)

and particle tracers still work for me.


Provide a clip of it missing and particle tracers not working, and then probably ur host_writeconfig shit too, and then reopen.

**Comment by johnathon-walnut** [comment]
> @tf2cheater2013 config https://pastebin.com/DHjWYYV5 . Also particles for bullet tracers don't work

There is a convar that disables tracers in first person. Set it to 0

**Comment by awesome20222** [comment]
> 

can't find this command

**Comment by JAGNEmk** [comment]
r_drawtracers_firstperson

**Comment by awesome20222** [comment]
> r_drawtracers_firstperson

thank mate
