### ISSUE TITLE
crithack and other bugs please fix NOW

### ISSUE THREAD

**Issue by whyskyboxchange** [tf2cheater2013/Fedoraware#144]
**Fedoraware Version Date:**  

## Config used:
this literally works with any config

## Description:  
crithack wont work with sticky launchers because of https://user-images.githubusercontent.com/93831973/161852449-b373815f-8bed-4fb9-b4ee-00db92cc0a91.png so please add more checks for that, spy camera doesnt save on config, and auto whip tries to whip myself while in third person, FIX!!!!!!!!!!!!!

## Steps to reproduce:  
- [x] I am able to consistently reproduce this error
yes all of those are consistent

1. Enable crithack
2. Trigger crithack key
3. No sticky crit
--
1. Enable Auto whip
2. Enable third person
3. Tries to whip myself
--
1. Enable spy camera
2. Resize and mess around with it
3. Save config
4. Reload config
5. It ends up back in the default spot
--
## Additional context 
idfk

- [x] I have included the steps to reproduce to the best I am able to share.

**Comment by whyskyboxchange** [comment]
also either fix crit bucket or just add some shitty text saying true or false if it can crit or not thanks

**Comment by xxmyn** [comment]
just guess whether u can crit or not ez,,,

**Comment by johnathon-walnut** [comment]
> also either fix crit bucket or just add some shitty text saying true or false if it can crit or not thanks

The problem with OR being there is that if the bucket isn't fixed it can still show as you being able to crit even if you can't

**Comment by xxmyn** [comment]
[user issue probably](https://youtu.be/YDvcJEUvyeE)

**Comment by xxmyn** [comment]
also the auto whip does not target yourself and i wasted far too long messing around with my (perfect) config to figure out that ur probably just schizophrenic.

**Comment by whyskyboxchange** [comment]
> also the auto whip does not target yourself and i wasted far too long messing around with my (perfect) config to figure out that ur probably just schizophrenic.

autowhip only targets* (not whips) myself while in third person

**Comment by johnathon-walnut** [comment]
Ur right about stickies not critting, ignore Baan.

**Comment by whyskyboxchange** [comment]
> Ur right about stickies not critting, ignore Baan.

oh ok
