### ISSUE TITLE
Health pack esp color won't change and is always 255, 0, 0, 255 (Red)

### ISSUE THREAD

**Issue by ShiroSeby** [tf2cheater2013/Fedoraware#145]
**Fedoraware Version Date: April 5 2022 10:56:21**  

## Config used:
https://files.catbox.moe/rtaxom.fed
It works with any config, maybe

## Description:  
Health pack esp color won't change and is always (255, 0, 0, 255) (Red)

## Steps to reproduce:  
- [✔️] I am able to consistently reproduce this error

1. Make a config
2. Change the health pack esp color to any other color other than red
3. Save config
4. Load config
5. Health pack esp color will be still red

## Additional context 
- [✔️] I have included the steps to reproduce to the best I am able to share.

**Comment by xxmyn** [comment]
Please upload the config not to catbox.moe whatever tf that is.

**Comment by johnathon-walnut** [comment]
It is literally on catbox

**Comment by xxmyn** [comment]
Fixed
