### ISSUE TITLE
health timer thing doesnt dissapear on sandviches

### ISSUE THREAD

**Issue by whyskyboxchange** [tf2cheater2013/Fedoraware#148]
**Fedoraware Version Date:**  

## Config used:
any

## Description:  
when spam dropping sandviches 
![hl2_l2kujvccPx](https://user-images.githubusercontent.com/93831973/161998819-81acdc9f-9238-4cbe-afe9-7d34bd27fb9d.png)
and picking them up the timer remains there

## Steps to reproduce:  
- [x] I am able to consistently reproduce this error

1. Enable display health packs or whatever its called thing
2. Drop sandvich
3. Pick it up
4. 
![hl2_l2kujvccPx](https://user-images.githubusercontent.com/93831973/161998947-538adeb3-614d-4bfe-b983-2e9211acdd18.png)

## Additional context 
idfk

- [x] I have included the steps to reproduce to the best I am able to share.

**Comment by lnx00** [comment]
Yea this is caused because the "item_pickup" event gets called when you collect the sandvich. Don't really know how to fix this / if there is a way to check the item that is being picked up since the sandvich is seen as a medkit by the event.

**Comment by xxmyn** [comment]
Im sorry but sandwiches have respawn times?

**Comment by johnathon-walnut** [comment]
Could probably semi-fix by keeping track of dropped sandwich positions but this would also have a bug where normal health packs would cause it to be retarded

**Comment by lnx00** [comment]
> Could probably semi-fix by keeping track of dropped sandwich positions but this would also have a bug where normal health packs would cause it to be retarded

I wonder how lmaobox solved this problem

**Comment by johnathon-walnut** [comment]
I don't think he ever did?

**Comment by lnx00** [comment]
I nver saw the pickup timer appearing on sandviches in lmaobox iirc
