### ISSUE TITLE
ebic crash

### ISSUE THREAD

**Issue by relaxtakenotes** [tf2cheater2013/Fedoraware#15]
I won't use the template 🖕🏻 

Game will crash if you select fresnel for the DME hand chams.

**Comment by M-F3D** [comment]
![image](https://user-images.githubusercontent.com/98985452/153041284-45cc083d-7f26-4afc-ae4e-35ffc9f69e75.png)
It doesn't crash for me but it is green

**Comment by tf2cheater2013** [comment]
pc issue, don't select fresnel

**Comment by tf2cheater2013** [comment]
This seems like an issue with the default config

**Comment by tf2cheater2013** [comment]
This has been fixed as of the latest commit, please switch to mat_hdr_level 2 if you are not already using it.
