### ISSUE TITLE
Aimbot tries to shoot through wall once enemy is shown on esp

### ISSUE THREAD

**Issue by XenoxUSser** [tf2cheater2013/Fedoraware#156]
once the enemy is visible in the ESP the aimbot tries to shoot no matter what even if theres a wall

**Comment by XenoxUSser** [comment]
i know theres low information but i just joined a random server loaded my always used config for heavy and it shoots as soon as an enemy is shown through esp

**Comment by xxmyn** [comment]
huh

**Comment by gayblackirony** [comment]
it shoots through walls if ur current aimbot hitbox is body /shrug

**Comment by xxmyn** [comment]
Fixed
