### ISSUE TITLE
What does the other miscs do aside from antibackstab

### ISSUE THREAD

**Issue by FFJ11** [tf2cheater2013/Fedoraware#158]
![image](https://user-images.githubusercontent.com/102504389/162431769-b2f09340-8c23-43cc-b97a-beb4766ccd4e.png)

**Comment by n4zzu** [comment]
HidePitchOS is just hide shots. So when you have AA, it tries to hide your onshot angles.
LegJitter is used with AA to make your legs do the funny.
No Overlap tries to ensure your fake angle never overlaps with your real angle while using fake angles.

**Comment by FFJ11** [comment]
Ok ty

**Comment by xxmyn** [comment]
hide pitch on shot gives u fakeup or fakedown when u shoot, idk if its useful outside of stopping people from backtracking your onshot.
