### ISSUE TITLE
why when i change the color of the dt bar the game crash

### ISSUE THREAD

**Issue by HARrhhv1** [tf2cheater2013/Fedoraware#162]
when i inject the cheat again the color of the menu health bar and the chocked packets does not saves
idk why i have those problems with configs

**Comment by lnx00** [comment]
It doesn't crash for me when changing the DT Bar colors.

**Comment by wayven** [comment]
> It doesn't crash for me when changing the DT Bar colors.

he didnt ask if you don't crash with it , help him you mongoloid

**Comment by johnathon-walnut** [comment]
> > It doesn't crash for me when changing the DT Bar colors.
> 
> he didnt ask if you don't crash with it , help him you mongoloid

How is someone meant to help with something they can't get to happen for them? If you can get it to happen for everyone you can debug it and find out *why* it is crashing, hence why it is important for issues to be reproducible.

**Comment by HARrhhv1** [comment]
make the dt bar all white and makes you crash for some reason and bcuz of that the menu color and esp colors does not save

**Comment by lnx00** [comment]
> make the dt bar all white and makes you crash for some reason and bcuz of that the menu color and esp colors does not save

https://streamable.com/e37sm6
I'm still not able to reproduce this. Please upload your config and make sure that you're using the latest Fedoraware build

**Comment by xxmyn** [comment]
Can't reproduce it sorry, maybe you could read the template next time you make an issue?
