### ISSUE TITLE
It randomly vanishes

### ISSUE THREAD

**Issue by FFJ11** [tf2cheater2013/Fedoraware#164]
When I was playing and found a new match, The cheat vanished and Had to re-inject it with fedoraloader

**Comment by xxmyn** [comment]
@lnx00

**Comment by lnx00** [comment]
Played around 3 hours with it on multiple configs maps but I didn't encounter this issue. I will keep an eye out though.

It would also be helpful if you could attach your config and more details about when this happens.

**Comment by johnathon-walnut** [comment]
Did you press F11?

**Comment by xxmyn** [comment]
Useless
