### ISSUE TITLE
Aimbot at auto aims body only

### ISSUE THREAD

**Issue by idiotwithgun** [tf2cheater2013/Fedoraware#166]
You can use any config, just make aimbot aim automatically at any parts of body

Aimbot as sniper only aims body (if its auto at hitbox, if i use head hitbox then it works normally)

Aimbot->Hitscan->Hitbox->Auto
Now watch it shooting body

**Comment by xxmyn** [comment]
hmm

**Comment by xxmyn** [comment]
[Yeh so I wasn't able to reproduce this with the info u gave sorry bro.](https://youtu.be/-ec_nld1tLc)
