### ISSUE TITLE
Holding a building with chams for building activated will overlay screen to be the chams color

### ISSUE THREAD

**Issue by ShiroSeby** [tf2cheater2013/Fedoraware#167]
![image](https://user-images.githubusercontent.com/88360266/162572854-9dd2c93d-77a4-4636-ba5f-108753affd1f.png)

(just enable local building chams lol)
Config: https://files.catbox.moe/j277wf.fed

**Comment by johnathon-walnut** [comment]
lol, i don't think there is much one can do about this

**Comment by johnathon-walnut** [comment]
other than not draw chams on ghost buildings

**Comment by xxmyn** [comment]
i fixed this ages ago but ill look at it again ig

**Comment by xxmyn** [comment]
Just checked with my own config and your config, neither of them cause the issue you're showing.

**Comment by xxmyn** [comment]
yeh mate ur a real piece of shit I want you to know that, this is exactly why you need to provide actual steps to reproduce, literally could've said "pick up a building that's already been built" instead of "just hold le building lel"

**Comment by xxmyn** [comment]
Still fixed it since I'm such an awesome dude
