### ISSUE TITLE
Menu accent color issue

### ISSUE THREAD

**Issue by ShiroSeby** [tf2cheater2013/Fedoraware#171]
When you load a config with different menu accent, the gradient bars (image below) doesn't change until you load the config twice
![image](https://user-images.githubusercontent.com/88360266/162594806-e0268132-4676-46ee-b97b-dc5b1669a33a.png)

**Comment by PeterPumpkinEater69real** [comment]
Happens to me aswell. It's not terrible but it's not nice to look at either.
