### ISSUE TITLE
"Auto" hitbox for projectile improvements

### ISSUE THREAD

**Issue by SylveonBottle** [tf2cheater2013/Fedoraware#174]
In short:
-Aim at chest if feet are occluded
-Don't aim at feet if enemy is bunnyhopping
-Aim at body if we have no reason to knock them up (i.e. they're about to die anyways)

1) Aim at body if feet are occluded
Aimbot fails to fire at people if they're standing ground above you. It should at least attempt to shoot at the target's chest instead of completely ignoring the enemy.
If a person suspects you of using projectile aimbot, all they have to do is stand slightly above you and you can't hit them.
-Check line of sight to feet
-If it's occluded, aim at chest instead
This should be somewhat similar to "Auto" hitbox for bullet-based weapons.

2) Aim at body if the enemy has recently touched the ground.
If an enemy is bunnyhopping, aimbot attempts to shoot at their feet and proceeds to miss due to the enemy jumping over the rocket. The rocket would've hit their feet had it aimed for their chest.
I was in a match with a pyro who discovered I was using aimbot because I would constantly miss them if they just jumped repeatedly. If there was a way to check for people who are bunny hopping (people who have recently jumped up / fallen back down) and aim at chest for these individuals, the aimbot wouldn't miss them.
-If the target jumps, aim for their chest for the next 1.5 seconds.
-After 1.5 seconds, aim at their feet. Jumping again resets the timer to 1.5 seconds
If they are prone to jumping everywhere / bunnyhopping, projectile aimbot should try to account for this by assuming they'll just jump over any shots at their feet.

3) Aim at body if the enemy is in the air and your next shot will kill them.
There's no reason to aim at the feet of a person in the air in order to knock them up if they're going to die to your next rocket anyways.
-If the projectile prediction location of the target is in the air, check the target's hp
-If the enemy has less than X hp, aim for the body.
X = how much damage our rocket would do based off of damage fall-off and the distance the enemy is from us
With an exception for the directhit:
-If we're using the direct hit
-And the target is in the air
-Assume that they've been knocked upwards. If their hp is below 152 (and has no buffs to negate damage), aim for the body for an easy direct hit.

**Comment by johnathon-walnut** [comment]
Honestly the projectile aimbot code really needs cleaning up, might look into it later

**Comment by SylveonBottle** [comment]
> Honestly the projectile aimbot code really needs cleaning up, might look into it later

If a recode of the projectile aimbot is considered in the future, might I suggest [strafe prediction](https://www.youtube.com/watch?v=yYLLrJrNMlI)?

Found a really annoying trolljer in casual that Fedora's projectile aimbot couldn't hit, simply because he strafed slightly. I believe CatHook might have this feature.

**Comment by xxmyn** [comment]
all the aimbot code in this cheat fucking sucks

**Comment by HARrhhv1** [comment]
> > Honestly the projectile aimbot code really needs cleaning up, might look into it later
> 
> If a recode of the projectile aimbot is considered in the future, might I suggest [strafe prediction](https://www.youtube.com/watch?v=yYLLrJrNMlI)?
> 
> Found a really annoying trolljer in casual that Fedora's projectile aimbot couldn't hit, simply because he strafed slightly. I believe CatHook might have this feature.

we need this for sure

**Comment by xxmyn** [comment]
eh...

**Comment by SylveonBottle** [comment]
By "eh" and the "Ideas" -> "Finished" move, can we assume that this was added?

**Comment by xxmyn** [comment]
It no longer ignores players with their toes hidden, so, to an extent yes.
