### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by HARrhhv1** [tf2cheater2013/Fedoraware#177]
add a anti aim indicator like this? 
![image](https://user-images.githubusercontent.com/102487175/162881566-7cc277b4-23cd-42a4-8ca7-672c30db8f64.png)

**Comment by HARrhhv1** [comment]
we need indicators maN

**Comment by HARrhhv1** [comment]
![image](https://user-images.githubusercontent.com/102487175/162886695-571ed585-4f00-4a10-b0b9-36458107a9a4.png)
indicators that show where a sniper is aiming

**Comment by xxmyn** [comment]
what if the sniper has anti-aim on

**Comment by HARrhhv1** [comment]
> what if the sniper has anti-aim on

nice question

**Comment by HARrhhv1** [comment]
> what if the sniper has anti-aim on

point where the sniper is looking ig

**Comment by johnathon-walnut** [comment]
How

**Comment by SylveonBottle** [comment]
draw line from sniper's eyes pointing where he's looking
end the line if it hits a wall
if a sniper is anti-aiming then it won't work (kinda stupid) but the point is to see where the legits and closet cheaters are aiming so you can avoid their sightline, actually pretty useful feature

**Comment by HARrhhv1** [comment]
> draw line from sniper's eyes pointing where he's looking end the line if it hits a wall if a sniper is anti-aiming then it won't work (kinda stupid) but the point is to see where the legits and closet cheaters are aiming so you can avoid their sightline, actually pretty useful feature

exactly

**Comment by johnathon-walnut** [comment]
close enough
