### ISSUE TITLE
i cannot move

### ISSUE THREAD

**Issue by sneekyspy** [tf2cheater2013/Fedoraware#178]
why i cant move and i just see my mouse arrow pls any help?

**Comment by cOpEtriNe** [comment]
type "quit smoking" in console for fix

**Comment by sneekyspy** [comment]
umm i cant even change class tho

**Comment by sneekyspy** [comment]
problem solved the only thing i can do is to shutdown fware and load it when i join the server

**Comment by cOpEtriNe** [comment]
oh nvm

**Comment by cOpEtriNe** [comment]
press enter while you have connected to the server, then choose class. If it doesn't work then idk

**Comment by sneekyspy** [comment]
ohhh!!! yes i know that i wanted to say sorry for wasting time and i know how before you sayed that and i am here to say sorry but you really helped now i am stupid guy in this world

**Comment by cOpEtriNe** [comment]
lol its ok

**Comment by xxmyn** [comment]
> yes i cant change class but i can do it when i change classes by the cheat on misc but i cant move i see only my mouse arrow

upload your config so we can all read Vars::Misc::ExtendFreeze: 1 together

**Comment by xxmyn** [comment]
useless.
