### ISSUE TITLE
wtf every time i update a config

### ISSUE THREAD

**Issue by FFJ11** [tf2cheater2013/Fedoraware#180]
It crashes everytime i update the current config

**Comment by snoopexe** [comment]
same

**Comment by ShiroSeby** [comment]
I think it's related to one of my issue I opened #172

**Comment by Loji-i** [comment]
Got the same, cfg if it matters: https://pastebin.com/bHCgWqnv

Steps to reproduce:
1. Launch/inject f-ware in to TF2 as normal.
2. On main menu, edit some settings in your config (for me its consistently crashes by enabling multipoint using my config above).
3. Save config > Crashes game to desktop after confirming the save.

4. After restarting/reinjecting, the config that crashed you has been corrupted/reset to default, meaning if you didn't back up your config it's gone entirely.
