### ISSUE TITLE
Materials just break after a while...

### ISSUE THREAD

**Issue by xxmyn** [tf2cheater2013/Fedoraware#181]
![image](https://user-images.githubusercontent.com/70382582/163072224-f02f0da2-011b-480c-8425-6f22ead313cb.png)

[Config Used](https://github.com/tf2cheater2013/Fedoraware/files/8477135/default.txt)
[Material Used](https://github.com/tf2cheater2013/Fedoraware/files/8477136/gold.txt)

**Comment by xxmyn** [comment]
![image](https://user-images.githubusercontent.com/70382582/163077050-285beba1-5285-4ecf-9623-fe4af69236cf.png)

this issue also effects gold ragdolls, which makes me think it's something else in the cheat and has nothing to do with the material editor.

**Comment by lnx00** [comment]
Didn't @johnathon-walnut change something about the Materials lately? Maybe that's causing issues

**Comment by xxmyn** [comment]
oops

**Comment by xxmyn** [comment]
Cause by mat_hdr_level
