### ISSUE TITLE
triggerbot key

### ISSUE THREAD

**Issue by GabrielNiccola** [tf2cheater2013/Fedoraware#186]
I would like you to remove the autobackstab key from auto detonate from auto airblast because I have to keep pressing a key and this is very annoying I would like you to remove it please

**Comment by wizardmanperson** [comment]
remove it yourself.

**Comment by wizardmanperson** [comment]
I find it better 2 use key.

**Comment by gayblackirony** [comment]
literally just unbind it

**Comment by gayblackirony** [comment]
???

**Comment by wizardmanperson** [comment]
yes

**Comment by gayblackirony** [comment]
🤝

**Comment by GabrielNiccola** [comment]
> literalmente apenas desvincule-o

**Comment by GabrielNiccola** [comment]
d

**Comment by wizardmanperson** [comment]
e

**Comment by gayblackirony** [comment]
how much crack did you smoke

**Comment by GabrielNiccola** [comment]
how do i remove the auto backstab key?

**Comment by wizardmanperson** [comment]
wtf is he doing lol

**Comment by wizardmanperson** [comment]
goto global (on trigger tab) and click on the trigger key button, then press escape to remove

**Comment by GabrielNiccola** [comment]
Thanks

**Comment by wizardmanperson** [comment]
np.

**Comment by GabrielNiccola** [comment]
but how do i close the write thing here

**Comment by wizardmanperson** [comment]
The issue?

**Comment by GabrielNiccola** [comment]
you forget

**Comment by johnathon-walnut** [comment]
you are mental

**Comment by GabrielNiccola** [comment]
sorry I don't know how to use the site a lot

**Comment by gayblackirony** [comment]
its alright

**Comment by GabrielNiccola** [comment]
How do I open?

**Comment by GabrielNiccola** [comment]
how do i get back to normal?

**Comment by gayblackirony** [comment]
just bind it again

**Comment by n4zzu** [comment]
schizophrenia
