### ISSUE TITLE
Waiting add Fake latancy on cheat. ( for play spy.)

### ISSUE THREAD

**Issue by LEFtt1** [tf2cheater2013/Fedoraware#187]
I can't wait to be added for a place fake lag ( for play spy) will be added Fake latancy.

**Comment by xxmyn** [comment]
dude stfu nobody cares

**Comment by LEFtt1** [comment]
sad

**Comment by LEFtt1** [comment]
wait 
![image](https://user-images.githubusercontent.com/103782432/163691446-650ef90b-4190-43a5-ab59-f53f2c62d23b.png)

**Comment by j4kst3r** [comment]
u are retarded plz stop commenting on this issue, just because its on the to-do doesn't mean ur getting it right away, it takes time u fkn brick

**Comment by LEFtt1** [comment]
ok ty :D
