### ISSUE TITLE
Aimbot head edge detection

### ISSUE THREAD

**Issue by FFJ11** [tf2cheater2013/Fedoraware#188]
Idk if aimbot shoots the edge of the head as soon as it appears, Or it waits for the center of the head.

![unknown (1)](https://user-images.githubusercontent.com/102504389/163670265-f2e4d628-21db-4c74-bdef-efe234dfba2f.png)

**Comment by gayblackirony** [comment]
pretty sure multipoints are a thing

**Comment by xxmyn** [comment]
the fucking code is open source have u tried reading??????
