### ISSUE TITLE
Crash when using cat identify

### ISSUE THREAD

**Issue by lnx00** [tf2cheater2013/Fedoraware#19]
The game will crash when a cathook user joins and cat identify is enabled.
This seems to be caused by line 147 in ChatInfo.cpp
`g_Interfaces.Engine->ServerCmdKeyValues(kv)`

**Comment by tf2cheater2013** [comment]
I believe this has been fixed in a recent commit, please close issue if it is working as intended.

**Comment by lnx00** [comment]
Fixed in baa258f60f282197c12bec3003cc4aaf2dea234c
