### ISSUE TITLE
heavy's minigun

### ISSUE THREAD

**Issue by SimpleAccountName** [tf2cheater2013/Fedoraware#191]
So basically when I play heavy and try to shoot with the minigun, it just shoots like a pistol, even if tapfire is off. I tried with all the tapfire settings and nothing worked. It's not about my config, I've tried legit and HvH config and no result. And yes, I made sure im not double tapping. Sometimes it works fine, most of the time doesn't. It looses ammo when shooting, but the sound is like a pistol and shoots like a pistol. I've tried with fake lag and with no fake lag, and again, no result. And I've also tried going into the test place where nobody is here so I can get a fps boost, and guess what, no results.

**Comment by gayblackirony** [comment]
do u have antibackstab/aa on?

**Comment by xxmyn** [comment]
Know issue, turn off all the anti aim shit and it should be fixed.

Doesn't interfere with firing speed as far as I can tell, but I understand if ur annoyed by the audio constantly stopping.
