### ISSUE TITLE
silent aim

### ISSUE THREAD

**Issue by adeadlysinn** [tf2cheater2013/Fedoraware#193]
it's broken i think it tracks the enemy even tho its silent how can i fix this?

**Comment by wizardmanperson** [comment]
cc_random in console

**Comment by gayblackirony** [comment]
do u have smooth if spectated

**Comment by gayblackirony** [comment]
on

**Comment by adeadlysinn** [comment]
> i have it off

**Comment by adeadlysinn** [comment]
i did it crashed it

**Comment by gayblackirony** [comment]
weird

**Comment by adeadlysinn** [comment]
> weird

ik

**Comment by adeadlysinn** [comment]
> cc_random in console

it crahed my game

**Comment by cOpEtriNe** [comment]
> > cc_random in console
> 
> it crashed my game

lmfao

**Comment by HARrhhv1** [comment]
> > cc_random in console
> 
> it crashed my game

ahhahahahHAHHHAHFAGAQAHA

**Comment by xxmyn** [comment]
joined github 1 hour ago and already has a pony pfp.
doesn't know that cc_random crashes game.

I don't think it aims if you can't shoot, but it should still move the viewmodel and highlight the player you are targeting.
