### ISSUE TITLE
draggable spectator doesnt save where i want it to

### ISSUE THREAD

**Issue by ok1253** [tf2cheater2013/Fedoraware#196]
**Fedoraware Version Date:**
current one 
 
## Description:  
when putting the draggable spectator list somewhere it will automatically save in the top corner no matter what

1. turn on draggable spectator list somewhere
2. save it 
3. exit the game (the draggable spec list will save where you initially put it no matter what config you load in)
4. re enter the game
5. load the config with the draggable spectator list
6. it just loads in the top corner

**Comment by ok1253** [comment]
this also happens with radar

**Comment by frel0** [comment]
How to fix this:
Disable draggable spectator

**Comment by idiotwithgun** [comment]
le pro tip

**Comment by johnathon-walnut** [comment]
are they meant to save
