### ISSUE TITLE
Fake ping

### ISSUE THREAD

**Issue by GabrielNiccolas3** [tf2cheater2013/Fedoraware#198]
I wanted you to put fake ping

**Comment by j4kst3r** [comment]
no.

**Comment by GabrielNiccolas3** [comment]
:(

**Comment by j4kst3r** [comment]
if you want stuff so badly, add it yourself. or at least make stuff realistic. If you want fake latency and a working autobackstab, $20 = lbox = fake latency + auto backstab

**Comment by GabrielNiccolas3** [comment]
can you increase the backtrack? you don't need much if you want it can even be small

**Comment by GabrielNiccolas3** [comment]
hmm

**Comment by GabrielNiccolas3** [comment]
Can you not put anything?

**Comment by j4kst3r** [comment]
?

**Comment by LEFtt1** [comment]
you can use lmaobox crack but need on other cheat 
which can backstab on backtack because on lmaobox crack work fake latancy on 700

**Comment by LEFtt1** [comment]
or you can use fake lag 22 tick in hvh + autobackstab range 1.0 + rage mode.

**Comment by LEFtt1** [comment]
or you can take the nullcore project (only there you need to update offsents) from github.

**Comment by GabrielNiccolas3** [comment]
send me the lmaobox crack and an injector that can inject it

**Comment by wizardmanperson** [comment]
lbox crack is probably outdated and detected

**Comment by GabrielNiccolas3** [comment]
Still send me the link

**Comment by wizardmanperson** [comment]
why?

**Comment by GabrielNiccolas3** [comment]
Because yes

**Comment by wizardmanperson** [comment]
ok

**Comment by GabrielNiccolas3** [comment]
And an injector that can inject you

**Comment by wizardmanperson** [comment]
go use gameowner or some shit

**Comment by GabrielNiccolas3** [comment]
Just send me the lmaobox crack

**Comment by wizardmanperson** [comment]
ok brb

**Comment by johnathon-walnut** [comment]
Please stop...

**Comment by LEFtt1** [comment]
hey Gabriel here https://brokencore.club/threads/17697/?

**Comment by xxmyn** [comment]
> hey Gabriel here https://brokencore.club/threads/17697/?

I'd prefer if this was the last time anybody linked a russian skid thread on this repo thanks.
