### ISSUE TITLE
What mAgic is this?

### ISSUE THREAD

**Issue by LEFtt1** [tf2cheater2013/Fedoraware#201]
The magic is this if you turn on the fake lag plain and put it on 1 without a button and immediately turn on double tap and charge the number on the server on which max 33 tickrate is installed to substitute for 67 tickrate.

**Comment by xxmyn** [comment]
SPEAK ENGLISH

**Comment by johnathon-walnut** [comment]
Lol.

**Comment by LEFtt1** [comment]
I say if you turn on fake lag and double tap where the server with the maximum number of tick rates is 33, then the number will return to 67 tickrates.

**Comment by j4kst3r** [comment]
You can't charge over 24 ticks. The max you are allowed to charge and release is 24. No cheat has been able to go past 24 as that is the maximum you can obtain. Please stop making completely retarded issues and just use the fucking cheat.

**Comment by LEFtt1** [comment]
lol

**Comment by PeterPumpkinEater69real** [comment]
don't make issues anymore
