### ISSUE TITLE
Keep getting banned for "SMAC 0.8.6.0: ConVar fog_enable violation" from community servers

### ISSUE THREAD

**Issue by Rishtarded** [tf2cheater2013/Fedoraware#202]
the title says it all and i'm new to this tf2 cheat

**Comment by HARrhhv1** [comment]
another newfag nn 🙄🙄🙄🙄

**Comment by johnathon-walnut** [comment]
Stop cheating on community servers OR comment out the fog editing.

**Comment by Rishtarded** [comment]
bro i dont know shit i was literally using someone's config

**Comment by Rishtarded** [comment]
> Stop cheating on community servers OR comment out the fog editing.

how do i disable the fog editing

**Comment by j4kst3r** [comment]
just dont play com servers. thats your best bet.

**Comment by wayven** [comment]
fog is ass disable that and kys 81398218939 8times pls

**Comment by johnathon-walnut** [comment]
Should be fixed
