### ISSUE TITLE
fps decrease when loaded in players

### ISSUE THREAD

**Issue by ok1253** [tf2cheater2013/Fedoraware#203]
**Fedoraware Version Date:**  
current one

## Config used:
https://files.catbox.moe/z095uq.fed

## Description:  
please help i get a major fps decrease when loading in a player model with my config on even when i turn off the esp chams and glow it still lags compared to the default config and not loaded in player models

my config on without loaded player models
![image_2022-04-21_114540486](https://user-images.githubusercontent.com/91960908/164367938-2c2a0000-8b47-4ff5-a344-dc947905a625.png)

default config with loaded player models
![image](https://user-images.githubusercontent.com/91960908/164368027-4587e30a-a6da-4dd6-9579-e174fa325216.png)

my config on with loaded player models
![image](https://user-images.githubusercontent.com/91960908/164368108-f9c68130-ae25-4c2f-9709-20cf3be518b4.png)

(pictures were taken with the neon annihilator for pyro)

**Comment by ok1253** [comment]
i dunno if this happens to others cus i have patata pc

**Comment by ok1253** [comment]
i also just realized that when holding a melee lowers it down more

**Comment by n4zzu** [comment]
the melee weapon thing idk, maybe swing pred is running all the time even if aimkey isnt pressed and that is lowering fps? idk

for the players being rendered in, this will always drop fps. how much you drop is relative to how good the code is behind chams(DME), esp etc. and we all know fedhak >>>>>>>> so no more complain pls

**Comment by xxmyn** [comment]
our chams arent in dme sadly.

also aimbot is always doing something regardless pf whether you are holding the aimkey down or not
