### ISSUE TITLE
Random crash with actual screenshot

### ISSUE THREAD

**Issue by ShiroSeby** [tf2cheater2013/Fedoraware#204]
![image](https://user-images.githubusercontent.com/88360266/164676973-e27851f3-6c99-4d73-97f1-14b6eb661af8.png)

No idea what is causing it and on how to reproduce, I was just playing 2fort for a hour then this happened
I think I enabled the teleporter portal visual (both mode) with my exit tele beside me but it didn't show so I disabled it and got my fps decreased by 50% I think (this was the last thing I did before crashing 5 minutes later)

Also I can't screenshot with anything since the error (screenshot) kept redirecting me to tf2 that froze

**Comment by johnathon-walnut** [comment]
LNX updated imgui recently and it has that assertion now and I'm not too sure why it happens. Are you running the latest build, I recall him commenting the assertion out.

**Comment by lnx00** [comment]
> LNX updated imgui recently and it has that assertion now and I'm not too sure why it happens. Are you running the latest build, I recall him commenting the assertion out.

There are multiple so are assertions. I've commented another one out in my dev branch.

**Comment by ShiroSeby** [comment]
> LNX updated imgui recently and it has that assertion now and I'm not too sure why it happens. Are you running the latest build, I recall him commenting the assertion out.

Yes, I am using the latest build from Apr 21, 2022 (baan's commit)

**Comment by xxmyn** [comment]
just click ignore and it will work trust

**Comment by ShiroSeby** [comment]
> just click ignore and it will work trust

If I click/use keyboard to use the button it will redirect me to tf2 that is freezing, can't do anything about that except closing tf2 using always on top task manager
