### ISSUE TITLE
The game has a freakishly small chance to crash if you make your own config on the map itemtest.

### ISSUE THREAD

**Issue by cactusLMAO** [tf2cheater2013/Fedoraware#205]
just crashing my game when i joining casual

**Comment by xxmyn** [comment]
> 
> 
> **Fedoraware Version Date:**  
> 
> ## Config used:
> 
> 
> 
> ## Description:  
> 
> 
> ## Steps to reproduce:  
> - [ ] I am able to consistently reproduce this error
> 
> 
> Steps to reproduce the behavior:  
> 
> 1. Enable X
> 2. Do Y
> 3. Notice Z
> 
> ## Additional context 
> 
> 
> - [ ] I have included the steps to reproduce to the best I am able to share.

but no, instead of that, you decide to put one sentence, no info, and expect us to somehow know wtf ur on about.

**Comment by cactusLMAO** [comment]
Ok
I used last build Fware (i used fedoraloader) 
I made a my own config on itemtest
When I logged in my game crashed without any notifications

**Comment by xxmyn** [comment]
Wow, where you made your config? I bet that has so much to do with why your game was crashing, maybe try making a config on 2fort?

**Comment by cactusLMAO** [comment]
Oh okay. I will try it now

**Comment by cactusLMAO** [comment]
Nope, joined with standart config and it still crashing

**Comment by xxmyn** [comment]
sry bro u gotta be 13 or older to have a github acc.

**Comment by cactusLMAO** [comment]
Why? im 14

**Comment by xxmyn** [comment]
bro no way u r 14 and think that the map u made ur config on is what's causing u to crash, also, when the template says "what config you used" it doesn't mean "did you make the config and if so, where / when" it means upload the config, come back when ur actually over 13.
