### ISSUE TITLE
Game crashing when i joining casual.

### ISSUE THREAD

**Issue by cactusLMAO** [tf2cheater2013/Fedoraware#206]
Used latest build of Fedoraware (used fedoraloader)
https://files.catbox.moe/7ltc10.fed this config i used
When I log into the casual, my game crashes without any error messages

**Comment by xxmyn** [comment]
![image](https://user-images.githubusercontent.com/70382582/164969808-03053e85-c6df-4eb6-ac27-f4380da42b95.png)

I'm able to connect to game perfectly using this config, please attach PC Specs, and if you are using any configs (matercomfig/vusaline(or vusalo)/chrismaxframes etc.)

Does this issue happen uninjected & does it occur with other cheats.

**Comment by xxmyn** [comment]
thanks for not responding
