### ISSUE TITLE
Auto rocket jump 

### ISSUE THREAD

**Issue by GabrielNiccolabruh** [tf2cheater2013/Fedoraware#209]
the auto rocket jump doesn't work I press mouse 2 it goes normal but in the second it reloads and doesn't fire I press mouse2 and keep pressing it but it doesn't fire and I'm sorry if it works is that I only tested the rocket 2 times

**Comment by sneekyspy** [comment]
m2 is alt fire to stop rockets reloading in middle

**Comment by xxmyn** [comment]
It's because of it running after prediction probably, I don't really care tbh, turn off auto reload if you really want to use the feature, or better yet, learn to rocket jump.
