### ISSUE TITLE
flying cleaver projectile aimbot does not work

### ISSUE THREAD

**Issue by ok1253** [tf2cheater2013/Fedoraware#210]
same issue as some projectile weapons
also maybe make rightous bison aim for chest automatically
when add projectile aim for sandman and giftwrap assassin

**Comment by xxmyn** [comment]
when i care, they are all implemented, they just don't get sorted properly to actually use the projectile aim (probably).

It will be fixed... maybe shortly.

**Comment by xxmyn** [comment]
it does work, liar.
