### ISSUE TITLE
fake lag stops working after recharging dt 

### ISSUE THREAD

**Issue by ok1253** [tf2cheater2013/Fedoraware#217]
cant double tap bots with fake laag is sad

**Comment by xxmyn** [comment]
attach video

**Comment by lnx00** [comment]
It's not possible to use DT and Fakelag together. Fakelag will automatically be disabled when you charge your DT ticks.

**Comment by xxmyn** [comment]
god this is fucking stupid.

don't dt more than 21 ticks, if you're having issues in the future follow the template UNLESS it's self explanatory or you will be blocked from making further issues.
