### ISSUE TITLE
can we bounding box bows 

### ISSUE THREAD

**Issue by HutchyBean** [tf2cheater2013/Fedoraware#222]

**Comment by HutchyBean** [comment]
https://www.youtube.com/watch?v=jvOaUF1Sl5c guys look at this MAGNETIC ARROW WHAAAAAAAAAAAAAAT

**Comment by xxmyn** [comment]
projectile aimbot uses bbox already if im not mistaken

**Comment by johnathon-walnut** [comment]
lol.....................................

**Comment by HutchyBean** [comment]
i hav eno clu how proejctile code work ( i got 64% onm matnhs test) but i dont think it EXists
