### ISSUE TITLE
crusaders crossbow missing on a standing still player

### ISSUE THREAD

**Issue by Vyxolar** [tf2cheater2013/Fedoraware#224]

**Comment by johnathon-walnut** [comment]
ok and how close were they, how soon did they stop moving from when you shot? were they also using fedoraware with the thing that makes u stop moving as soon as u let go of a movement key? there's loads of things that could affect this

**Comment by johnathon-walnut** [comment]
also no config attached nor video?

**Comment by johnathon-walnut** [comment]
and you dont know if you can make it reproduce this constantly?

**Comment by johnathon-walnut** [comment]
template exists for a reason - use it please.
