### ISSUE TITLE
visuals suggestion

### ISSUE THREAD

**Issue by HARrhhv1** [tf2cheater2013/Fedoraware#225]
![image](https://user-images.githubusercontent.com/102487175/166130002-4dfd1f2a-52e6-4a1f-803e-ff84a0f76e09.png)
add these hitbox when u hit someone with proj weapons

![image](https://user-images.githubusercontent.com/102487175/166130060-79bf30ff-cd80-4fe1-8e4e-2c9fdd21e3f1.png)
and if is possible add a different movement simulation trial like, this like when you shoot someone the trial appears like that

and a option to change the position of the conditions on esp

**Comment by xxmyn** [comment]
I have a suggestion: if you want copied rijin visuals (beyond just the dt bar) why don't you just buy their cheat?
