### ISSUE TITLE
funky weird thing

### ISSUE THREAD

**Issue by AscendedSion** [tf2cheater2013/Fedoraware#226]
**Newest Version **  

## Config used:

https://files.catbox.moe/gfadvl.fed

## Description:  

Cheat crashes on inject due to [THIS](http://cdn.hvh.tf/u/IN0kwS.png)

## Steps to reproduce:  
- [x] I am able to consistently reproduce this error

yes you can consistently get this error, just inject cheat lol

1. open tf2
2. open injector
3. inject fware(release).dll

## Additional context 

- [x] I have included the steps to reproduce to the best I am able to share.

**Comment by j4kst3r** [comment]
cry about it lol

**Comment by xxmyn** [comment]
I can't tell if you are joking or not.

SetFontGlyphSet (the vfunc you happened to cut the name out of in your screenshot) is only called by the cheat when fonts are loaded/reloaded.

do you have the DEFAULT windows font called Verdana installed on your computer (C:/WINDOWS/FONTS/VERDANA.TTF)?
do you have any settings for TF2 that have anything to do with fonts?
does this issue occur with the default fedoraware config?

**Comment by AscendedSion** [comment]
yes i have the default windows font called verdana
no i do not have any tf2 settings that do anything with fonts
i cant inject the cheat without it crashing so idk if it does it with default cfg

**Comment by johnathon-walnut** [comment]
reinstall your game
