### ISSUE TITLE
Debug build not injecting and crashes hl2.exe - "Access violation reading location"

### ISSUE THREAD

**Issue by Loji-i** [tf2cheater2013/Fedoraware#227]
**Fedoraware Version Date: Current/Newest**  

## Config used:
Not applicable.

## Description:  
Debug build doesn't inject and crashes hl2.exe due to "Access violation reading location".

## Steps to reproduce:  
1. Build the current Fedoraware debug build.
2. Attach VS Debugger to hl2.exe
3. Inject FWare(Debug).dll using Xenos with settings (as the tutorial on the main page showed):
![image](https://user-images.githubusercontent.com/103847093/166176537-18faa72d-6699-47e8-87a5-e0f373dfb4a5.png)
4. Debugger throws errors: [Pastebin link, password 'fware'](https://pastebin.com/L4y1FekS)

## Additional context 
Trying to debug _another_ bug other people including me encounter where you crash upon saving a config, and the .fed config file gets cleared.

But instead run in to this, let me know if you need more information.

**Comment by xxmyn** [comment]
inject with native inject when debugging.
