### ISSUE TITLE
crash when want save cfg

### ISSUE THREAD

**Issue by ilya228011** [tf2cheater2013/Fedoraware#229]
**Fedoraware Version Date:**  

## Steps to reproduce:  
- [ ] I am able to consistently reproduce this error

1. Enable X
2. Do Y
3. Notice Z

## Additional context 

- [ ] I have included the steps to reproduce to the best I am able to share.

**Comment by gayblackirony** [comment]
ty

**Comment by FourteenHvH** [comment]
Bro? You didn't say anything or provide and you expect fixes

**Comment by Loji-i** [comment]
I know the bug he's mentioning; though the debug version doesn't seem to encounter it, only the release version.
Both fedoraloader version/injection and a self-built version (with xenos injection) encounter it.

So... Just use the debug version, until there's some kind of fix for release.

**Comment by ShiroSeby** [comment]
> I know the bug he's mentioning; though the debug version doesn't seem to encounter it, only the release version. Both fedoraloader version/injection and a self-built version (with xenos injection) encounter it.
> 
> So... Just use the debug version, until there's some kind of fix for release.

So do I build in debug x86 mode?

**Comment by xxmyn** [comment]
if you want to avoid it crashing just save & make your config in debug and then load it in release.

release is significantly more stable, I have no idea what causes the crashing on release and I can't replicate it at all.
