### ISSUE TITLE
Optimisation

### ISSUE THREAD

**Issue by canedoly** [tf2cheater2013/Fedoraware#23]
Since the optimization is pretty bad in this cheat, you should add [this](https://github.com/Facepunch/garrysmod/pull/1590) glow its apparently a lot better than blur glow and it looks nice (Its lua tho)
Crouch jump like crouching before jumping or mid-air so you will jump higher and maybe break some bad aimbot?

Also when I charge the DT after a second I just randomly teleport some ticks making the DT not instant

**Comment by johnathon-walnut** [comment]
no

**Comment by johnathon-walnut** [comment]
the glow and chams are not the reason the optimization is bad

**Comment by canedoly** [comment]
that makes sense, but what about other features? Is it possible to know which drain your fps the most?

**Comment by HutchyBean** [comment]
its bering called on frame render start.

**Comment by ilya228011** [comment]
HOW TO SAVE CFG

**Comment by canedoly** [comment]
I've found some bugs like
"Sky" in modulations doesn't save, so if you disabled it and saved the config, after you load the config back, you need to disable it again, don't know about other stuff in modulations if they save
Big nasty bullet tracer doesn't work with crits on red team, don't know about blue
Using aimbot with streaming weapons like, minigun or pistol makes you stop moving if you got antiwarp enabled
[weirdglitch.zip](https://github.com/tf2cheater2013/Fedoraware/files/8109744/weirdglitch.zip) will try making a new config to see if the issue is still there

**Comment by xxmyn** [comment]
I have tried to fix the issues I was able to reproduce, please close issue if they are no longer present.

**Comment by johnathon-walnut** [comment]
Actually I might add this glow

**Comment by xxmyn** [comment]
glow has been added
