### ISSUE TITLE
crashing

### ISSUE THREAD

**Issue by certifiedsw4gger** [tf2cheater2013/Fedoraware#231]
**Fedoraware Version Date:**  

## Config used:
?

## Description:  
crashing on manual map injection with xenos
## Steps to reproduce:  
-?

?
## Additional context 
 ples help yes nagas

- [ ] I have included the steps to reproduce to the best I am able to share.

**Comment by johnathon-walnut** [comment]
thanks man really nice usage of the template...
im convinced this is a troll by one person at this point
