### ISSUE TITLE
AUTOSTAB BREAKS AFTER FIRST MATCH but sometimes I can get it working by turning buttons on and off

### ISSUE THREAD

**Issue by Sung-jin-Lim** [tf2cheater2013/Fedoraware#232]
**Fedoraware Version Date:**  

## Steps to reproduce:  
- [ ] I am able to consistently reproduce this error

1. Enable X
2. Do Y
3. Notice Z

## Additional context 

- [ ] I have included the steps to reproduce to the best I am able to share.

**Comment by xxmyn** [comment]
when we say use the template we mean fill in the info.

**Comment by GabrielNiccolabruh** [comment]
he said that the auto backstab breaks after the first game this also happens with me fix it now

**Comment by xxmyn** [comment]
SHUT THE FUCK UP

**Comment by johnathon-walnut** [comment]
> he said that the auto backstab breaks after the first game this also happens with me fix it now

Hope you know that saying fix it now makes everyone involved in this very unlikely to fix it out of spite for your demanding language.
