### ISSUE TITLE
Crashes when saving config

### ISSUE THREAD

**Issue by fast-overlocking** [tf2cheater2013/Fedoraware#233]
From the first time I created a config, it was saved.
Then when you load the config, change the settings and save it - crash.
It's not the first time I've encountered this. Even if done from scratch.

**Comment by lnx00** [comment]
Yes, this is a feature

**Comment by lnx00** [comment]
> > Yes, this is a feature
> 
> how to remove it?

Buy Fedoraware Premium to store your configs permanently

**Comment by gayblackirony** [comment]
join discord to discuss the price
