### ISSUE TITLE
crashing with manual map injection type (xenos)

### ISSUE THREAD

**Issue by certifiedsw4gger** [tf2cheater2013/Fedoraware#235]
Soooo i have problem with injecting with manual map, when i inject with ll it just injects and its working normally (native inject) but when i use the manual map it just crashes on inject.

**Comment by xxmyn** [comment]
Debug or Release build?

**Comment by johnathon-walnut** [comment]
Solution: just native inject???

**Comment by xxmyn** [comment]
please stop trolling mfed!!!

**Comment by certifiedsw4gger** [comment]
> Solution: just native inject??? "The source code is most likely DETECTED, use a VMProtected manual mapping injector"  i dont trust random public vac bypasses so i guess i have to use manual mapping injector to not get banned???? idk




> Debug or Release build? Release

**Comment by johnathon-walnut** [comment]
> > Solution: just native inject??? "The source code is most likely DETECTED, use a VMProtected manual mapping injector"  i dont trust random public vac bypasses so i guess i have to use manual mapping injector to not get banned???? idk
> 
> > Debug or Release build? Release

Ignore that shit in readme, it's nonsense. Use danielkrupinskis vac bypass and xenos' native injection method.

**Comment by xxmyn** [comment]
Manual mapping won't stop you from getting banned.

Since you said you were using xenos, are you using Ingore TLS and Erase PE Headers when injecting?
Has this issue been a constant occurrence or has it only started recently?
Have you tried removing your configs from the /fedfigs folder and seeing if the cheat injects properly then?
How long are you waiting prior to injecting (wait at least 30 seconds after playing around with the console & item screen before injecting)
Are you injecting in the menu or in game?

**Comment by certifiedsw4gger** [comment]
> > > Solution: just native inject??? "The source code is most likely DETECTED, use a VMProtected manual mapping injector"  i dont trust random public vac bypasses so i guess i have to use manual mapping injector to not get banned???? idk
> > 
> > 
> > > Debug or Release build? Release
> 
> Ignore that shit in readme, it's nonsense. Use danielkrupinskis vac bypass and xenos' native injection method.
well i dont very trust the vac bypass since i already got banned w it but ok i will try on some fresh acc 





> Manual mapping won't stop you from getting banned.
> 
> Since you said you were using xenos, are you using Ingore TLS and Erase PE Headers when injecting? Has this issue been a constant occurrence or has it only started recently? Have you tried removing your configs from the /fedfigs folder and seeing if the cheat injects properly then? How long are you waiting prior to injecting (wait at least 30 seconds after playing around with the console & item screen before injecting) Are you injecting in the menu or in game?

yes i am using tls and erease pe headers while injecting. well i just wanted to try the cheat so it started recently. i dont have any cfgs saved. and i wasnt like waiting i just opened the game waited so the game will load and i just inject and i injected inmenu

**Comment by johnathon-walnut** [comment]
> > > > Solution: just native inject??? "The source code is most likely DETECTED, use a VMProtected manual mapping injector"  i dont trust random public vac bypasses so i guess i have to use manual mapping injector to not get banned???? idk
> > > 
> > > 
> > > > Debug or Release build? Release
> > 
> > 
> > Ignore that shit in readme, it's nonsense. Use danielkrupinskis vac bypass and xenos' native injection method.
> 
> well i dont very trust the vac bypass since i already got banned w it but ok i will try on some fresh acc
> 
> > Manual mapping won't stop you from getting banned.
> > Since you said you were using xenos, are you using Ingore TLS and Erase PE Headers when injecting? Has this issue been a constant occurrence or has it only started recently? Have you tried removing your configs from the /fedfigs folder and seeing if the cheat injects properly then? How long are you waiting prior to injecting (wait at least 30 seconds after playing around with the console & item screen before injecting) Are you injecting in the menu or in game?
> 
> yes i am using tls and erease pe headers while injecting. well i just wanted to try the cheat so it started recently. i dont have any cfgs saved. and i wasnt like waiting i just opened the game waited so the game will load and i just inject and i injected inmenu

If you don't trust yourself to vac bypass, try LNX's loader
