### ISSUE TITLE
duck jump and autoback stab bad very bad

### ISSUE THREAD

**Issue by ok1253** [tf2cheater2013/Fedoraware#236]
**Fedoraware Version Date:**  
latest

## Description:  
doesnt need a config since it works with any config wit duck jump and autobcak trab

## Steps to reproduce:  
- [x] I am able to consistently reproduce this error

1.enable duckjump
2.enable autobackstyaab
3.go on tr_watlkwauy
4.jump on npc head while holding crouc buton or
4. jump on npc head not holding crouc buton
5. it wont stab esepcically with th the first 4th (holind croyuch butotn0

- [x] I have included the steps to reproduce to the best I am able to share.

**Comment by johnathon-walnut** [comment]
You're taking the piss.

**Comment by ok1253** [comment]
thanks

**Comment by xxmyn** [comment]
banned from interacting with the repo just for this ngl
