### ISSUE TITLE
Fedoraloader error

### ISSUE THREAD

**Issue by GabrielNiccolabruh** [tf2cheater2013/Fedoraware#237]
I installed Fedoraloader and when I open the error api-ms-win-core-winrt-l1-1-0.dll appears

**Comment by lnx00** [comment]
1. [Wrong section](https://github.com/lnx00/Fedoraloader/issues)
2. [Please read the README next time](https://github.com/lnx00/Fedoraloader#cant-run-fedoraloader)

Fedoraloader is **not** supported on Windows 7.
