### ISSUE TITLE
Body aim if lethal doesnt work.

### ISSUE THREAD

**Issue by DEVILISHTUNE** [tf2cheater2013/Fedoraware#238]
Anytime someone has little to no heath my sniper still shoots for the head. never did that before. whats diffrent? (Aim for body if lethal is checked)

**Comment by DEVILISHTUNE** [comment]
the head hits every time. the ambi. does body shot. something with the sniper i think

**Comment by xxmyn** [comment]
i remade the way hitboxes are dealt with and i probably broke something with baim if lethal

**Comment by DEVILISHTUNE** [comment]
Alright. ill keep an eye out for an update/ect.

**Comment by xxmyn** [comment]
from what i can see it looks like it aims for head only if you can hit it
