### ISSUE TITLE
HOW TO SAVE CFG LOL

### ISSUE THREAD

**Issue by ilya228011** [tf2cheater2013/Fedoraware#24]
**Fedoraware Version Date:**  

## Steps to reproduce:  
- [ ] I am able to consistently reproduce this error

1. Enable X
2. Do Y
3. Notice Z

## Screenshot of cheats enabled  

- [ ] I have included the steps to reproduce to the best I am able to share.

**Comment by ilya228011** [comment]
broooo tyyyyy

omg its workrkrk

**Comment by hyperventilation** [comment]
""ilya""
