### ISSUE TITLE
add custom imgui styles again

### ISSUE THREAD

**Issue by PeterPumpkinEater69real** [tf2cheater2013/Fedoraware#240]
its very nice. imgui styles are very good you can set the style of imgui and the styles are very stylish and stuff like that

**Comment by xxmyn** [comment]
I assigned mfed as a joke, simply, no.

**Comment by johnathon-walnut** [comment]
I don't see why we couldn't but I'm not willing to spend time to make this how I'd want (saving/loading like reshade)
