### ISSUE TITLE
Anti aim

### ISSUE THREAD

**Issue by GabrielNiccolabruh** [tf2cheater2013/Fedoraware#243]
when I use Anti aim with edge and left for everyone, does it look like I'm from the side or from the front?

**Comment by j4kst3r** [comment]
https://tenor.com/view/man-tf2hvh-tf2-antiaim-gif-20554783

**Comment by j4kst3r** [comment]
jebem ti mater gabriel

**Comment by gayblackirony** [comment]
^^^

**Comment by j4kst3r** [comment]
+1

**Comment by xxmyn** [comment]
whatever you have selected as your fake yaw is what the enemy sees (it's not perfectly what they see but it's close)
