### ISSUE TITLE
NOMOTD and PickClass are now no working

### ISSUE THREAD

**Issue by ghost** [tf2cheater2013/Fedoraware#248]
**Fedoraware Version Date:**  7 may

## Description:  
NOMOTD and PickClass are now no working. It feels like they are completely missing.

With [**Merge pull request 245 from lnx00/patch-1**](https://github.com/tf2cheater2013/Fedoraware/commit/82dd34bf866f6bf205a6b7d953ab6eea9ddbe061) they worked perfectly.

**Comment by lnx00** [comment]
#251 should've fixed this
