### ISSUE TITLE
Auto Accept Item

### ISSUE THREAD

**Issue by GabrielNiccolabruh** [tf2cheater2013/Fedoraware#249]
add an option that automatically accepts items when dropped

**Comment by johnathon-walnut** [comment]
how?

**Comment by xxmyn** [comment]
you'd have to check if the notification is for an item drop or if it's for a duel etc.

**Comment by GabrielNiccolabruh** [comment]
even so add this nobody almost uses duel mode

**Comment by johnathon-walnut** [comment]
I can look into doing this properly but it seems hard to test since the drops are random

**Comment by xxmyn** [comment]
Uhh what?

If somebody tries to duel you, you will instantly accept it, if you have found a new game, you will instantly be connected to it, if you get a drop sure it will accept it, from memory it will also open the window to show you it, if somebody does that "invite to trade" shit to you, you will instantly accept it, any in game request will immediately be accepted.

gir489 made a comment ages ago that I remember about checking whether the "glint" was for a duel, I imagine if you could find that comment you could just ez paste it all and then change it to be for an item drop.

**Comment by xxmyn** [comment]
> even so add this nobody almost uses duel mode

Also pretty bold might I add to demand we add features that aren't really that needed, like most people have the capacity to just accept the drop normally, and auto-accepting drops is just, trash.

Lbox does this however, so if you wanna be the one person who uses that feature in lbox, go ahead and buy it.

**Comment by johnathon-walnut** [comment]
I use it in lbox :^)

**Comment by GabrielNiccolabruh** [comment]
-_-

**Comment by johnathon-walnut** [comment]
> 

Also the point is that it accepts items before the notification comes up and doesn't interrupt you right?

**Comment by xxmyn** [comment]
it's of very little use and if you have a hud that doesn't make it a popup you kind of forget about them after a while anyway.

**Comment by GabrielNiccolabruh** [comment]
i would buy lmaobox but i don't have money

**Comment by xxmyn** [comment]
it is 20 dollars.

**Comment by GabrielNiccolabruh** [comment]
buy me

**Comment by xxmyn** [comment]
no?
