### ISSUE TITLE
particle tracers don't work

### ISSUE THREAD

**Issue by idiotwithgun** [tf2cheater2013/Fedoraware#253]
**Fedoraware Version Date:**  https://github.com/tf2cheater2013/Fedoraware/actions/runs/2286370863

## Config used:
any cfg

## Description:  
none of particle tracers are working for me
## Steps to reproduce:  
1:Turn on any Particle Tracers
2:No tracers at all

**Comment by johnathon-walnut** [comment]
Do you have r_firstperson_tracers set to 0?

**Comment by idiotwithgun** [comment]
Uh, i have no idea what is that, is it console command?

**Comment by johnathon-walnut** [comment]
Yes, its a console command, if it's 0 you won't see tracers in first person, set it to 1

**Comment by idiotwithgun** [comment]
> r_drawtracers_firstperson 0

oh, thanks alot! that worked

**Comment by idiotwithgun** [comment]
> Yes, its a console command, if it's 0 you won't see tracers in first person, set it to 1

ok, thanks

**Comment by lnx00** [comment]
It would probably be a good idea to automatically enable r_drawtracers_firstperson when the user enables tracers.
