### ISSUE TITLE
medic bug

### ISSUE THREAD

**Issue by canedoly** [tf2cheater2013/Fedoraware#255]
If you are playing medic, in thirdperson, medigun is out and holding the aimkey the aimbot will try to heal itself causing it to spin like crazy

**Comment by xxmyn** [comment]
I couldn't recreate this, since you were such an awesome dude and attached a video of the bug along with ur config I'll try my hardest to fix it :D (fuck you i hope you die)

**Comment by canedoly** [comment]
the config is default

https://user-images.githubusercontent.com/81353241/167294266-b7d6fec2-a9f4-4a19-84a4-f7d712700877.mp4

i didn't configure sharex so fps are "low"

**Comment by xxmyn** [comment]
so wholesome, so so wholesome.

**Comment by johnathon-walnut** [comment]
i told u this happens lol

**Comment by lnx00** [comment]
You spin me right 'round, baby, right 'round
