### ISSUE TITLE
Revert Projectile Aim To Previous Version 

### ISSUE THREAD

**Issue by yujispin990** [tf2cheater2013/Fedoraware#262]
Projectile Aim is performing much worse and much slower,previous version had it almost perfect if not perfect.

in my opinion at least.

**Comment by canedoly** [comment]
just download an older version if the new one has bugs

**Comment by yujispin990** [comment]
the new version had some wierd hitbox selection even tho i had it on head,tested every hitbox option it had and it was not doing well at all,took too long to shoot and even if it did it was not accurate, it would miss bodyshots as well,where as the previous version was a monster it predicted trolldier going so fast in the air and right before he lands it had hit a perfect headshot,i wished i'd recorded it,enemy trolldier was baffled and speechless,so i implore you to at least release the previous version,i was using the loader so i could not tell you which version number i had used,but i was sure it was right before they changed projectile aim options.

**Comment by yujispin990** [comment]
does anyone have the version before the change?

**Comment by yujispin990** [comment]
oh my lord,i did not know that,thank you so much!!!
