### ISSUE TITLE
SMAC fog_enable violation

### ISSUE THREAD

**Issue by pelinnn-leaks** [tf2cheater2013/Fedoraware#264]
How to prevent SMAC 0.8.6.3: ConVar fog_enable violation?
i get autoban from the servers protected by SMAC even if i disable every option in fedoraware :/

**Comment by xxmyn** [comment]
https://github.com/tf2cheater2013/Fedoraware/blob/115d6f5f4014b95fe3a90f134b2c9e01487f0c2c/Fedoraware/TeamFortress2/TeamFortress2/Features/Menu/Menu.cpp#L1286

**Comment by pelinnn-leaks** [comment]
> https://github.com/tf2cheater2013/Fedoraware/blob/115d6f5f4014b95fe3a90f134b2c9e01487f0c2c/Fedoraware/TeamFortress2/TeamFortress2/Features/Menu/Menu.cpp#L1286

thanks m8 i'll try to Comment this line, and hopefully the owner and the mods take a look into this issue :)

**Comment by xxmyn** [comment]
you could remove the CVAR_FLAG_REPLICATED flag from it and see if it stops smac from detecting it.

**Comment by pelinnn-leaks** [comment]
> you could remove the CVAR_FLAG_REPLICATED flag from it and see if it stops smac from detecting it.

that makes sense! thank you so much for the useful infos (y)
i'll try the methods asap!

**Comment by xxmyn** [comment]
well that was the wrong flag but the i cant get the one i was thinking of to work.

if you just enable fog and have fog density at 0 it probably won't check that (i know stac doesn't)

**Comment by pelinnn-leaks** [comment]
> well that was the wrong flag but the i cant get the one i was thinking of to work.
> 
> if you just enable fog and have fog density at 0 it probably won't check that (i know stac doesn't)

wow that really worked! i just tested the method and SMAC didn't take any action, thank you so much for the help! i really appreciate it! finally no more autoban when i join some servers :100:

**Comment by johnathon-walnut** [comment]
Should be fixed
