### ISSUE TITLE
[Request] Followbot / Walkbot

### ISSUE THREAD

**Issue by pelinnn-leaks** [tf2cheater2013/Fedoraware#266]
it would be great to have a feature like followbot/walkbot.
Fedoraware is my favorite and best cheat that I've been using for a while, and I hope to see these features in the future.
and thank you so much for providing us with this awesome masterpiece!

**Comment by FourteenHvH** [comment]
Buy lmaobox or use cathook issue fixed thanks stinky pedo

**Comment by johnathon-walnut** [comment]
> Buy lmaobox or use cathook issue fixed thanks stinky pedo

Please stop commenting

**Comment by lnx00** [comment]
Hmm shouldn't be too difficult

**Comment by johnathon-walnut** [comment]
I appreciate the issue but I really would not want this adding

**Comment by pelinnn-leaks** [comment]
> I appreciate the issue but I really would not want this adding

I'll probably only use it against casual bots for the memes xD

**Comment by zeroxeclipse** [comment]
+1 good fuature

**Comment by HARrhhv1** [comment]
> it would be great to have a feature like followbot/walkbot. Fedoraware is my favorite and best cheat that I've been using for a while, and I hope to see these features in the future. and thank you so much for providing us with this awesome masterpiece!

g ood
