### ISSUE TITLE
Configures gone

### ISSUE THREAD

**Issue by FFJ11** [tf2cheater2013/Fedoraware#267]
My configures were gone , wtf happened

**Comment by xxmyn** [comment]
251fd06f2cbc8b60987f97aeb3bc5b9dc108871b happened... 8 days ago.

**Comment by idiotwithgun** [comment]
https://tubular-gnome-df8c8a.netlify.app/
open your .fed cfgs with notepad, cope and paste everything into the converter, change file from .fed to .fw, copy and paste everything from converter to the .fw file
do again for each cfg you want
or just make them again lol
