### ISSUE TITLE
Suggestion: Mark Players as [Cheater / Admin]

### ISSUE THREAD

**Issue by zeroxeclipse** [tf2cheater2013/Fedoraware#268]
I have a suggestion for the playerlist, please add an option to mark someone as a cheater/admin and receive a warning in the party chat when they join the server.
I usually use the BOT detector, but it would be much better if we can mark them directly from Fedora.

**Comment by xxmyn** [comment]
savable player priorities :thinking:

**Comment by lnx00** [comment]
> savable player priorities 🤔

We should fix the playerlist first before creating piorities

**Comment by johnathon-walnut** [comment]
What's broken?

**Comment by lnx00** [comment]
Flickering and sometimes players are missing from it for some reason

**Comment by johnathon-walnut** [comment]
oh yeah lol CAM moment

**Comment by zeroxeclipse** [comment]
> savable player priorities thinking

What I mean is an option to save the Steam ID [U:1:XXXXXXXXXX] of a selected cheater/admin/player from the player list into a JSON file.

And Fedora checks the Steam ID of players who just joined the server and compares it with the Steam IDs in the JSON file,
If there is a match, you will receive a warning/notification in the group chat.

Similar idea of this project: https://github.com/PazerOP/tf2_bot_detector

but light ware :)

**Comment by HARrhhv1** [comment]
> > savable player priorities thinking
> 
> What I mean is an option to save the Steam ID [U:1:XXXXXXXXXX] of a selected cheater/admin/player from the player list into a JSON file.
> 
> And Fedora checks the Steam ID of players who just joined the server and compares it with the Steam IDs in the JSON file, If there is a match, you will receive a warning/notification in the group chat.
> 
> Similar idea of this project: https://github.com/PazerOP/tf2_bot_detector
> 
> but light ware :)

i like

**Comment by relaxtakenotes** [comment]
> Flickering and sometimes players are missing from it for some reason

entity cache 🖕🏻

**Comment by johnathon-walnut** [comment]
fo real
