### ISSUE TITLE
setcvar bug

### ISSUE THREAD

**Issue by canedoly** [tf2cheater2013/Fedoraware#269]
![obraz](https://user-images.githubusercontent.com/81353241/168286017-c855cf58-4ce0-42f1-82bd-b939545f098f.png)
when i use setcvar to set something like sv_maxupdaterate 1000 it's actually set to sv_maxupdaterate sv_maxupdaterate 1000, like in the screenshot provided. (ignore the sv_maxupdaterate after the setcvar command)

**Comment by johnathon-walnut** [comment]
LNX when I said take a look at it I didn't mean break it idiot

**Comment by xxmyn** [comment]
it new anti cheat bpyass tuest us!

**Comment by lnx00** [comment]
> LNX when I said take a look at it I didn't mean break it idiot

:trollface:
