### ISSUE TITLE
Bug: The chat is not working

### ISSUE THREAD

**Issue by zeroxeclipse** [tf2cheater2013/Fedoraware#272]
I noticed in recent versions of Fedora a weird bug, after injecting it and joining any server, I can't see messages from server members and the messages I send are invisible.

Currently I'm using an old version of Fedora so I can chat!

Please take a look and thanks!

**Comment by lnx00** [comment]
Type this into console:
`cl_mute_all_comms 0`

**Comment by zeroxeclipse** [comment]
I'll try it rn :)

**Comment by zeroxeclipse** [comment]
i've tried the command but the chat is still invisible :(

**Comment by lnx00** [comment]
> i've tried the command but the chat is still invisible :(

I think i have an potential fix for this. Will push later

**Comment by zeroxeclipse** [comment]
Thank you!

**Comment by zeroxeclipse** [comment]
Omg this a huge update! i'll definitely test it as soon the pull request is accepted! good job man o7

**Comment by idiotwithgun** [comment]
^facts!
