### ISSUE TITLE
requests

### ISSUE THREAD

**Issue by HARrhhv1** [tf2cheater2013/Fedoraware#275]
add a option to shoot your teammates when mp_friendlyfire is on....
and Auto uber when someone says "Activate Charge" 

pls :pleading_face:

**Comment by j4kst3r** [comment]
please stop making these retarded issues that are so niche

**Comment by gayblackirony** [comment]
https://www.youtube.com/watch?v=Irgp6XF9HX8&list=RDMM&index=25

**Comment by gayblackirony** [comment]
https://www.youtube.com/watch?v=Irgp6XF9HX8&

**Comment by frel0** [comment]
> please stop making these retarded issues that are so niche

the reason why this community sucks ASS.

**Comment by xxmyn** [comment]
I might add the mp_friendlyfire one if I ever get around to adding better ignore conditions, I am not adding the second one.

**Comment by HARrhhv1** [comment]
> I might add the mp_friendlyfire one if I ever get around to adding better ignore conditions, I am not adding the second one.

Ok is fine
