### ISSUE TITLE
A small bug

### ISSUE THREAD

**Issue by zeroxeclipse** [tf2cheater2013/Fedoraware#276]
Everything is perfect in the latest release, but I noticed that when I press the jump button, I high jump every time, no matter what platform I'm on!

And the option that makes each jump as high as possible is disabled.

**Comment by xxmyn** [comment]
@lnx00

**Comment by lnx00** [comment]
Which feature do you mean? Duck jump?

**Comment by zeroxeclipse** [comment]
I guess the Edge Jump is auto enabled in the background

**Comment by xxmyn** [comment]
attach your fucking config you RETARD

**Comment by johnathon-walnut** [comment]
So mean

**Comment by xxmyn** [comment]
people make issues, attach nothing, do nothing to try and get it fixed, and then expect us to be omniscient and just fix le issue.

**Comment by xxmyn** [comment]
Just tested jumping, cannot recreate this issue.
