### ISSUE TITLE
According to Fedora..

### ISSUE THREAD

**Issue by tf2embl** [tf2cheater2013/Fedoraware#283]
According to fedora this is blast
![download-_10_](https://user-images.githubusercontent.com/104022436/169078654-43a46785-b8c6-4db7-ae9c-f0ac2a0231a9.png)
 ( sorry for small text )
 [ blast and bullet are inverted 
 bullet = blast
 blast = bullet ]

**Comment by GabrielNiccolabruh** [comment]
who plays doctor doctor is the worst class

**Comment by HARrhhv1** [comment]
> who plays doctor doctor is the worst class

mad medic best class

**Comment by HARrhhv1** [comment]
> According to fedora this is blast ![download-10](https://user-images.githubusercontent.com/104022436/169078654-43a46785-b8c6-4db7-ae9c-f0ac2a0231a9.png) ( sorry for small text ) [ blast and bullet are inverted bullet = blast blast = bullet ]

they need to fix vacc text fr

**Comment by FourteenHvH** [comment]
It's easy bro fix yourself 
(If I remember)
61 = bullet
62 = blast
63 = fire
Esp.cpp thanks!!!

**Comment by johnathon-walnut** [comment]
yeah lol i just put them in the wrong place

**Comment by lnx00** [comment]
Fixed, will push with the next pr
