### ISSUE TITLE
Fix yo dt w bt

### ISSUE THREAD

**Issue by FourteenHvH** [tf2cheater2013/Fedoraware#286]
Backtrack with dt
Tick count isn't right and it misses
^
Issue explained
Video: https://youtu.be/Ezh1iLd6VyM
With hate 14
(Edited version and no I didn't touch backtrack so it shouldn't miss nor the aimbot.)

**Comment by johnathon-walnut** [comment]
i wont

**Comment by FourteenHvH** [comment]
I just said a real issue not other bs, but well who cares xd

**Comment by johnathon-walnut** [comment]
ill be honest i just dont know how to lol
