### ISSUE TITLE
dt,bt or crithack problem (major fps drops)

### ISSUE THREAD

**Issue by whyskyboxchange** [tf2cheater2013/Fedoraware#287]
**Fedoraware Version Date:**  

## Config used:
https://files.catbox.moe/yrjm3b.fw -- my config

## Description:  
i am pretty sure this is caused either by dt, bt or crit hack but im very certain this is crithack. when i use crithack for a decent period like 10 mins or 20 with dt or without when i use crithack key and use aim key my fps drops to like 20 and then back to my usual amount ( like 150 ig )

## Steps to reproduce:  
- [x] I am able to consistently reproduce this error

1. Enable DT and CritHack
2. Use both of them for like 10 to 20 minutes
3. Game starts to lag when I try to use both of them

## Additional context 
this bug is kinda annoying it might be config issue but im guessing not since crithack is already buggy

- [x] I have included the steps to reproduce to the best I am able to share.

**Comment by canedoly** [comment]
probably crithack issue, just don't crit as much

**Comment by whyskyboxchange** [comment]
> 

yeah prob but still i wanna 1 shot heavies or just idk use crit hack in general

**Comment by whyskyboxchange** [comment]
why did my reply not work

**Comment by FourteenHvH** [comment]
Never had issues with fps, prob render issues or game

**Comment by whyskyboxchange** [comment]
> Never had issues with fps, prob render issues or game

i went in third person and the fps problem basically fixed itself (i am confused??)

**Comment by FourteenHvH** [comment]
I will see in my build if it happens if not then look into it with pub build.. since I have removed glow and other stuff that kill fps and crithack is a bit changed for me so.. yea let me look into it

**Comment by whyskyboxchange** [comment]
H

>

**Comment by whyskyboxchange** [comment]
> I will see in my build if it happens if not then look into it with pub build.. since I have removed glow and other stuff that kill fps and crithack is a bit changed for me so.. yea let me look into it

ok

**Comment by XJN2** [comment]
Crithack should've been fixed now, I think. My dumbass self will look at the DT and Backtrack soon.

**Comment by frel0** [comment]
> Crithack should've been fixed now, I think. My dumbass self will look at the DT and Backtrack soon.

only crithack made your game lag
backtrack is supposed to be laggy (you cant fix that)
and dt isnt lagging at all
