### ISSUE TITLE
Crithack lagging fixed in less than 5 minutes

### ISSUE THREAD

**Issue by frel0** [tf2cheater2013/Fedoraware#292]
whoever put loops in here, is a dumbass

![image](https://user-images.githubusercontent.com/90924169/169316302-45de5517-1091-47fe-8cf4-63e021320041.png)
replace loops with 15
![image](https://user-images.githubusercontent.com/90924169/169316487-fd04b037-bda5-4bb6-9813-7f4be183b463.png)

line 51 and crithack.cpp
also when looping shit, please know that the performance will be dogshit

**Comment by XJN2** [comment]
Opening a pull-request soon to fix this.

**Comment by xDroflLOL** [comment]
wonderful

**Comment by XJN2** [comment]
This should be closeable now, PR got merged

**Comment by lnx00** [comment]
How did you come up with 15 loops? Is there a specific reason for this number?

**Comment by frel0** [comment]
it literally doesnt fucking matter what the value is, 15 should be the best and doesnt lag your game like your LOOP that loops forever until u turn off crithack

**Comment by frel0** [comment]
> You clearly don't know what you're talking about or what the code you've sent is actually doing.

bro? if you loop the crithack thing it makes your game lag literally try it yourself my man

**Comment by lnx00** [comment]
> > You clearly don't know what you're talking about or what the code you've sent is actually doing.
> 
> bro? if you loop the crithack thing it makes your game lag literally try it yourself my man

I can't test it because i'm not poor and my pc can handle the loops perfectly fine

**Comment by frel0** [comment]
> 

![HELLO](https://user-images.githubusercontent.com/90924169/169369070-bf000aea-18e6-4730-9fc1-30b3b18b135f.png)

HAPPENS TO ME TOO BTW.... youre iqless asf

**Comment by canedoly** [comment]
is this like, lower amount = higher performance but fewer crits?
Because i've noticed that I don't crit that much with any weapon that isn't melee

**Comment by xDroflLOL** [comment]
> is this like, lower amount = higher performance but fewer crits? Because i've noticed that I don't crit that much with any weapon that isn't melee

xddddddddddddddddddddddddddddddddddddd

**Comment by frel0** [comment]
> is this like, lower amount = higher performance but fewer crits? Because i've noticed that I don't crit that much with any weapon that isn't melee

if it was 1 nothing would change (probably?)

**Comment by lnx00** [comment]
> is this like, lower amount = higher performance but fewer crits? Because i've noticed that I don't crit that much with any weapon that isn't melee

That's what i wanted to know. How can we be sure that scanning 15 ticks is enough? Because i am pretty sure that it reduces the amount of crits. Some other crithack sources search 4096 ticks so i wanted to know where the number 15 came from.

**Comment by frel0** [comment]
> > is this like, lower amount = higher performance but fewer crits? Because i've noticed that I don't crit that much with any weapon that isn't melee
> 
> That's what i wanted to know. How can we be sure that scanning 15 ticks is enough? Because i am pretty sure that it reduces the amount of crits. Some other crithack sources search 4096 ticks so i wanted to know where the number 15 came from.

it literally works on any value how can u not understand what im saying

**Comment by johnathon-walnut** [comment]
why are you scared of loops

**Comment by xDroflLOL** [comment]
> > > is this like, lower amount = higher performance but fewer crits? Because i've noticed that I don't crit that much with any weapon that isn't melee
> > 
> > 
> > That's what i wanted to know. How can we be sure that scanning 15 ticks is enough? Because i am pretty sure that it reduces the amount of crits. Some other crithack sources search 4096 ticks so i wanted to know where the number 15 came from.
> 
> it literally works on any value how can u not understand what im saying

are you compiling directly from source, without actually [_Enable Enhanced Instruction Set with your best instruction set??_](https://github.com/tf2cheater2013/Fedoraware#guide)

**Comment by frel0** [comment]
> > > > is this like, lower amount = higher performance but fewer crits? Because i've noticed that I don't crit that much with any weapon that isn't melee
> > > 
> > > 
> > > That's what i wanted to know. How can we be sure that scanning 15 ticks is enough? Because i am pretty sure that it reduces the amount of crits. Some other crithack sources search 4096 ticks so i wanted to know where the number 15 came from.
> > 
> > 
> > it literally works on any value how can u not understand what im saying
> 
> are you compiling directly from source, without actually [_Enabling Enhanced Instruction Set with your best instruction set for your CPU??_](https://github.com/tf2cheater2013/Fedoraware#guide)

i hope you know this exists 
![image](https://user-images.githubusercontent.com/90924169/169379176-73f8cbff-49e6-4f38-ba12-a113a1a73afd.png)

**Comment by xDroflLOL** [comment]
> > > > > is this like, lower amount = higher performance but fewer crits? Because i've noticed that I don't crit that much with any weapon that isn't melee
> > > > 
> > > > 
> > > > That's what i wanted to know. How can we be sure that scanning 15 ticks is enough? Because i am pretty sure that it reduces the amount of crits. Some other crithack sources search 4096 ticks so i wanted to know where the number 15 came from.
> > > 
> > > 
> > > it literally works on any value how can u not understand what im saying
> > 
> > 
> > are you compiling directly from source, without actually [_Enabling Enhanced Instruction Set with your best instruction set for your CPU??_](https://github.com/tf2cheater2013/Fedoraware#guide)
> 
> i hope you know this exists ![image](https://user-images.githubusercontent.com/90924169/169379176-73f8cbff-49e6-4f38-ba12-a113a1a73afd.png)

i'm using [FedoraLoader](https://github.com/lnx00/Fedoraloader/releases/) dip

**Comment by xxmyn** [comment]
incredibly stupid issue.
