### ISSUE TITLE
Exit Teleporter Arrows

### ISSUE THREAD

**Issue by SylveonBottle** [tf2cheater2013/Fedoraware#294]
Draw an arrow over teleporters that show which way they're facing (which way enemies will face when exiting the teleporter).

![image](https://user-images.githubusercontent.com/17802843/169353926-dd9366c9-c1de-449e-ac4c-1663ec22470d.png)

Idk man doesn't have to be complicated. Literally just a 1m line that points from the center would be good enough. Another ch I used had this and I've been depressed ever since, it used to be such a really neat feature.

Really good for knowing if your team has a noob portal that will send you into a wall, or so you can hide behind an enemy exit teleporter to farm backstabs. It was just really fun to have in general, just a little bit of knowledge to help give you the edge whenever you happened to find an exit teleporter.

**Comment by frel0** [comment]
nah i think it will just waste our times, you know you should learn how to code and make it urself.

**Comment by SylveonBottle** [comment]
> nah i think it will just waste our times, you know you should learn how to code and make it urself.

Yeah man I should take 1-3 hours a day for 3 months to learn C++ just so I can draw a single line. talk about wasting time

**Comment by frel0** [comment]
> > nah i think it will just waste our times, you know you should learn how to code and make it urself.
> 
> Yeah man I should take 1-3 hours a day for 3 months to learn C++ just so I can draw a single line. talk about wasting time

sperging

**Comment by resiki8182** [comment]
Is this like you want?
![image](https://user-images.githubusercontent.com/35955241/169387494-450370de-3724-4f47-904f-ceac18670d6d.png)

**Comment by GabrielNiccolabruh** [comment]
just add this is good for farming backstabs

**Comment by SylveonBottle** [comment]
> Is this like you want?
basically. If it's possible maybe a color picker? Just to make it a little more noticable

**Comment by resiki8182** [comment]
> > Is this like you want?
> 
> basically. If it's possible maybe a color picker? Just to make it a little more noticable

Ok. sorry for late reply I was gone. I'll create a pull request
