### ISSUE TITLE
Fresnel chams not overlaying correctly or not working 4 me

### ISSUE THREAD

**Issue by hotodog** [tf2cheater2013/Fedoraware#305]
(newest fedoraware version from actions tab) [chams not working correctly]
![image](https://user-images.githubusercontent.com/91759684/168447233-7fd5fbe9-06f8-40f2-8a7b-9a05de0fa3b4.png)

(older fedoraware version from actions tab I think around from 02/09/22) [chams working correctly]
![image](https://user-images.githubusercontent.com/91759684/168448445-c90291e6-6b91-41b0-a4b4-2175581017a0.png)

I am using the same settings in both screenshare

I have used different configs multiple times and I can recreate the issue 

↓ (both versions used in the screenshots) ↓

[old.zip](https://github.com/tf2cheater2013/Fedoraware/files/8693889/old.zip)
[Fedoraware (27).zip](https://github.com/tf2cheater2013/Fedoraware/files/8745739/Fedoraware.27.zip)

↓ host_writeconfig output ↓

cfgver "1"
unbindall
bind "0" "slot10"
bind "1" "slot1"
bind "2" "slot2"
bind "3" "slot3"
bind "4" "slot4"
bind "5" "slot5"
bind "6" "slot6"
bind "7" "slot7"
bind "8" "slot8"
bind "9" "slot9"
bind "a" "+moveleft"
bind "b" "+voicerecord"
bind "c" "voice_menu_3"
bind "d" "+moveright"
bind "g" "+taunt"
bind "h" "+use_action_slot_item"
bind "i" "showmapinfo"
bind "j" "cl_trigger_first_notification"
bind "k" "cl_decline_first_notification"
bind "l" "dropitem"
bind "m" "open_charinfo_direct"
bind "n" "open_charinfo_backpack"
bind "p" "say_party"
bind "r" "+reload"
bind "s" "+back"
bind "t" "say"
bind "u" "messagemode2"
bind "w" "+forward"
bind "x" "voice_menu_2"
bind "y" "say_team"
bind "z" "voice_menu_1"
bind "`" "toggleconsole"
bind "," "changeclass"
bind "." "changeteam"
bind "/" "+inspect"
bind "-" "explode"
bind "=" "kill"
bind "SPACE" "+jump"
bind "TAB" "+showscores"
bind "ESCAPE" "cancelselect"
bind "INS" "+klook"
bind "END" "centerview"
bind "PAUSE" "pause"
bind "ALT" "+strafe"
bind "CTRL" "+duck"
bind "UPARROW" "+forward"
bind "LEFTARROW" "+left"
bind "DOWNARROW" "+back"
bind "RIGHTARROW" "+right"
bind "F3" "show_matchmaking"
bind "F6" "save_replay"
bind "F7" "abuse_report_queue"
bind "F9" "vr_toggle"
bind "F10" "quit prompt"
bind "F11" "vr_reset_home_pos"
bind "MOUSE1" "+attack"
bind "MOUSE2" "+attack2"
bind "MOUSE3" "+attack3"
replay_editor_camera_length "15"
youtube_http_proxy ""
replay_movie_reveal_warning "0"
replay_movie_export_last_dir ""
replay_renderqueue_first_add "1"
replay_rendersetting_exportraw "0"
replay_rendersetting_renderglow "0"
replay_quitmsg_dontaskagain "1"
replay_editor_fov_mousewheel_multiplier "5"
replay_editor_fov_mousewheel_invert "0"
replay_replayeditor_rewindmsgcounter "1"
replay_enablerenderpreview "1"
youtube_username ""
cl_flipviewmodels "0"
cl_rumblescale "1.0"
cl_debugrumble "0"
cl_thirdperson "0"
cl_interp_ratio "2"
cl_interp ".03"
cl_team "default"
cl_class "default"
vr_activate_default "0"
vr_moveaim_mode "3"
vr_moveaim_mode_zoom "3"
vr_moveaim_reticle_yaw_limit "10"
vr_moveaim_reticle_pitch_limit "30"
vr_moveaim_reticle_yaw_limit_zoom "0"
vr_moveaim_reticle_pitch_limit_zoom "-1"
vr_hud_max_fov "60"
vr_hud_forward "500"
vr_hud_display_ratio "0.95"
vr_hud_axis_lock_to_world "0"
vr_zoom_multiplier "2.0"
vr_force_windowed "0"
hud_takesshots "0"
hud_freezecamhide "0"
r_drawtracers_firstperson "1"
glow_outline_effect_enable "1"
cl_showhelp "0"
hud_draw_fixed_reticle "0"
hud_achievement_description "0"
hud_achievement_count "0"
cl_chatfilters "63"
cl_chatfilter_version "1"
cl_mute_all_comms "1"
cl_enable_text_chat "1"
cc_linger_time "1.0"
cc_predisplay_time "0.25"
cc_subtitles "0"
cc_lang ""
crosshair "1"
cl_observercrosshair "1"
cl_hudhint_sound "0"
g15_update_msec "250"
cam_snapto "0"
cam_ideallag "4.0"
cam_idealdelta "4.0"
cam_idealyaw "0"
cam_idealpitch "0"
cam_idealdist "150"
cam_idealdistright "0"
cam_idealdistup "0"
cam_collision "1"
c_maxpitch "90"
c_minpitch "0"
c_maxyaw "135"
c_minyaw "-135"
c_maxdistance "200"
c_mindistance "30"
c_orthowidth "100"
c_orthoheight "100"
joy_name "joystick"
joy_advanced "1"
joy_advaxisx "4"
joy_advaxisy "2"
joy_advaxisz "0"
joy_advaxisr "1"
joy_advaxisu "3"
joy_advaxisv "0"
joy_forwardthreshold "0.15"
joy_sidethreshold "0.15"
joy_pitchthreshold "0.15"
joy_yawthreshold "0.15"
joy_forwardsensitivity "-1"
joy_sidesensitivity "1"
joy_pitchsensitivity "1"
joy_yawsensitivity "-1"
joy_response_move "1"
joy_response_look "0"
joy_lowend "1"
joy_lowmap "1"
joy_accelscale "0.6"
joy_accelmax "1.0"
joy_autoaimdampenrange "0"
joy_autoaimdampen "0"
joy_diagonalpov "0"
joy_display_input "0"
joy_wingmanwarrior_turnhack "0"
joy_inverty "0"
joy_movement_stick "0"
joy_xcontroller_cfg_loaded "0"
lookspring "0"
lookstrafe "0"
joystick "0"
m_pitch "0.022"
m_filter "0"
sensitivity "3"
m_side "0.8"
m_yaw "0.022"
m_forward "1"
m_customaccel "0"
m_customaccel_scale "0.04"
m_customaccel_max "0"
m_customaccel_exponent "1"
m_mousespeed "0"
m_mouseaccel1 "0"
m_mouseaccel2 "0"
m_rawinput "1"
cl_mouselook "1"
sc_yaw_sensitivity "1.0"
sc_pitch_sensitivity "0.75"
cl_idealpitchscale "0.8"
net_scale "5"
net_graphpos "1"
net_graphsolid "0"
net_graphtext "1"
net_graphmsecs "400"
net_graphshowlatency "1"
net_graphshowinterp "1"
net_graphheight "64"
net_graphproportionalfont "1"
zoom_sensitivity_ratio "1.0"
viewmodel_fov "70"
mat_viewportscale "1"
mat_viewportupscale "1"
cl_software_cursor "0"
mat_software_aa_strength "0"
mat_software_aa_quality "0"
mat_software_aa_edge_threshold "1.0"
mat_software_aa_blur_one_pixel_lines "0.5"
mat_software_aa_tap_offset "1.0"
mat_software_aa_strength_vgui "0"
pyro_vignette "2"
pyro_vignette_distortion "1"
pyro_min_intensity "0.1"
pyro_max_intensity "0.35"
pyro_min_rate "0.05"
pyro_max_rate "0.2"
pyro_min_side_length "0.3"
pyro_max_side_length "0.55"
pyro_min_side_width "0.65"
pyro_max_side_width "0.95"
pyro_dof "1"
voice_modenable "1"
hud_fastswitch "1"
store_version "1"
tf_trade_up_use_count "3"
cl_showbackpackrarities "0"
cl_show_market_data_on_items "1"
tf_explanations_backpackpanel "1"
tf_backpack_page_button_delay ".25"
cl_notifications_show_ingame "1"
cl_notifications_max_num_visible "3"
cl_notifications_move_time "0"
tf_time_loading_item_panels ".0005"
tf_store_stamp_donation_add_timestamp "0"
cl_trading_show_requests_from "3"
hud_classautokill "0"
overview_health "1"
overview_names "1"
overview_tracks "1"
overview_locked "1"
overview_alpha "1.0"
spec_scoreboard "0"
cl_spec_mode "6"
cl_disablehtmlmotd "1"
ifm_steadycam_rotaterate "60"
ifm_steadycam_zoomspeed "1.0"
ifm_steadycam_zoomdamp "0.95"
ifm_steadycam_armspeed "0.5"
ifm_steadycam_rotatedamp "0.95"
ifm_steadycam_mousefactor "1.0"
ifm_steadycam_mousepower "1.0"
ifm_steadycam_2dspringconstant "33.0"
ifm_steadycam_2ddragconstant "11.0"
ifm_steadycam_noise "0.0"
ifm_steadycam_sensitivity "1.0"
sixense_weapon_select_sensitivity "1.65"
sixense_crouch_sensitivity "1.5"
sixense_jump_sensitivity "1.2"
sixense_reload_sensitivity "1.5"
sixense_left_handed "0"
sixense_sensitivity_level "2"
sixense_controller_angle_mode "0.0f"
sixense_roll_correct_blend "0.965f"
sixense_exit_one_to_one_dot "0.85"
sixense_exit_metroid_blend "0.95f"
sixense_max_charge_spin "3.0f"
sixense_zoom_momentary_time "500"
sixense_base_offset_x "0.0"
sixense_base_offset_y "0.0"
sixense_base_offset_z "-20.0"
sixense_trigger_threshold "0.05"
sixense_tilt_gesture_angle_threshold "35.0"
sixense_point_gesture_angle_threshold "15.0"
sixense_mouse_enabled "1.0"
sixense_mouse_sensitivity "1.0"
sixense_spring_view_enabled "1.0f"
sixense_spring_view_min_spring "0.025f"
sixense_spring_view_max_spring "0.9999f"
sixense_spring_view_min_angle "1.0f"
sixense_spring_view_max_angle "45.0f"
sixense_aim_freeaim_heading_multiplier "1.750000"
sixense_aim_freeaim_pitch_multiplier "1.750000"
sixense_aim_freeaim_dead_zone_radius "0.000000"
sixense_aim_freeaim_accel_band_size "15"
sixense_aim_freeaim_max_speed "12.000000"
sixense_aim_freeaim_auto_level_rate "1.0"
sixense_aim_freeaim_accel_band_exponent "1.0"
sixense_aim_freeaim_switch_blend_time_exit "0.25"
sixense_aim_1to1_ratchet_vertical "1.0"
sixense_aim_1to1_heading_multiplier "3.0"
sixense_aim_1to1_pitch_multiplier "3.000000"
sixense_feet_angles_offset_stick_spin_horiz_multiplier "7.500000"
sixense_feet_angles_offset_stick_spin_vert_multiplier "4.500000"
sixense_feet_angles_offset_stick_spin_invert_pitch "1.0"
sixense_feet_angles_offset_stick_spin_exponent "1.0"
sixense_aim_scope_heading_multiplier "0.6"
sixense_aim_scope_pitch_multiplier "0.6"
sixense_melee_pitch_blend_val "0.99"
sixense_crosshair_horiz_multiplier "1.0"
sixense_crosshair_vert_multiplier "1.0"
sixense_always_draw_crosshair "1"
sixense_walking_dead_zone_percent "10.0"
sixense_walking_exponent "1.0"
sixense_enabled "0"
sixense_filter_level "0.5"
sixense_mode "0"
cl_spraydisable "1"
muzzleflash_light "0"
tf_chargedfriends ""
cl_autorezoom "0"
tf_remember_activeweapon "0"
tf_remember_lastswitched "0"
cl_autoreload "1"
tf_respawn_on_loadoutchanges "0"
sb_dontshow_maxplayer_warning "1"
sb_close_browser_on_connect "1"
tf_spectate_pyrovision "0"
tf_replay_pyrovision "0"
tf_romevision_opt_in "0"
tf_romevision_skip_prompt "1"
tf_medieval_thirdperson "0"
tf_inspect_hint_count "11"
fov_desired "90"
tf_highfive_hintcount "4"
tf_delete_temp_files "1"
cl_steamscreenshots "1"
cl_hud_minmode "1"
viewmodel_fov_demo "54"
tf_hud_no_crosshair_on_scope_zoom "1"
cl_ask_favorite_opt_out "1"
cl_ask_blacklist_opt_out "1"
tf_halloween_bonus_ducks_cooldown "20"
tf_coach_request_nevershowagain "1"
tf_warpaint_explanation_viewed "1"
ds_enable "0"
ds_dir "demos"
ds_prefix ""
ds_min_streak "2"
ds_kill_delay "600"
ds_log "1"
ds_sound "1"
ds_notify "0"
ds_screens "0"
ds_autodelete "0"
tf_particles_disable_weather "0"
hud_combattext "1"
hud_combattext_healing "1"
hud_combattext_batching "1"
hud_combattext_batching_window "0.2"
hud_combattext_doesnt_block_overhead_text "1"
hud_combattext_red "255.000000"
hud_combattext_green "255.000000"
hud_combattext_blue "255.000000"
tf_dingalingaling "1"
tf_dingaling_volume "0.750000"
tf_dingaling_pitchmindmg "100.000000"
tf_dingaling_pitchmaxdmg "100.000000"
tf_dingalingaling_lasthit "1"
tf_dingaling_lasthit_volume "0.750000"
tf_dingaling_lasthit_pitchmindmg "100.000000"
tf_dingaling_lasthit_pitchmaxdmg "100.000000"
tf_dingalingaling_repeat_delay ".007"
tf_dingalingaling_effect "3"
tf_dingalingaling_last_effect "0"
hud_achievement_count_engineer "0"
tf_hud_num_building_alert_beeps "2"
cl_crosshair_red "255.000000"
cl_crosshair_green "255.000000"
cl_crosshair_blue "255.000000"
cl_crosshair_file ""
cl_crosshair_scale "32.0"
cl_hud_killstreak_display_time "2"
cl_hud_killstreak_display_fontsize "0"
cl_hud_killstreak_display_alpha "120"
tf_contract_progress_show "1"
tf_contract_competitive_show "2"
tf_recent_achievements "0"
tf_find_a_match_hint_viewed "1"
tf_training_has_prompted_for_training "1"
tf_training_has_prompted_for_offline_practice "1"
tf_training_has_prompted_for_forums "1"
tf_training_has_prompted_for_options "1"
tf_training_has_prompted_for_loadout "1"
cl_ask_bigpicture_controller_opt_out "1"
cl_mainmenu_operation_motd_start "2022-05-11 18:52:41"
cl_mainmenu_operation_motd_reset "0"
cl_mainmenu_updateglow "0"
tf_mainmenu_match_panel_type "7"
cl_promotional_codes_button_show "0"
tf_last_store_pricesheet_version "60966"
cl_mvm_wave_status_visible_during_wave "1"
tf_use_match_hud "1"
tf_build_menu_controller_mode "0"
tf_simple_disguise_menu "0"
tf_disguise_menu_controller_mode "0"
tf_hud_notification_show_count_kart_controls "1"
tf_hud_notification_show_count_ghost_controls "1"
tf_hud_notification_show_count_ghost_controls_no_respawn "1"
tf_hud_show_servertimelimit "1"
cl_hud_playerclass_use_playermodel "0"
cl_hud_playerclass_playermodel_showed_confirm_dialog "1"
tf_spec_xray_disable "0"
tf_enable_glows_after_respawn "1"
tf_spectator_target_location "0"
tf_hud_target_id_disable_floating_health "1"
tf_hud_target_id_alpha "100"
tf_hud_target_id_offset "0"
tf_hud_target_id_show_avatars "1"
tf_healthicon_height_offset "10"
tf_weapon_select_demo_start_delay "1.0"
tf_weapon_select_demo_time "0"
tf_item_inspect_model_spin_rate "30"
tf_item_inspect_model_auto_spin "1"
tf_rd_finale_beep_time "10"
tf_colorblindassist "1"
tf_halloween_kart_pitch "10"
tf_halloween_kart_pitch_slow_follow_rate "0.5"
tf_halloween_kart_pitch_fast_follow_rate "2"
tf_use_min_viewmodels "1"
tf_mm_custom_ping_enabled "0"
tf_mm_custom_ping "350"
tf_party_join_request_mode "1"
tf_party_ignore_invites "0"
tf_party_keep_on_same_team "0"
tf_mvm_tabs_discovered "1"
tf_steam_workshop_import_icon_path ""
tf_steam_workshop_import_model_path ""
tf_steam_workshop_import_material_path ""
publish_file_last_dir ""
tf_steam_workshop_page_skip "10"
tf_explanations_charinfo_armory_panel "1"
tf_explanations_charinfopanel "1"
tf_show_preset_explanation_in_class_loadout "0"
tf_show_taunt_explanation_in_class_loadout "0"
tf_explanations_craftingpanel "1"
tf_quest_notification_line_delay "1.2"
tf_testitem_recent ""
tf_show_maps_details_explanation_count "0"
replay_replaywelcomedlgcount "0"
tf_mvm_classupgradehelpcount "3"
tf_scoreboard_mouse_mode "1"
tf_scoreboard_ping_as_text "1"
tf_scoreboard_alt_class_icons "0"
tf_mm_dashboard_slide_panel_step "20"
tf_casual_welcome_hide "1"
tf_comp_welcome_hide "1"
tf_notifications_push_bottom "0"
tf_queue_spinner_color "0"
tf_dashboard_slide_time ".1"
tf_chat_popup_hold_time "10"
tf_special_event_hide "0"
tf_mm_dashboard_spew_enabled "0"
tf_matchmaking_ticket_help "1"
tf_quest_map_intro_viewed "1"
cl_spec_carrieditems "1"
cl_use_tournament_specgui "0"
cl_training_completed_with_classes "511"
tf_medigun_autoheal "1"
hud_medicautocallers "0"
hud_medicautocallersthreshold "75.000000"
hud_medichealtargetmarker "1"
tf_sniper_fullcharge_bell "0"
cl_crosshaircolor "0"
cl_dynamiccrosshair "1"
cl_scalecrosshair "1"
cl_crosshairalpha "200"
tf_explanations_discardpanel "1"
tf_explanations_store "1"
r_eyegloss "1"
commentary_firstrun "0"
vgui_message_dialog_modal "1"
scene_showfaceto "0"
ai_report_task_timings_on_limit "0"
ai_think_limit_label "0"
npc_height_adjust "1"
sv_pvsskipanimation "1"
scene_showlook "0"
scene_showmoveto "0"
scene_showunlock "0"
xbox_throttlebias "100"
xbox_throttlespoof "200"
xbox_autothrottle "1"
func_break_max_pieces "15"
suitvolume "0.25"
option_duck_method "1"
sk_autoaim_mode "1"
sv_noclipaccelerate "5"
sv_noclipspeed "5"
sv_specaccelerate "5"
sv_specspeed "3"
sv_specnoclip "1"
sv_backspeed "0.6"
sv_skyname "sky_goldrush_01"
tf_skillrating_update_interval "180"
tf_server_identity_token ""
tf_server_identity_account_id "0"
tf_server_identity_disable_quickplay "0"
replay_enableeventbasedscreenshots "0"
replay_dodiskcleanup "1"
replay_voice_during_playback "0"
replay_flushinterval "15"
windows_speaker_config "7"
snd_legacy_surround "0"
snd_pitchquality "1"
volume "0.400000"
snd_musicvolume "0.000000"
snd_mixahead ".05"
adsp_debug "0"
snd_ducktovolume "0.55"
snd_duckerattacktime "0.5"
snd_duckerreleasetime "2.5"
snd_duckerthreshold "0.15"
dsp_slow_cpu "0"
dsp_volume "1.0"
dsp_enhance_stereo "0"
snd_mute_losefocus "1"
voice_scale "1"
voice_enable "1"
voice_forcemicrecord "1"
name "зађА"
password ""
cl_clanid "0"
sv_unlockedchapters "99"
tv_nochat "0"
cl_showpluginmessages "0"
cl_timeout "30"
cl_logofile "materials/vgui/logos/d_images_community.vtf"
cl_soundfile "sound/player/jingle.wav"
cl_allowdownload "0"
cl_downloadfilter "mapsonly"
mat_colorcorrection "1"
con_enable "1"
r_eyemove "1"
r_eyeshift_x "0"
r_eyeshift_y "0"
r_eyeshift_z "0"
r_eyesize "0"
r_ambientboost "1"
r_ambientmin "0.3"
r_ambientfactor "5"
r_drawmodelstatsoverlaymin "0.1"
r_drawmodelstatsoverlaymax "1.5"
mp_decals "256"
mat_color_projection "0"
sv_logsdir "logs"
sv_logfile "1"
sv_logflush "0"
sv_logecho "1"
sv_log_onefile "0"
sv_logbans "0"
sv_logfilename_format ""
sv_logfilecompress "0"
sv_voiceenable "1"
sv_forcepreload "0"
bugreporter_uploadasync "0"
rate "131072"
cl_cmdrate "66"
cl_updaterate "66"
closecaption "0"
skill "1"
net_maxroutable "1200"
cl_allowupload "0"
engine_no_focus_sleep "0"
mat_powersavingsmode "0"
budget_bargraph_background_alpha "128"
budget_peaks_window "30"
budget_averages_window "30"
budget_show_peaks "1"
budget_show_averages "0"
budget_show_history "1"
budget_history_numsamplesvisible "100"
budget_history_range_ms "66.666666667"
budget_panel_bottom_of_history_fraction ".25"
budget_bargraph_range_ms "16.6666666667"
budget_background_alpha "128"
budget_panel_x "0"
budget_panel_y "50"
budget_panel_width "512"
budget_panel_height "384"
texture_budget_panel_x "0"
texture_budget_panel_y "450"
texture_budget_panel_width "512"
texture_budget_panel_height "284"
texture_budget_panel_bottom_of_history_fraction ".25"
texture_budget_background_alpha "128"
vprof_graphwidth "512"
vprof_graphheight "256"
vprof_verbose "1"
vprof_unaccounted_limit "0.3"
vprof_warningmsec "10"
video_quicktime_encode_gamma "3"
video_quicktime_decode_gamma "0"
r_rootlod "0"
mat_forceaniso "8"
mat_picmip "-1"
mat_monitorgamma "2.2"
mat_monitorgamma_tv_enabled "0"
mat_antialias "8"
mat_aaquality "0"
r_shadowrendertotexture "1"
r_waterforceexpensive "1"
mat_motion_blur_enabled "0"
mat_queue_mode "2"
mat_queue_report "0"
mat_managedtextures "0"
mat_spewalloc "0"
mat_texture_list_content_path ""
joy_axisbutton_threshold "0.3"
joy_axis_deadzone "0.2"
joy_gamecontroller_config ""
sc_joystick_map "1"
sc_disable "0"
mat_hdr_level "100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"

(send help)

**Comment by xxmyn** [comment]
make sure bloom is enabled

**Comment by hotodog** [comment]
> 

it is I am using the same settings in both screenshots

**Comment by Eniac763** [comment]
I was having the same trouble too, but enabling bloom worked for me.

PS: I am not using the latest version of Fedoraware though

**Comment by xxmyn** [comment]
Idk what to say, this is clearly a lighting issue 🤷

**Comment by hotodog** [comment]
> Idk what to say, this is clearly a lighting issue 🤷

then what do i change or sum shit (ive tried using stock and resetting my game a million times and different visual configs or no cfg at all)
