### ISSUE TITLE
Idea: MAYBE add fake latency using net_fakelag

### ISSUE THREAD

**Issue by xDroflLOL** [tf2cheater2013/Fedoraware#307]
Fake latency is different from fake lag (which makes the server thinks you are lagging; as in dropping in frames, but you're not), where you tell the server that you have net_fakelag set to, let's say, 270, and thus the server would delay the information to you, by 270 * 2 (yes it's in increments of 2), so it's 540ms of delay, aka more than half of second of delay.

**Comment by johnathon-walnut** [comment]
no.

**Comment by xDroflLOL** [comment]
hm yes you should totally close this because "no one knows how it works, and no one bothers to care"

when other cheats already gotten this feature..

**Comment by johnathon-walnut** [comment]
you cant fake latency with net_fakelag

**Comment by xDroflLOL** [comment]
> you cant fake latency with net_fakelag

nope, i tried it out on a local server, and it said that my ping was ~530
![image](https://user-images.githubusercontent.com/87008513/169710552-5bf319c3-5486-41df-94bc-2d6a383deaae.png)

**Comment by johnathon-walnut** [comment]
👍 you are still wrong

**Comment by gayblackirony** [comment]
hahahahhahahahahahahahahaha

**Comment by xDroflLOL** [comment]
> 👍 you are still wrong

yeah dude totally...

...when someone could code to fake net_fakelag to be 270 (or whatever)

**Comment by johnathon-walnut** [comment]
this isnt fake latency

**Comment by xDroflLOL** [comment]
> this isnt fake latency

at least from what i tested (playing in a match, testing it on a local host server), it is

**Comment by johnathon-walnut** [comment]
its not

**Comment by xDroflLOL** [comment]
> its not

explain how it is it, then

**Comment by johnathon-walnut** [comment]
Lag all incoming network data (including loopback) by this many milliseconds.

keyword: all

**Comment by xDroflLOL** [comment]
it DELAYS the incoming network data, NOT lags it

**Comment by johnathon-walnut** [comment]
that is literally the convar description.

**Comment by femboy-boop** [comment]
All it does it lags your packets aka delaying it. On your side. Not server side and yea server says you have that because u fake it on your side b1gger next time do a proper issue.

**Comment by GabrielNiccolabruh** [comment]
just add this it will be good to play spy

**Comment by femboy-boop** [comment]
I JUST EXPLAINED IT WONT WORK NIGGERS

**Comment by xDroflLOL** [comment]
> I JUST EXPLAINED IT WONT WORK NIGGERS

mad.....

**Comment by femboy-boop** [comment]
Who are you NN learn the game first than talk nigger

**Comment by xDroflLOL** [comment]
> Who are you NN learn the game first than talk nigger

mad.........

**Comment by femboy-boop** [comment]
No co features?

**Comment by johnathon-walnut** [comment]
racism..,.,.,..,.,.,.

**Comment by femboy-boop** [comment]
Shut up niegger -dababy
