### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by HARrhhv2** [tf2cheater2013/Fedoraware#308]
addkey binds like this? 
![image](https://user-images.githubusercontent.com/105882762/169717371-32735af5-5c28-4ef3-8740-09b6bd32f256.png)

**Comment by FART900000000** [comment]
no

**Comment by femboy-boop** [comment]
I could do that but fuck you

**Comment by FART900000000** [comment]
14 can you add it pls

**Comment by johnathon-walnut** [comment]
> I could do that but fuck you

Do it :D

**Comment by femboy-boop** [comment]
Fart (farted) retarded (tarded), ok but it's gonna be limited cuz fuck u :3

**Comment by HARrhhv2** [comment]
> I could do that but fuck you

🥺🥺🥺🥺🙏🙏🙏🙏🙏🙏 and those fresnel glow chams in your videos 🥺

**Comment by lnx00** [comment]
Might consider it

**Comment by lnx00** [comment]
I'm adding it. Which features do you which to indicate?

**Comment by johnathon-walnut** [comment]
anything with a keybind

**Comment by lnx00** [comment]
![Preview](https://i.imgur.com/s3YxaUp.png)

**Comment by lnx00** [comment]
Added in #347
