### ISSUE TITLE
Improve Auto backstab

### ISSUE THREAD

**Issue by GabrielNiccolabruh** [tf2cheater2013/Fedoraware#310]
improve auto backstab it in 1.0 attacks in parts that don't backstab

**Comment by johnathon-walnut** [comment]
consider not using 1.0

**Comment by xxmyn** [comment]
this issue makes no sense lol

**Comment by GabrielNiccolabruh** [comment]
and make the cheat support dxlevel 81

**Comment by lnx00** [comment]
Simply don't use dxlevel <90

**Comment by GabrielNiccolabruh** [comment]
is that dxlevel 81 gives more fps

**Comment by lnx00** [comment]
Then you have to decide whether you want to use Fedoraware or have more fps

**Comment by xxmyn** [comment]
the cheat supports dxlevel 81, in all the testing I have done with dxlevel 81, it has worked perfectly (i do not use dxlevel 81.)

**Comment by FART900000000** [comment]
shut up

**Comment by GabrielNiccolabruh** [comment]
when i use fedoraware with dxlevel 81 after few minutes it crashes

**Comment by GabrielNiccolabruh** [comment]
worst decision
