### ISSUE TITLE
pSuspect->IsTaunting() check in cheater detector doesn't sound too good since players can still charge ticks while taunting

### ISSUE THREAD

**Issue by XJN2** [tf2cheater2013/Fedoraware#312]
title

**Comment by xxmyn** [comment]
players can also charge ticks while dead or dormant and not get detected, players can charge ticks slowly and not get detected, and release said ticks slowly as well, the cheater detection can be bypasses pretty easily rn, the taunt check is for anti aim detections im gonna add later.
