### ISSUE TITLE
backtracking projectiles is NOT possible you need to disable backtracking for projectile weapons or it misses becuase projectiles are built differently

### ISSUE THREAD

**Issue by HutchyBean** [tf2cheater2013/Fedoraware#316]

**Comment by gayblackirony** [comment]
why

**Comment by johnathon-walnut** [comment]
it doesnt actually affect the projectiles... it just gets drawn regardless

**Comment by HutchyBean** [comment]
i dunno i tested it and like it was missing 100% when backtracking was on huntsman

**Comment by HutchyBean** [comment]
upon further testing it is deffentely fucking projectiles up !!!

**Comment by SylveonBottle** [comment]
> 

Tested different backtracking/projectile aimbot settings in tr_walkway and was unable to reproduce the issue.

Could you show a video?

**Comment by xxmyn** [comment]
even with fake latency I can't reproduce this, since you have had like a day and haven't clipped this im gonna close the issue :D
