### ISSUE TITLE
It has been crash lots recently latest commit

### ISSUE THREAD

**Issue by HutchyBean** [tf2cheater2013/Fedoraware#317]
I have notice crash when hvh as soldier. i could not figure out what is. probablyt splash or osmehitng. also  when i swithc weapon it sometime crashes as well. also when game crash as soldier visual studio no give debug attach debug error so i was baffled and dont know what cause error so can not provide helpful report

**Comment by SylveonBottle** [comment]
May be related to using Crithack on non-crit weapons.
Disable crithack and see if you stop crashing.
https://github.com/tf2cheater2013/Fedoraware/commit/fa90f6885f36ab25c5681d7890ee886170a56b28#commitcomment-74629835

**Comment by xxmyn** [comment]
the simple fix is to not scan on weapons that cant crit, as i have said countless times the loop ends when it finds a cmdnumber you can crit on, and will rarely loop more than 20 times anyway.

**Comment by xxmyn** [comment]
I've reduced the amount of loops in the most recent commit, please close this issue if you're no longer experiencing the issue (after re-reading i'm not even sure if you crashed because of the crithack)
