### ISSUE TITLE
Feet aim on ground" ignores projectile aim method / Replace with seperate air & ground hitbox selectors

### ISSUE THREAD

**Issue by SylveonBottle** [tf2cheater2013/Fedoraware#319]
1. `Projectile aim method` set to `Body`
2. `Feet aim on ground` enabled

What I expect to happen:
If the target is on the ground, the proj aimbot should aim at the feet.
If the target is not on the ground, the proj aimbot should aim at the body.

What actually happens:
When the target is on the ground, proj aim fires at the body. 
It never fires at the feet.

Suggestion:
Rename "Aim Method" to "Air Hitbox"
Replace "Feet aim on ground" with "Ground Hitbox", add options for feet/body/head/auto.

This way, the user can set Air Hitbox to aim at feet to juggle enemies in the air, or set Ground Hitbox to body to aim at the body.
Or reverse, Ground Hitbox can be set to feet in order to launch enemies up, but Air Hitbox can be set to body to maximize likelihood of hitting an airshot without suspiciously always hitting the feet.

Shitty example:
![image](https://user-images.githubusercontent.com/17802843/170612391-f3fb618d-9d7a-47db-b1a8-666d501d46c1.png)

**Comment by xxmyn** [comment]
Slight mistake where it only aims at feet if the hitbox is set to auto, I'll fix eventually...

**Comment by xxmyn** [comment]
I fixed the issue, not really sure about the air / ground hitboxes tbh.
