### ISSUE TITLE
Projectile Aimbot's "Prediction Time" should be ignored on buildings

### ISSUE THREAD

**Issue by SylveonBottle** [tf2cheater2013/Fedoraware#320]
Setting "prediction time" to 1 second makes aimbot unable to shoot at buildings that are more than 1 second away

they can't move.. so uh.. projectile aimbot should ignore prediction time when targeting unmovable objects

**Comment by xxmyn** [comment]
movement simulation isnt used on buildings and iirc max pred time isnt taken into account for them

**Comment by SylveonBottle** [comment]
> movement simulation isnt used on buildings and iirc max pred time isnt taken into account for them

re-open dummy
I wouldn't have made the issue if I didn't test it in the first place

**Comment by SylveonBottle** [comment]
https://user-images.githubusercontent.com/17802843/170620013-5647798a-78ea-4ef0-b372-5e188ce0c5b2.mp4

**Comment by femboy-boop** [comment]
Baan moment....
