### ISSUE TITLE
"Multipoint" for projectile aimbot / rework pls

### ISSUE THREAD

**Issue by SylveonBottle** [tf2cheater2013/Fedoraware#321]
https://youtu.be/aw5R6MpOtOs?t=15

Checking the 8 corners of the hitbox seems like a good idea.
![image](https://user-images.githubusercontent.com/17802843/170618278-f9fed3a4-1e21-4934-87f2-0c60639a4ba3.png)

Currently projectile aimbot seems _really_ dumb right now.
I have "aim method" set to head in this clip:

https://user-images.githubusercontent.com/17802843/170619030-dadb20de-02c9-4af5-b999-e12f0ca7595f.mp4

It randomly aims at at the feet (despite 'feet aim on ground' and 'splash prediction' not being enabled) lmao

**Comment by femboy-boop** [comment]
Proj aim needs a rework... Baan is a smart paster and fucked it up a bit

**Comment by xDroflLOL** [comment]
> Proj aim needs a rework... Baan is a smart paster and fucked it up a bit

"smart" in very MASSIVE quotes

**Comment by xxmyn** [comment]
it wasn't pasted it's just bad code.

**Comment by xxmyn** [comment]
> "smart" in very MASSIVE quotes

Not sure why I didn't ban you from this repo after you sperged out about net_fakelag but thanks for reminding me to do it :D

**Comment by xxmyn** [comment]
this should be fixed. (i really hope it is)
