### ISSUE TITLE
Skial

### ISSUE THREAD

**Issue by GabrielNiccolabruh** [tf2cheater2013/Fedoraware#323]
I get banned when I enter the skial serve

**Comment by frel0** [comment]
https://github.com/relaxtakenotes/xenos/releases/download/1.1.2/injectorstuff.7z

**Comment by GabrielNiccolabruh** [comment]
if i use this injector i am not banned?

**Comment by macedoniaN1337** [comment]
> if i use this injector i am not banned?

no, the reason why you are getting banned is, because of skial's anti-cheat system, they detect quickly if you use a high fov aimbot, fakelag, antiaim (or spinbot as new cheaters call it), bhop etc

@frel0 also linking jp4's edited xenos injector won't do much against skial's smac lol

**Comment by lnx00** [comment]
Skial is most likely detecting the changed cvars (fog for example). I'm too lazy to fix it tho

**Comment by AXDWT** [comment]
i mean skial has good anti cheat u cant just bypass it 
but valve anti cheat u can bypass it SO EASY u need vac bypass
if you got vac banned then u can use 1 fps to bypass it

**Comment by SylveonBottle** [comment]
Anything that affects server-side can be detected by skial's anticheat. Even lmaobox's norecoil will get you banned. 
Your best bet is to literally disable everything and only use esp. But eve then, skial will ban you for looking at enemies through walls or pre-firing only when there's an enemy. 
Literally use chams and nothing else. Even a low fov of 3 can be detected in demo's and get you banned if somebody reports you.

There's not really a good way to bypass skial's anticheat unless we go through the entire cheat and block a bunch of features / reset a bunch of cvars, and I don't think anyone is willing to put that much effort to cheat in a single community server.

Disable everything, only use chams, and hope that fedoraware doesn't change any cvars upon injection and _maybe_ you won't get immediately banned.

**Comment by johnathon-walnut** [comment]
stop cheating on community servers

**Comment by johnathon-walnut** [comment]
Should be fixed
