### ISSUE TITLE
Splash prediction shoots walls.

### ISSUE THREAD

**Issue by xxmyn** [tf2cheater2013/Fedoraware#326]
https://youtu.be/ghDO4nmGc-w

with or without flip viewmodel (which doesn't seem to work most of the time), the splash prediction will continually make me shoot walls.

**Comment by xxmyn** [comment]
@lnx00 👿

**Comment by lnx00** [comment]
I wish there was a method to properly check if a rocket can hit a given position without hitting walls...

**Comment by xxmyn** [comment]
there is I did it perfectly its perfect it checks for offsets it (probably) correctly checks the hull size of a rocket it even checks to make sure the offset isnt from your current angle and is calculated from the angle you will shoot at, it is objectively genius.

**Comment by lnx00** [comment]
> there is I did it perfectly its perfect it checks for offsets it (probably) correctly checks the hull size of a rocket it even checks to make sure the offset isnt from your current angle and is calculated from the angle you will shoot at, it is objectively genius.

Where can I find this method?

**Comment by xxmyn** [comment]
bool CAimbotProjectile::WillProjectileHit(CBaseEntity* pLocal, CBaseCombatWeapon* pWeapon, CUserCmd* pCmd, Vec3 vPredictedPos, Solution_t& out, const ProjectileInfo_t& projInfo, const Predictor_t& predictor)

**Comment by SylveonBottle** [comment]
>check distance from right shoulder to crosshair location until it intercepts a wall
>check distance from left shoulder to crosshair location until it intercepts a wall
>compare the distances
>switch cl_flipviewmodel to whichever was bigger

It won't check the rocket bounding box, but I had this idea for a really shitty way of always shooting whatever would result in your rocket going closest to where you're aiming. In situations like in the video, it would always result in the left cl_flipviewmodel being chosen if it means the rocket can get past the wall that way.

If you do it like this, you can let players use viewmodel flipper without needing projectile aimbot.
