### ISSUE TITLE
Can't headshot with huntsman

### ISSUE THREAD

**Issue by FFJ11** [tf2cheater2013/Fedoraware#327]
It always aims for the body, any solutions to fix it?

**Comment by xxmyn** [comment]
are you aiming for head?

**Comment by FFJ11** [comment]
Yes

**Comment by FFJ11** [comment]
Mostly feet

**Comment by xxmyn** [comment]
it's an issue with the player not being visible, it just returns their absolute origin, which is feet.

it will be fixed.
