### ISSUE TITLE
Keeps crashing randomly even with crithack off (referring to thishttps://github.com/tf2cheater2013/Fedoraware/issues/317) 

### ISSUE THREAD

**Issue by thirdy1215** [tf2cheater2013/Fedoraware#328]
Keeps crashing even with crithack off but instead of the screen frozen and audio looping it just straights up closes tf2

Idk if it's my configs or custom files doing this but I have tried playing without injecting fedoraware and it does not crash randomly

Suck a n#gga dick.

**Comment by xxmyn** [comment]
I forgor to push
