### ISSUE TITLE
Projectile aimbot crashing

### ISSUE THREAD

**Issue by idiotwithgun** [tf2cheater2013/Fedoraware#329]
**Fedoraware Version Date:**  
https://github.com/tf2cheater2013/Fedoraware/actions/runs/2400090071

## Config used:
default
## Description:  
Game crashes when proj aimbot is used

## Steps to reproduce:  
Use projectile aimbot

Enable aimbot
Try using projectile aimbot on enemy

**Comment by xxmyn** [comment]
this is fixed in the latest build.
