### ISSUE TITLE
How Edit Fedora GUI on Visual Studio?

### ISSUE THREAD

**Issue by DuckGamePlay** [tf2cheater2013/Fedoraware#330]
How i can do this?

**Comment by lnx00** [comment]
Edit the [Features/Menu/Menu.cpp file](https://github.com/tf2cheater2013/Fedoraware/blob/main/Fedoraware/TeamFortress2/TeamFortress2/Features/Menu/Menu.cpp).

The styles are defined at the bottom inside `LoadStyle` and `Init`

**Comment by DuckGamePlay** [comment]
Ok ty
