### ISSUE TITLE
Market Garden Swing Prediction.

### ISSUE THREAD

**Issue by yujispin990** [tf2cheater2013/Fedoraware#331]
As of now the swing prediction swings way to early and sometimes doesn't swing at all missing the timing ,I have no idea if its trying to hit backtrack or just trying to predict normally ,i hope swing prediction gets some love as well,there is a youtuber who uses a different fedoraware remake that has swing prediction its a private build and judging by what i've seen its really good.

**Comment by idiotwithgun** [comment]
Aimbot in this cheat doesn't aims the backtrack
