### ISSUE TITLE
ProjAIm: "Feet" aims at head, "Head" aims at feet

### ISSUE THREAD

**Issue by SylveonBottle** [tf2cheater2013/Fedoraware#335]
https://user-images.githubusercontent.com/17802843/170852443-b462b90f-6230-4f86-bbc4-da1f8b1c9481.mp4

**Comment by xxmyn** [comment]
tests feature for like 2 hours, releases feature, tests it for 26 seconds in casual, doesn't work.

:/

**Comment by SylveonBottle** [comment]
also `head` aims for body when on ground
https://user-images.githubusercontent.com/17802843/170852563-e4cd3495-b96f-4bb6-9603-a3bcd971ac1e.mp4

**Comment by SylveonBottle** [comment]
When tested on `map itemtest`, `head` aims at the head. 
I'm starting to think `tr_walkway_r2` is breaking projaimbot.

**Comment by xxmyn** [comment]
it aims at the sky sometimes
it aims at the floor sometimes
in casual it has made my arrow disappear sometimes

I have tested on walkway and itemtest, and it always seems fine until I test in casual.

**Comment by xxmyn** [comment]
i have not tested the latest commit, but, it probably works (i fucking hope)

**Comment by xxmyn** [comment]
yep i headshot 1 soldier in casual i quit i did it not testing anymore cause i might've done the wrong thing!!!

**Comment by xxmyn** [comment]
ok 2 hours of testing in casual it actually works.
