### ISSUE TITLE
Menu

### ISSUE THREAD

**Issue by GabrielNiccolabruh** [tf2cheater2013/Fedoraware#336]
I inject and press insert but the menu does not appear

**Comment by xxmyn** [comment]
u inject avx2 bro idk what to tell u probs not my problem?

**Comment by GabrielNiccolabruh** [comment]
did you change the menu appears button?

**Comment by xxmyn** [comment]
braindead.

**Comment by Eniac763** [comment]
If your cpu does not support AVX2 instruction set, don't build using the AVX2 solution configuration, instead use release
