### ISSUE TITLE
Move the buttons 

### ISSUE THREAD

**Issue by DuckGamePlay** [tf2cheater2013/Fedoraware#337]
Is there any way to move the buttons to the sidebar, like that?
![161588254-5cf29b82-fd70-41c1-90c3-f77b29014a68](https://user-images.githubusercontent.com/86413661/170879256-e93089e4-9076-499c-ac1d-4acf9411794c.png)
(i used photoshop to do this)

**Comment by femboy-boop** [comment]
Uh yea, but I won't do it

**Comment by xxmyn** [comment]
its possible.
