### ISSUE TITLE
Health Value on Health Bar

### ISSUE THREAD

**Issue by Eniac763** [tf2cheater2013/Fedoraware#339]
Was curious if someone could add this, it looks pretty cool.

![image](https://user-images.githubusercontent.com/95100740/170888665-4d1e47ad-6bcd-409f-8852-a88b4362b58f.png)

Also the health value should move down as players hp decreases.

![image](https://user-images.githubusercontent.com/95100740/170888694-e8632a1d-7e3d-44ad-9614-f2f99bba4920.png)

**Comment by HARrhhv2** [comment]
YEP looks sooo good we need it

**Comment by HARrhhv2** [comment]
also a option to move the name and conditions to the bottom right or left

**Comment by johnathon-walnut** [comment]
i love chad alpha males dot club

**Comment by lnx00** [comment]
Added in #347
