### ISSUE TITLE
Fake latency

### ISSUE THREAD

**Issue by GabrielNiccolabruh** [tf2cheater2013/Fedoraware#340]
fake latency only works after a match on monday it goes down instead of up fix it and make auto backstab work with fake latency and aimbot too

**Comment by femboy-boop** [comment]
Omg kys

**Comment by GabrielNiccolabruh** [comment]
Do you know how to solve this?

**Comment by femboy-boop** [comment]
It's called buying a cheat.

**Comment by GabrielNiccolabruh** [comment]
it will take time for me to buy lmaobox

**Comment by GabrielNiccolabruh** [comment]
Do you have a hvh config?

**Comment by tf2cheater2013** [comment]
some people are just completely braindead.
