### ISSUE TITLE
[REQUEST] autostrafe smooting slider

### ISSUE THREAD

**Issue by HARrhhv2** [tf2cheater2013/Fedoraware#341]
![image](https://user-images.githubusercontent.com/105882762/170892480-bb41ac37-0268-4192-a122-fc59f74d4c0b.png)
controls how sharply autostrafe turns
higher = slower turn
lower = faster turn

what u guys think

**Comment by femboy-boop** [comment]
Are you retarded

**Comment by femboy-boop** [comment]
Lower is slower
Higher is faster
And it's called retrack please learn the game or features

**Comment by lnx00** [comment]
stupid feature
