### ISSUE TITLE
unable to connect if backtrack is on 

### ISSUE THREAD

**Issue by johnpablo1** [tf2cheater2013/Fedoraware#342]
**Fedoraware Version Date:**  
latest

## Description:  
if backtrack is on with latency u wont be able to connect to the casual server only haapens on casual

## Steps to reproduce the behavior:  
1. turn on backtrack
2. search for match
3. it take ages and u can stop it by turning off backtrack

## Additional context 
it only happens after 2 matches play 1 match with backtrack able to connect but second time u wont be able unles u turn it off
here screenshot
![image](https://user-images.githubusercontent.com/106420166/170909890-fd07b696-be68-43a8-8405-4710db11c169.png)

**Comment by johnathon-walnut** [comment]
https://en.m.wikipedia.org/wiki/Apophenia
