### ISSUE TITLE
backstab issue

### ISSUE THREAD

**Issue by johnpablo1** [tf2cheater2013/Fedoraware#343]
**Fedoraware Version Date:**  
latest

## Description:  
this video is self explanatory

https://user-images.githubusercontent.com/106420166/170971053-d0245513-b465-423e-8f4d-0675d8615c02.mp4

## Additional context
this was recorded with 1.01 stab range

**Comment by xxmyn** [comment]
ur fucking kidding me right.

**Comment by johnathon-walnut** [comment]
Wtf did I just watch?

**Comment by xxmyn** [comment]
it doesn't autostab at the maximum possible range probably bc the calculation for backstab checks is a bit conservative.

**Comment by xxmyn** [comment]
actually looking back at this I think the check is fine and this could be issue #197
