### ISSUE TITLE
minor lag issue

### ISSUE THREAD

**Issue by johnpablo1** [tf2cheater2013/Fedoraware#344]
**Fedoraware Version Date:**  
latest

## Config used:
https://catbox.moe is down someone link a diffrent file sharing website so i can send my config

## Description:  
fps drops when ur farthur away from a player while holding down the projectile aim button

https://user-images.githubusercontent.com/106420166/171003449-52753ed1-3ba8-4489-b11d-9a14a9e18724.mp4
## Steps to reproduce the behavior:  
1. go far away
2. hold down the aimbot button with any kind of projectile weapon
3. game lags

## Additional context 
its not a mastercomfig bug it doesnt work with guns I recorded it where all the enemies are stacked and that makes it more laggier but a single character can still lag you

**Comment by lnx00** [comment]
https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files

**Comment by lnx00** [comment]
Seems like @xxmyn broke the projectile aimbot :)

**Comment by femboy-boop** [comment]
In esp?, Wtf you mean.
And yea baan fucked update the fps with proj
First fix is: better pc
Second fix: actually fixing the proj aim

**Comment by xxmyn** [comment]
simulating players over long distances is fucking with fps??? ill get to the bottom of this!!!

/s

**Comment by tf2cheater2013** [comment]
> "Vars::Aimbot::Projectile::ScanPoints": "11",
> "Vars::Aimbot::Projectile::ScanScale": "0.5"
