### ISSUE TITLE
Cheater Detector

### ISSUE THREAD

**Issue by DuckGamePlay** [tf2cheater2013/Fedoraware#346]
How i can make cheater detector like rijin (with blue name)?
![c3038f28-5654-49ad-be33-c407a3bc9c5f](https://user-images.githubusercontent.com/86413661/171055633-b222646a-9130-471b-9c06-e82b10828bd2.jpg)

**Comment by FART900000000** [comment]
by sacrificing a fetus to the devil

**Comment by xxmyn** [comment]
pay 10 dollah to senator and he will teach u for a month.

**Comment by jailbaiting** [comment]
DIY, the github open source
