### ISSUE TITLE
The Vaccinator

### ISSUE THREAD

**Issue by mafiotuLX** [tf2cheater2013/Fedoraware#348]
i have a suggestion for the ESP
Please add a detection if the enemy is sheilded by the vaccinator
and if possible detect how many available charges the medic has
this will be so useful and thanks!

**Comment by femboy-boop** [comment]
ARE YOU BLIND

**Comment by xxmyn** [comment]
i think it alr does

**Comment by jailbaiting** [comment]
SHUT UP RETARD ITS CALLED FLAGS AND IF U TURN IT ON IN ESP U WILL UNDERSTAND WHAT THEY ARE USING

**Comment by xxmyn** [comment]
he cant reopen closed issues only mfed and i can...

**Comment by jailbaiting** [comment]
> > SHUT UP RETARD ITS CALLED FLAGS AND IF U TURN IT ON IN ESP U WILL UNDERSTAND WHAT THEY ARE USING
> 
> STFU RETARD no one cares! don't reply to a closed issue moron

okay retard at least im not bullied LOL keep begging for features that are already in the cheat u fucking moron use ur fucking eyes. do u wear pyrovision irl retard?

**Comment by xxmyn** [comment]
gonna get an email from github if we keep this up...
