### ISSUE TITLE
Points in projectile

### ISSUE THREAD

**Issue by FFJ11** [tf2cheater2013/Fedoraware#352]
It confuses me so much what do they exactly do

**Comment by xxmyn** [comment]
short: reduces the amount of work the cheat does, i'm planning on optimizing the cheat a bit more in the future as well.

long: reduces the amount of "points" the cheat is allowed to store (and subsequently) sort while doing projectile aimbot calculations, [these points](https://github.com/tf2cheater2013/Fedoraware/blob/025f0ecc0f1ef84e8c86baa5799d10d0539de5c7/Fedoraware/TeamFortress2/TeamFortress2/Features/Aimbot/AimbotProjectile/AimbotProjectile.cpp#L440) are used as possible locations for the aimbot to aim at, the cheat will sort through how many of them are visible (or however many you are limiting it to sorting) and return the closest one to your desired hitbox.
