### ISSUE TITLE
Nospread for projectiles implemented or not working?

### ISSUE THREAD

**Issue by Zachkilla** [tf2cheater2013/Fedoraware#356]
**Fedoraware Version: Latest**

Any Config will mess up - nospread not implemented for projectiles?

Hold mouse 1 for 5 - 8 seconds until your hand start shaking with the huntsman.

If you hold mouse 1 with huntsman for 5 or more seconds and let go of mouse 1 and the arrow will fly in a different direction and also it applies to multiple projectile weapons like pills and rockets?

Add nospread support for projectiles to fix the issue.

**Comment by lnx00** [comment]
Why would you ever want to charge the huntsman for more than 5 seconds? Just release and charge again...

**Comment by HutchyBean** [comment]
> Why would you ever want to charge the huntsman for more than 5 seconds? Just release and charge again...

hater......

**Comment by johnathon-walnut** [comment]
Not implemented, how does this work?

**Comment by HutchyBean** [comment]
> Not implemented, how does this work?

Doesnt cathook have it?

**Comment by lnx00** [comment]
This is the projectile nospread that cathook is using:
https://www.unknowncheats.me/forum/team-fortress-2-a/139094-projectile-nospread.html

**Comment by Zachkilla** [comment]
> Why would you ever want to charge the huntsman for more than 5 seconds? Just release and charge again...

It’s not just for huntsman but it would guarantee the shot without missing, pills and sticky’s have spread from what I was told.

**Comment by johnathon-walnut** [comment]
> > Why would you ever want to charge the huntsman for more than 5 seconds? Just release and charge again...
> 
> It’s not just for huntsman but it would guarantee the shot without missing, pills and sticky’s have spread from what I was told.

doesn't affect pills/stickies but it does affect the beggars bazooka, huntsman and syringe gun

**Comment by Zachkilla** [comment]
> > > Why would you ever want to charge the huntsman for more than 5 seconds? Just release and charge again...
> > 
> > 
> > It’s not just for huntsman but it would guarantee the shot without missing, pills and sticky’s have spread from what I was told.
> 
> doesn't affect pills/stickies but it does affect the beggars bazooka, huntsman and syringe gun

Ok, hopefully no-spread for projectile will be added.
