### ISSUE TITLE
(SUGGESTION) add sticky aim or a toggle option for trigger bot pls

### ISSUE THREAD

**Issue by hotodog** [tf2cheater2013/Fedoraware#360]
sticky bomb aimbot would be coolios

or a feature to toggle triggerbot instead of hold

**Comment by HutchyBean** [comment]
Wouldn't a low fov plain aimbot sticky aim

**Comment by HutchyBean** [comment]
Ohhhh you mean sticky as j. Sticky bomb

**Comment by HutchyBean** [comment]
l0l

**Comment by xxmyn** [comment]
how.

**Comment by hotodog** [comment]
I have no idea im just saying /shrug
