### ISSUE TITLE
Choosing pyro will crash the game

### ISSUE THREAD

**Issue by thirdy1215** [tf2cheater2013/Fedoraware#364]
How tf does one class crash my game either it's a bug from fedoraware or tf2's spaghetti source

**Comment by Lithi27** [comment]
Had the same issue with heavy before, i suggest u reinstall windows lmao...

**Comment by thirdy1215** [comment]
Eat my shiny Australium ass

**Comment by gayblackirony** [comment]
> Eat my shiny Australium ass

what
