### ISSUE TITLE
Follow bots with Sandboxie

### ISSUE THREAD

**Issue by ghost** [tf2cheater2013/Fedoraware#368]
I wanted to make Follow bots with Fedoraware. For Follow bots I use Sandboxie. The problem is that inject a cheat into Follow bots, game freezes, after a while the freeze disappears and in the end nothing is injected.

**Comment by PeterPumpkinEater69real** [comment]
followbot my ASS!

**Comment by xxmyn** [comment]
disgusting

**Comment by xxmyn** [comment]
locked because fedoraware followbots is an idea i dont want discussed here
