### ISSUE TITLE
Suggestion: Name Stealer / Changer

### ISSUE THREAD

**Issue by mafiotuLX** [tf2cheater2013/Fedoraware#369]
it would be nice to have this option in Fedoraware ( ͡° ͜ʖ ͡°)

**Comment by wizardmanperson** [comment]
There is already a name changer, but not a stealer.

**Comment by johnathon-walnut** [comment]
You can use the name command in console

**Comment by zeroxeclipse** [comment]
Yeah that will be awesome with the follow bots, damn no one will know where's the legit player

**Comment by xxmyn** [comment]
This is an open source cheat, I have no personal interest in adding more features for followbotters to use, not to mention name stealing is almost entirely useless now as you have to rejoin the server to steal a players name (2 minute vote cooldown upon joining), and the person you stole the name of can just call the vote (or anyone can call the vote using console).

Locking, if you want this as a feature, add it to your own build.
