### ISSUE TITLE
Sniper rifle style override doesn't work

### ISSUE THREAD

**Issue by wizardmanperson** [tf2cheater2013/Fedoraware#37]
**Fedoraware Version Date:** 
Latest version

## Config used:
https://files.catbox.moe/4jd8qs.fed

## Description:  
style override doesn't work on the sniper rifle

## Steps to reproduce:  
- [x] I am able to consistently reproduce this error

1. Enable style override (no sheen, no unusual effects)
2. apply 
3. nothing

## Additional context 
it doesn't work on casual or bot matches. The style override works for other weapons, even with sheens and unusual effects. But not for the sniper rifle

- [x] I have included the steps to reproduce to the best I am able to share.

**Comment by wizardmanperson** [comment]
Sheen, unusual effects dont work either

**Comment by johnathon-walnut** [comment]
Can confirm this is happening, but I frankly have zero (0) idea why. It works for every weapon except _specifically_ the sniper rifle...

**Comment by xxmyn** [comment]
I'm sorry, but what is style override supposed to do?

**Comment by johnathon-walnut** [comment]
It's supposed to enable the Australium effect, or something else on other weapons

**Comment by johnathon-walnut** [comment]
It's referring to the attribute "item style override" specifically

**Comment by johnathon-walnut** [comment]
(in the item schema)

**Comment by xxmyn** [comment]
yeh alr, seems kind of weird that it doesn't work since i cant see anything that would stop it :/

**Comment by johnathon-walnut** [comment]
Yeah I said that 24 days ago

**Comment by johnathon-walnut** [comment]
I still have no idea why this doesn't work but to be honest I don't care
