### ISSUE TITLE
How DO I install fedorware?

### ISSUE THREAD

**Issue by resiki8182** [tf2cheater2013/Fedoraware#372]
**Fedoraware Version Date:**  

## Steps to reproduce:  
- [ ] I am able to consistently reproduce this error

1. Enable X
2. Do Y
3. Notice Z

## Additional context 

- [ ] I have included the steps to reproduce to the best I am able to share.

**Comment by gayblackirony** [comment]
pretty sure there are shitton of tutorials out there

download fedoraloader (https://github.com/lnx00/Fedoraloader) and click inject

**Comment by resiki8182** [comment]
> pretty sure there are shitton of tutorials out there
> 
> download fedoraloader (https://github.com/lnx00/Fedoraloader) and click inject

thank you brother
