### ISSUE TITLE
whip teammates issue

### ISSUE THREAD

**Issue by johnpablo1** [tf2cheater2013/Fedoraware#374]
**Fedoraware Version Date:**  
Latest
## Config used:
This works with any config.

## Description:  
Whipping friends doesn't work when ignore friends is on.

## Steps to reproduce the behavior:  
1. Turn on whip teammates
2. Turn on ignore friends
3. Try to whip your friend/s that's on your team
4. Doesn't work at all

## Additional context 
https://user-images.githubusercontent.com/106420166/172980356-804a3f61-fe42-460c-bb45-bbaafb569588.mp4

**Comment by FART900000000** [comment]
i dont know if i should laugh or cry

**Comment by tf2cheater2013** [comment]
i shall fix it shortly............ .m..i.h.h..rtr............................b..o.o...b..........i.....e.....s.......:........D.................

**Comment by xxmyn** [comment]
Fixed soon.
