### ISSUE TITLE
what the actual fuck (esp fps issue)

### ISSUE THREAD

**Issue by johnpablo1** [tf2cheater2013/Fedoraware#375]
**Fedoraware Version Date:**  
latest

## Config used:
[heavy rage.txt](https://github.com/tf2cheater2013/Fedoraware/files/8875590/heavy.rage.txt)

## Description:  
i think its pretty self explanatory

## Steps to reproduce the behavior:  
1. load my config
2. go behind a wall 
3. lag
4. or just do what the video does

## Additional context 

https://user-images.githubusercontent.com/106420166/172985916-feeecaa5-a854-4447-bb2f-f2488b927cbf.mp4

**Comment by xxmyn** [comment]
This has nothing to do with, don't multibox as many aim points.
