### ISSUE TITLE
Dt issue

### ISSUE THREAD

**Issue by johnpablo1** [tf2cheater2013/Fedoraware#376]
**Fedoraware Version Date:**  
Latest
## Config used:
Pretty sure it works with any config

## Description:  
When fake lag is on and teleport mode is set to smooth, dt completely breaks it stays like that until you restart tf2.

## Steps to reproduce the behavior:  
1. Turn on fake lag (disable on key option)
2. Turn on smooth teleport mode
3. Recharge
4. Can't move
5. Try to rejoin
6. Can't charge 

## Additional context 
Another issue is that Charged dt doesn't work with fake lag on idk might be intended feature

**Comment by SylveonBottle** [comment]
Smooth teleport appears to be broken.
Instant teleport still works.

**Comment by xxmyn** [comment]
seems like an issue with my cyoa code, id recommend downloading an earlier build until i fix it

**Comment by PeterPumpkinEater69real** [comment]
>Another issue is that Charged dt doesn't work with fake lag on idk might be intended feature
youre already choking packets
