### ISSUE TITLE
another dt issue

### ISSUE THREAD

**Issue by johnpablo1** [tf2cheater2013/Fedoraware#378]
**Fedoraware Version Date:**  
Latest

## Config used:
[heavy rage.txt](https://github.com/tf2cheater2013/Fedoraware/files/8878564/heavy.rage.txt)

## Description:  
Minigun/Tomislav Etc. Doesn't wait for the dt.

## Additional context 
I am holding M1 here but the dt wont wait and when recharging the minigun respin-up or something 

https://user-images.githubusercontent.com/106420166/173059691-b4c7ca51-ec98-4cf5-aaed-b5e2a9e45256.mp4

**Comment by SylveonBottle** [comment]
The issue with recharing was commented here: https://github.com/tf2cheater2013/Fedoraware/issues/373#issuecomment-1151865890

**Comment by johnpablo1** [comment]
oh ok
