### ISSUE TITLE
Backtracking Issues

### ISSUE THREAD

**Issue by thirdy1215** [tf2cheater2013/Fedoraware#38]
The Aimbot doesn't even try to shoot the Backtrack like spy's autoback stab doesn't work against backtracking 

Can you also increase the amount of ticks In Backtracking?

**Comment by wizardmanperson** [comment]
yeah the increase  of ticks would be better
Also, did you turn on aimbot aims last tick?

**Comment by thirdy1215** [comment]
I did but result is still the same

**Comment by thirdy1215** [comment]
Either it's a config problem or just a bug

**Comment by wizardmanperson** [comment]
yea its a bug then

**Comment by johnathon-walnut** [comment]
"Increasing" the amount of ticks would be useless, they wouldn't be valid and if you attempted to shoot them it wouldn't work. I think what you're asking for is fake latency which would let you increase it, but I don't really know how to do it and haven't bothered to look how but I can try.

The auto backstab - and everything else - has not been made specifically to work with the backtrack, the way it chooses which tick to target is based on which one is closest to your crosshair if that helps. Honestly this backtrack is not very well implemented.

**Comment by thirdy1215** [comment]
oh makes perfectly sense, I'll just close it so they won't be frustrated on making proper fake latency or other Bullshit
