### ISSUE TITLE
Anti-aim On even if off

### ISSUE THREAD

**Issue by FFJ11** [tf2cheater2013/Fedoraware#382]
![Screenshot 2022-06-14 003809](https://user-images.githubusercontent.com/102504389/173378840-0def1216-08a9-4826-99d6-0f1f843e7b98.png)

**Comment by FFJ11** [comment]
Alright

**Comment by xxmyn** [comment]
![image](https://user-images.githubusercontent.com/70382582/173492759-ff4217cd-f137-4bcb-9893-91ffdfc96f38.png)

learn to read.
