### ISSUE TITLE
Anti warp is not working slightly

### ISSUE THREAD

**Issue by johnpablo1** [tf2cheater2013/Fedoraware#384]
**Fedoraware Version Date:**  
latest

## Config used:
works with any config

## Description:  
brogen anti-warp

## Additional context 

https://user-images.githubusercontent.com/106420166/173508733-59512eef-79ae-47bb-acea-101139995d65.mp4

## Another issue
disabling wait for dt breaks dt and its charging is always (dt impossible) and when you move it moves you backwards

**Comment by xxmyn** [comment]
shift 20 ticks instead

**Comment by johnpablo1** [comment]
uhh its still not working tho

**Comment by xxmyn** [comment]
works fine for me

**Comment by johnpablo1** [comment]
its not my config cause its happening too on the default config

**Comment by xxmyn** [comment]
refer to previous comment

**Comment by johnpablo1** [comment]
i just recompiled its still broken

**Comment by xxmyn** [comment]
refer to previous comment

**Comment by xxmyn** [comment]
Ohh I now see you edited the title.

Yes the antiwarp is not perfect, shifting 20 ticks usually lets you hit both shots if you're having issues with other values.
