### ISSUE TITLE
My problems with fed

### ISSUE THREAD

**Issue by Tf2beballin** [tf2cheater2013/Fedoraware#386]
1 backtrack: backtracking does not even work most of the time
2 silent aimbot: Silent aimbot literally Misses even if trigger bot or auto shoot is on it still misses
3 smooth aimbot: starts to stutter when smoothing is at 2
4 crithack: works but doesn’t save crits for fast firing weapons like the minigun 
5 fedora loader: it’s literally detected for most Community servers said people I met
6 fedoraware: Sometimes crashing for no reason lol
(Might be edited later)

**Comment by Tf2beballin** [comment]
Read the section again 
People said that it’s detected in community servers

**Comment by xxmyn** [comment]
mensa.test.no

please post your results
