### ISSUE TITLE
Followbot Crash

### ISSUE THREAD

**Issue by hivec2** [tf2cheater2013/Fedoraware#388]
Queuing casual with followbot crashes, i believe the crash leads to CL_Move.cpp line 13? (VS Attached Debugger👌) no idea why.

**Comment by lnx00** [comment]
Reference:
https://github.com/tf2cheater2013/Fedoraware/blob/c64bb1d2a3787aa4e007930d233a4ef4cdfbd1cf/Fedoraware/TeamFortress2/TeamFortress2/Hooks/Detours/CL_Move.cpp#L13

Are you sture that it was caused by line 13? I don't know how the initialization of KeyHelper could crash in any way

**Comment by hivec2** [comment]
19 sorry, 	return oClMove(accumulated_extra_samples, bFinalTick);

**Comment by hivec2** [comment]
I can record an example in a couple hours showing it as it happens every time with the followbot enabled

**Comment by hivec2** [comment]
Fixed, Issue = Mental retardation
