### ISSUE TITLE
Dragons fury acting weird

### ISSUE THREAD

**Issue by thirdy1215** [tf2cheater2013/Fedoraware#39]
Fuck you  I'm not recording it 🖕

When trying to use aimbot with dragons fury will delay and teleports you before doing damage 

Idk I'm just describing it

**Comment by johnathon-walnut** [comment]
This is because it's still attemping to do it pSilent, but for some reason with the dragons fury I can't find out when it will next attack/time to next attack, meaning sendpacket is like constantly messed up when using it. I'll make it use the flamethrower logic.
