### ISSUE TITLE
fake lag chams on even tho fake lag is off

### ISSUE THREAD

**Issue by johnpablo1** [tf2cheater2013/Fedoraware#394]
**Fedoraware Version Date:**  
latest

## Config used:
Works with any

## Description:  
Fake lag chams shows even if fake lag is off

## Additional context 

https://user-images.githubusercontent.com/106420166/174066011-7ca52017-7686-468e-a6c9-818b6df3ba50.mp4

**Comment by xxmyn** [comment]
What?
