### ISSUE TITLE
few bugs

### ISSUE THREAD

**Issue by canedoly** [tf2cheater2013/Fedoraware#395]
my [config](https://files.catbox.moe/1oz0g8.rar)

Bugs

- Beams will draw multiple times if you have high ping (you can use net_fakelag like 250).

- If the enemy is crouching, not moving and you have huntsman on auto it will fail to headshot. (video)

- When using chams overlay, the weapons are invisible, you only see the overlay (video)

- Chams and fresnel overlay also apply to ammopacks which have been dropped by the enemy (screenshot and video)

![steamwebhelper_3t8QqjHJ7J](https://user-images.githubusercontent.com/81353241/174082134-d7df67c9-a83f-4143-96a6-a8c7847d4f28.png)

https://user-images.githubusercontent.com/81353241/174089754-c6e0febe-b245-4664-99fd-cec8c84374ce.mp4

(ignore the low fps, sharex was trolling me)

could you also add projectile prediction path only after firing with an duration, it just looks better than seeing the path for half a second just because you have the aimbot binded and auto shoot on

**Comment by femboy-boop** [comment]
<3 baan

**Comment by xxmyn** [comment]
argh I thought I fixed the huntsman!!

**Comment by xxmyn** [comment]
I've fixed 3/4 issues, not planning on fixing the other one.

**Comment by lnx00** [comment]
> I've fixed 3/4 issues, not planning on fixing the other one.

Lazy

**Comment by johnathon-walnut** [comment]
no
