### ISSUE TITLE
Improving Swing Prediction For Market Gardening.

### ISSUE THREAD

**Issue by yujispin990** [tf2cheater2013/Fedoraware#396]
Its swings way to early on any melee weapon on any class,i had to bind to m1 and let me do some of the prediction till i get close enough for the aimbot to lock on,hopefully it could be improved.

**Comment by xxmyn** [comment]
turn off swing prediction?

Ill look into fixing i later but I dont really care right now.

**Comment by xxmyn** [comment]
also duplicate issue wth??
