### ISSUE TITLE
flamethrower doesnt range check

### ISSUE THREAD

**Issue by johnpablo1** [tf2cheater2013/Fedoraware#397]
**Fedoraware Version Date:**  
latest

## Config used:
[Pyro - Copy.txt](https://github.com/tf2cheater2013/Fedoraware/files/8925316/Pyro.-.Copy.txt)

## Description:  
it doesnt range check when it used to before baan's update 

## Steps to reproduce the behavior:  
1. load my config
2. hold the aimbot button
3. be far away from the target
4. the flamethrower cant hit the target

## Additional context 

https://user-images.githubusercontent.com/106420166/174244982-a5b2096d-6318-4956-9273-4a5a356adbba.mp4

**Comment by xxmyn** [comment]
Fixed shortly.
