### ISSUE TITLE
projectile bug

### ISSUE THREAD

**Issue by johnpablo1** [tf2cheater2013/Fedoraware#399]
**Fedoraware Version Date:**  
latest

## Config used:
[Soldier1.txt](https://github.com/tf2cheater2013/Fedoraware/files/8935215/Soldier1.txt)

## Description:  
the aimbot draws too far infront of the character and it only starts to work when a player is going to walk to a slope going up or down

## Steps to reproduce the behavior:  
1. load my config
2. go as soldier
3. try to shoot a person/npc
4. it will draw too far ahead

## Additional context 

https://user-images.githubusercontent.com/106420166/174477737-ca41873f-de5d-4577-83c5-3ce6c5c4388f.mp4

**Comment by johnathon-walnut** [comment]
i've known about this bug for ages just don't know why it happens nor how to fix

**Comment by johnpablo1** [comment]
i realize it only happens when point scale is maxed out

**Comment by johnathon-walnut** [comment]
no this has happened before that stuff was even added

**Comment by johnpablo1** [comment]
it has never happened to me before it was added

**Comment by johnathon-walnut** [comment]
ok well it has happened to me before it was added

**Comment by xxmyn** [comment]
Enemies that spawn in while your local player is fakelagging will also consistently be overpredicted.

**Comment by xxmyn** [comment]
Apparently this only happens on walkway.

**Comment by johnpablo1** [comment]
this happened to me when i was in a ingame match but ok
