### ISSUE TITLE
viewmodel aimbot is broken

### ISSUE THREAD

**Issue by mr-nv** [tf2cheater2013/Fedoraware#403]
it aims to the other side
https://user-images.githubusercontent.com/31269663/174635630-3cf72d88-7f7d-4ce3-9047-7917baf04468.mp4

**Comment by femboy-boop** [comment]
it should be fine. due to flip model.

**Comment by mr-nv** [comment]
still needs to be fixed tho

вт, 21 июн. 2022 г., 07:46 Femboy ***@***.***>:

**Comment by mr-nv** [comment]
retarded fix would be to toggle flipped viewmodels off while viewmodel aimbot is active

**Comment by xxmyn** [comment]
just - the yaw offset?

**Comment by mr-nv** [comment]
if you mean doing (vEyeAngles.y *= -1.f) here https://github.com/tf2cheater2013/Fedoraware/blob/main/Fedoraware/TeamFortress2/TeamFortress2/Hooks/Detours/C_BasePlayer_CalcViewModelView.cpp#L21
then no it doesnt work
my math is too shit to figure out the proper fix

**Comment by mr-nv** [comment]
doesnt really matter how you fix it in the end eh
