### ISSUE TITLE
add region unlock like in lmaobox

### ISSUE THREAD

**Issue by ilya228011** [tf2cheater2013/Fedoraware#407]
add region unlock like in lmaobox

**Comment by johnathon-walnut** [comment]
Already in the cheat.

**Comment by ilya228011** [comment]
Where can I find region unlock?

**Comment by lnx00** [comment]
> Where can I find region unlock?

Misc -> Region Selector

**Comment by ilya228011** [comment]
Equip region unlock - Have up to 3 hats or cosmetics equipped by unlocking the region restriction  ITS LMAO

**Comment by johnathon-walnut** [comment]
Ive been wanting to mess around with item schema stuff anyway

**Comment by johnathon-walnut** [comment]
This is done in https://github.com/tf2cheater2013/Fedoraware/commit/605a95bbdb07553786a1cc63231ac7c456d59e4f
