### ISSUE TITLE
[IMPORTANT BUG] Pong is opponent is missing....

### ISSUE THREAD

**Issue by HutchyBean** [tf2cheater2013/Fedoraware#416]
https://user-images.githubusercontent.com/38333275/175423488-8c7780b8-3021-4693-92cb-04aa8afbcbe4.mp4

**Comment by HutchyBean** [comment]
:troller:

**Comment by lnx00** [comment]
Oh no, i'm sorry! I will fix this ASAP

**Comment by HutchyBean** [comment]
Thank you so much...

**Comment by lnx00** [comment]
This should now be fixed. I hope you forgive the inconvenience this caused!
