### ISSUE TITLE
RESET CONFIG

### ISSUE THREAD

**Issue by rrhyast** [tf2cheater2013/Fedoraware#418]
Add option to reset config, It's annoying to use pre-configured CFG.

**Comment by HutchyBean** [comment]
What do you mean? reset what config ?

**Comment by rrhyast** [comment]
> What do you mean? reset what config ?

Default CFG + where is the CFG folder?

**Comment by tf2cheater2013** [comment]
the config that you get on inject is the default config.

**Comment by rrhyast** [comment]
> the config that you get on inject is the default config.

WTF how to reset it why u close my issue.

**Comment by johnathon-walnut** [comment]
Just turn all the features off

**Comment by xxmyn** [comment]
> > the config that you get on inject is the default config.
> 
> WTF how to reset it why u close my issue.

I just said, the config you get on inject, is the default config.
