### ISSUE TITLE
Cheat Detection pyro crit

### ISSUE THREAD

**Issue by GabrielNicolas10** [tf2cheater2013/Fedoraware#425]
remove Cheat Detection when I die my tf2 freezes then comes back and something pops up in the cheat Detection chat it crashes my tf2 and make the crit hack work with pyro's flamethrower

**Comment by johnathon-walnut** [comment]
Is the 10 in your name to represent the year you were born in?

**Comment by GabrielNicolas10** [comment]
'-'

**Comment by GabrielNicolas10** [comment]
will you remove yes or no?

**Comment by lnx00** [comment]
It's not even broken
