### ISSUE TITLE
Cheat undetected

### ISSUE THREAD

**Issue by GabrielNicolas10** [tf2cheater2013/Fedoraware#429]
make the cheat undetected i am banned from servers, and blackwonder

**Comment by johnathon-walnut** [comment]
no

**Comment by GabrielNicolas10** [comment]
why?

**Comment by johnathon-walnut** [comment]
not worth the time

**Comment by HutchyBean** [comment]
Do it yourself 😈😈😈😈

**Comment by GabrielNicolas10** [comment]
i don't know anything about c++ i don't know if it runs on windows 7 worst decision was to change my windows 10 for windows 7

**Comment by johnathon-walnut** [comment]
fedoraware doesn't run on windows 7

**Comment by xxmyn** [comment]
why did you switch to windows 7 lmao
