### ISSUE TITLE
the revolver does not fire on the spy when fake lags are enabled

### ISSUE THREAD

**Issue by ilya228011** [tf2cheater2013/Fedoraware#43]
**Fedoraware Version Date:**  

## Steps to reproduce:  
- [ ] I am able to consistently reproduce this error

1. Enable X
2. Do Y
3. Notice Z

## Screenshot of cheats enabled  

- [ ] I have included the steps to reproduce to the best I am able to share.

**Comment by johnathon-walnut** [comment]
ok

**Comment by cOpEtriNe** [comment]
how many fake lags?

**Comment by ilya228011** [comment]
it doesn't matter, even if you put 1, it still won't shoot

**Comment by xxmyn** [comment]
I have tried this with the stock revolver, and all types of fakelag, in both a casual and local server and have been unable to reproduce this error, please reopen the issue with your fedoraware config and your host_writeconfig file uploaded.
