### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by GabrielNicolas10** [tf2cheater2013/Fedoraware#430]
when i die my tf2 freezes it only happens when i have a hack when i have no it does not happen this is not a thing of my pc and the cheat, remove the cheat detection, and also when i injected it came all unconfigured

**Comment by xxmyn** [comment]
Closed because you've admitted to running windows 7 (this cheat does not support windows 7).

**Comment by GabrielNicolas10** [comment]
does that mean fedoraware does not support windows 7?

**Comment by GabrielNicolas10** [comment]
Shit

**Comment by gayblackirony** [comment]
only win xp, win 10

**Comment by gayblackirony** [comment]
sorry

**Comment by GabrielNicolas10** [comment]
this is the only good hack

**Comment by gayblackirony** [comment]
fr.

**Comment by gayblackirony** [comment]
name any other cheat that has pong

**Comment by GabrielNicolas10** [comment]
there is a way to disable cheat detection I don't see any option in the cheat that has cheat detection as disabled

**Comment by canedoly** [comment]
in esp for players

**Comment by GabrielNicolas10** [comment]
and the cheat mark?

**Comment by xxmyn** [comment]
Gabriel one more comment I will ban you from commenting :D

**Comment by lnx00** [comment]
> name any other cheat that has pong

BigPackets has snake, don't know if it has pong too
