### ISSUE TITLE
Dxlevel

### ISSUE THREAD

**Issue by GabrielNicolas10** [tf2cheater2013/Fedoraware#432]
hi if it's not too much to ask, can you make the cheat support dxlevel 81?

**Comment by gayblackirony** [comment]
just lower your gamma

**Comment by GabrielNicolas10** [comment]
hm

**Comment by GabrielNicolas10** [comment]
thanks

**Comment by GabrielNicolas10** [comment]
I'm saying that the cheat does not support dxlevel 81

**Comment by GabrielNicolas10** [comment]
and so far they haven't removed the cheat detection and when i inject it it still comes all unconfigured

**Comment by canedoly** [comment]
> I'm saying that the cheat does not support dxlevel 81

why are you even using dxlevel below 90?
at this point the cheat should have a notification, whenever someone has dxlevel below 90

**Comment by VOID-Nightmare** [comment]
> > I'm saying that the cheat does not support dxlevel 81
> 
> why are you even using dxlevel below 90? at this point the cheat should have a notification, whenever someone has dxlevel below 90

This would be smart. It's not super obvious what went wrong unless you know about dxlevels in the first place

**Comment by GabrielNicolas10** [comment]
when i inject fedoraware it comes with everything disabled

**Comment by GabrielNicolas10** [comment]
yesterday he was normal

**Comment by VOID-Nightmare** [comment]
> when i inject fedoraware it comes with everything disabled

Should probably be its own issue, but yeah i also experience this

**Comment by canedoly** [comment]
> when i inject fedoraware it comes with everything disabled

its because baan changed every var to be disabled by default in this [commit](https://github.com/tf2cheater2013/Fedoraware/commit/c106bddb70a2038f5904be49b84ad34d3cce9f1c)
just make your own config and save it

**Comment by lnx00** [comment]
no
