### ISSUE TITLE
add nolerp

### ISSUE THREAD

**Issue by yesyes786** [tf2cheater2013/Fedoraware#436]
add nolerp like rijin would be pretty cool

**Comment by HutchyBean** [comment]
we have ...

**Comment by yesyes786** [comment]
rijins feels different

**Comment by johnathon-walnut** [comment]
Honestly i'd rather NOT do this given how wonky it is in rijin with cosmetics following people for no reason and stuff

**Comment by GabrielNicolas10** [comment]
just add

**Comment by FART900000000** [comment]
> just add

hi gabrielnicolas10 can you please fucking shut up cunt nobody gives a shit
