### ISSUE TITLE
Killstreak enabler

### ISSUE THREAD

**Issue by wizardmanperson** [tf2cheater2013/Fedoraware#44]
Add a killstreak enabler.

**Comment by johnathon-walnut** [comment]
How

**Comment by wizardmanperson** [comment]
idk

**Comment by lnx00** [comment]
@johnathon-walnut https://github.com/nullworks/cathook/blob/32d15aaa2d00768239eac362de0e4134571cbf9c/src/hacks/Killstreak.cpp
