### ISSUE TITLE
after getting kicked game crashes on joining new round and death effects for enemy ragdolls dont work

### ISSUE THREAD

**Issue by Muffinmaker2** [tf2cheater2013/Fedoraware#445]
**Fedoraware Version Date:26.6.2022**  

## Config used:

<https://www.mediafire.com/file/qxh2ppelc0ar5tb/MuffinsSexConfig.fw/file>

## Description:  
 If you play one game and u get kicked out of  and then join the next match the game crashes

## Steps to reproduce:  
- [ ] I am able to consistently reproduce this error

1. Load Config
2. Join Game
3. get kicked from that game
4. join the next game
5. crash

## Additional context 
Also the Death effects dont seem to work the ones with the gold and ice and shit

- [ ] I have included the steps to reproduce to the best I am able to share.

**Comment by johnathon-walnut** [comment]
regarding the crash, it can't get it to happen to me
regarding the ragdoll effects "not working", you're wrong

**Comment by Muffinmaker2** [comment]
> regarding the crash, it can't get it to happen to me
> regarding the ragdoll effects "not working", you're wrong

what did i wrong tho?

**Comment by johnathon-walnut** [comment]
if i knew i would have told u mate

**Comment by canedoly** [comment]
> > regarding the crash, it can't get it to happen to me
> > regarding the ragdoll effects "not working", you're wrong
> 
> what did i wrong tho?

do you have ragdolls on? if so try disabling chams for ragdolls maybe that will help

**Comment by Muffinmaker2** [comment]
disabling chams for ragdolls didnt fix anything what else could be the cause?

**Comment by Muffinmaker2** [comment]
ok now after testing for 2 hours apparently enabling dme chams and normal chams enabled makes that the ragdoll effects wont render or something
