### ISSUE TITLE
Crashes during menu load

### ISSUE THREAD

**Issue by DEVILISHTUNE** [tf2cheater2013/Fedoraware#446]
## Config used:
N/A

## Steps to reproduce:  
Just load in.

Just try and load the menu

- [ Well best I can as it does it to me] I have included the steps to reproduce to the best I am able to share.

**Comment by johnathon-walnut** [comment]
we already know

**Comment by DEVILISHTUNE** [comment]
> we already know

Ah thanks! didnt know sorry!

**Comment by GabrielNicolas10** [comment]
add aimbot to sticky bomb

**Comment by johnathon-walnut** [comment]
@xxmyn it's time, get rid of him
