### ISSUE TITLE
Scrolling for playerlist

### ISSUE THREAD

**Issue by kyrahm** [tf2cheater2013/Fedoraware#447]
When I lower the resolution for tf2, the playerlist isnt shown completely at the bottom. Need scrolling for playerlist

**Comment by xxmyn** [comment]
fedoraware doesn't support playing on a nintendo.

**Comment by johnathon-walnut** [comment]
I mean we could easily add this? Surely the easiest way would be to just put it in a child so it can scroll, like we do in the main menu?
