### ISSUE TITLE
You cannot reset the custom menu button.

### ISSUE THREAD

**Issue by xxmyn** [tf2cheater2013/Fedoraware#448]
Trying to set it back to INSERT closes the menu, and does not overwrite the current key.

**Comment by johnathon-walnut** [comment]
based

**Comment by VOID-Nightmare** [comment]
> Trying to set it back to INSERT closes the menu, and does not overwrite the current key.

This is because 'INSERT' is hard-coded to toggle the menu regardless of what the custom menu button is. If you wish to un-bind it you should be able to press the 'ESC' key to set it to none.
