### ISSUE TITLE
Suggestion Auto Accept for casual

### ISSUE THREAD

**Issue by Muffinmaker2** [tf2cheater2013/Fedoraware#449]
Like when we already have this
![image](https://user-images.githubusercontent.com/107619523/175950668-4e73f7a6-fb5f-4a39-9870-410876c15294.png)
why dont we can also have this
![image](https://user-images.githubusercontent.com/107619523/175950851-ae87cda0-babf-4f1a-bf03-2cb928a342c7.png)

**Comment by johnathon-walnut** [comment]
Sure

**Comment by johnathon-walnut** [comment]
Just to clarify, this means you want it to skip the 10 seconds once you've found a match right?

**Comment by Muffinmaker2** [comment]
yea

**Comment by johnathon-walnut** [comment]
Readded this to actually work and not suck

**Comment by Muffinmaker2** [comment]
megasex 👍
