### ISSUE TITLE
Cant compile Fedoraware in VS 2022

### ISSUE THREAD

**Issue by Gught** [tf2cheater2013/Fedoraware#450]
Every time i try to compile source code of Fedoraware into *.dll
I get this error:
"NuGet Package restore failed for project TeamFortress2: Unable to find version '1.79.0' of package 'boost'.
  https://api.nuget.org/v3/index.json: Unable to load the service index for source https://api.nuget.org/v3/index.json.
  An error occurred while sending the request.
  The underlying connection was closed: An unexpected error occurred on a send.
  Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.
  An existing connection was forcibly closed by the remote host.
 Please see Error List window for detailed warnings and errors."

I managed to compile it few days ago but this error appeared again.				
If someone know how to fix it please tell me

**Comment by johnathon-walnut** [comment]
Install boost

**Comment by Gught** [comment]
how?

**Comment by Gught** [comment]
i just cant even refresh the NuGet package manager it just doesnt work

**Comment by johnathon-walnut** [comment]
How did you fix it last time?

**Comment by Gught** [comment]
i dont know but last time when i got this error i just reinstalled VS 2022 after a month and it worked

**Comment by Gught** [comment]
i tried it again and it didnt work

**Comment by NotAnUser1** [comment]
Right-click on the “TeamFortress2” in the Solution Explorer like shown and select manage NuGet packages
![image](https://user-images.githubusercontent.com/72518912/175977547-5afb1cba-67a2-4832-9af8-4b208fa21400.png)

It should load something for a sec then there should appear a popup up top crying about boost package not being available or something with a restore option, click that

**Comment by Gught** [comment]
> Right-click on the “TeamFortress2” in the Solution Explorer like shown and select manage NuGet packages ![image](https://user-images.githubusercontent.com/72518912/175977547-5afb1cba-67a2-4832-9af8-4b208fa21400.png)
> 
> It should load something for a sec then there should appear a popup up top crying about boost package not being available or something with a restore option, click that

I have already tried that, thats  what VS is actually trying to do

**Comment by NotAnUser1** [comment]
Then try deleting your packages folder that's in the same folder as your .sln file and do those again, that should redownload it

**Comment by Gught** [comment]
whats the name of the packages folder?
I cant find it in folder with .sln file

**Comment by NotAnUser1** [comment]
![image](https://user-images.githubusercontent.com/72518912/175982015-acec1845-aae7-4a69-b1e7-23b62dfb31c4.png)

it's just called that, maybe try backing up some folders or going in some

**Comment by Gught** [comment]
I dont have this one

**Comment by Gught** [comment]
I can only see file named packages.config 
in "TeamFortress2" folder

**Comment by NotAnUser1** [comment]
https://stackoverflow.com/questions/41185443/nuget-connection-attempt-failed-unable-to-load-the-service-index-for-source

Maybe try your luck there, I'm out of ideas

**Comment by Gught** [comment]
FIXED IT! by manually installing boost using separately installed nuget.exe with command line "nuget.exe Install boost -Version 1.79.0" and copying boost package files to "C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\" directory

**Comment by Gught** [comment]
Well, it didnt fix this error but it helped me compiling fedoraware in VS 2022 .
so this discussion is closed
