### ISSUE TITLE
Double tap and shotgun

### ISSUE THREAD

**Issue by kyrahm** [tf2cheater2013/Fedoraware#457]
Double tap no works with weapon shotgun. With Soda Popper it works fine.

**Comment by HutchyBean** [comment]
soda popper is faster

**Comment by xxmyn** [comment]
is this post a joke?

**Comment by johnathon-walnut** [comment]
> because shotguns don't have a similar fire rate to Force a Nature/Soda popper?

Yeah but it's called doubletap bro not rapid fire

**Comment by xxmyn** [comment]
I genuinely can't believe you are this stupid :D  
doubletap does not "fire both bullets", it allows you to remove a significant amount of delay between two shots, on small fire rate weapons (<300ms) this gives the effect of firing more than 1 bullet at a time, but on shotguns that take longer than that, the best doubletap can do is reduce the time between shots.

this is publicly available information, please google it before you make a gh issue about it :DDDDDD
