### ISSUE TITLE
[BUG] Auto Extinguish crashes game

### ISSUE THREAD

**Issue by Muffinmaker2** [tf2cheater2013/Fedoraware#458]
Fedoraware Version Date: 28.06.2022

## Config used:
https://www.mediafire.com/file/gr229a17emgeb8o/newtest.fw/file

## Description:  
When Auto Extinguish is activated in Triggerbot tab and u try running out of spawn as pyro ur game crashes.
Tested both ways. Triggerbot with no key and Triggerbot with a key and in both Scenarios the game crashes
in the one with the triggerbot key set pressing the key the game crashes

## Steps to reproduce:  

1. Set a Triggerbotkey or dont do it
2. Enable Autoairblast shit and Auto Extinguish
3. Go in to a game
4. Choose Pyro
5. Try walking out of spawn
6. Have fun
## Additional context 
Also the Auto Accept dont work :c

**Comment by xxmyn** [comment]
Closing until it's shown that this is still an issue.
