### ISSUE TITLE
This cheat blinds me or annoys me with stupid shit

### ISSUE THREAD

**Issue by Xee545** [tf2cheater2013/Fedoraware#46]
**Fedoraware Version Date:**  
Feb 27th, 2022

## Config used:
https://files.catbox.moe/2yr3b6.fed More Visuals
https://files.catbox.moe/ixa3j3.fed Fewer Visuals, More Rijin-y?
I don't really know if visuals are the issue here.

## Description:  
Either the screen creates a blinding effect, freezes/crashes the game, or creates a overlay

## Steps to reproduce:  
- [O] I am able to consistently reproduce this error

1. Doubletap + Aimbot someone
2. Test your luck, it has like a 50% chance of breaking.

## Additional context 
CPU: 11th Gen Intel Core i5 1135G7 4c/8t Processor
GPU: Intel Iris Xe Graphics (Integrated Graphics)
Lmaobox and Nullcore doesn't do this.

## Screenshot of cheats enabled  
https://steamuserimages-a.akamaihd.net/ugc/1840287886128759244/627372D2CD4AEA09540A6688DDA2ACCE557A4F04/
https://steamuserimages-a.akamaihd.net/ugc/1840287886128045827/0E85E7A07C3CAF09B4BA89170BDC8AF5A9D2EA00/
https://steamuserimages-a.akamaihd.net/ugc/1840287886128014168/13655FD32990CEFC634A7458C131712922C2D316/

- [O] I have included the steps to reproduce to the best I am able to share.

**Comment by HeXz69** [comment]
on ixa3j3.fed cfg set smooth to minimum 1 because setting it to 0 does this "blinding effect"

**Comment by xxmyn** [comment]
[fixed here](https://github.com/tf2cheater2013/Fedoraware/tree/baan(bad))
