### ISSUE TITLE
[BUG!!!!] MENU BROKEN (UN-USABLE)

### ISSUE THREAD

**Issue by HutchyBean** [tf2cheater2013/Fedoraware#473]
![image](https://user-images.githubusercontent.com/38333275/176788669-0156ed38-bc98-437b-8802-28d94aef5f1d.png)

**Comment by HutchyBean** [comment]
![image](https://user-images.githubusercontent.com/38333275/176788746-68bd9b3f-6ab8-4cad-ac26-431329ddf500.png)
addenium

**Comment by tf2cheater2013** [comment]
sut u.
