### ISSUE TITLE
i can dual inject with lbox?

### ISSUE THREAD

**Issue by nofhdgtf778** [tf2cheater2013/Fedoraware#48]
can i dual inject with lmaobox and play?

**Comment by johnathon-walnut** [comment]
Probably not

**Comment by nofhdgtf778** [comment]
> Probably not

any solution?

**Comment by lnx00** [comment]
Why do people want to dual inject? Just choose one of both cheats...

@canedoly You're probably getting kicked due to "Issued too many commands" since that's the most common reason when joining a server.

**Comment by xxmyn** [comment]
duel injecting is not supported in fware
