### ISSUE TITLE
draw prediction path after shoot

### ISSUE THREAD

**Issue by Podssa** [tf2cheater2013/Fedoraware#499]
draw prediction path after shoot not 24/7 and add meter lines to it if u can.

**Comment by xxmyn** [comment]
maybe :D

**Comment by johnathon-walnut** [comment]
What purpose do the meter lines actually serve?

**Comment by Podssa** [comment]
it makes the path not look like spaghetti line

**Comment by johnathon-walnut** [comment]
Waste of time

**Comment by Podssa** [comment]
Well it will look much better and its just small add

**Comment by NitroTF2** [comment]
It was a thing, with draw projectile line or render it.

**Comment by relaxtakenotes** [comment]
https://user-images.githubusercontent.com/91839650/178721701-c5cab50b-463c-44e4-8924-ef70bb61ce06.mp4

**Comment by xxmyn** [comment]
> hl2_rpYVRAfV2d.mp4

i thought u used rijin and didnt touch other cheats

**Comment by johnathon-walnut** [comment]
> hl2_rpYVRAfV2d.mp4

What's the point of this video? The projectile aimbot misses when the target doesn't follow their predicted path?
