### ISSUE TITLE
Auto class pick-up

### ISSUE THREAD

**Issue by FilippoFerarri** [tf2cheater2013/Fedoraware#50]
I suggest you add a auto class pick ( allows you to automatically select a class in config, so we for example do not have to manually select soldier, if we play with sondier config)

**Comment by BeeEllEsss** [comment]
???

**Comment by kamizyyy** [comment]
just pick any class, its not that hard???

**Comment by johnathon-walnut** [comment]
Honestly the more I think about this the less I understand why you'd need this

**Comment by Sallendher** [comment]
He lazy as fuck haha

**Comment by johnathon-walnut** [comment]
You aren't owed features.

**Comment by nofhdgtf778** [comment]
> You aren't owed features.

when crithack

**Comment by xxmyn** [comment]
this has been added and merged
