### ISSUE TITLE
Suggestion: Fresnel Overlay

### ISSUE THREAD

**Issue by nofhdgtf778** [tf2cheater2013/Fedoraware#56]
![image](https://user-images.githubusercontent.com/99003686/156836165-0403232e-a82e-4011-927c-d8d8661052aa.png)

This is what it looks like

**Comment by xxmyn** [comment]
add an image of whatever the hell ur talking about, fresnel with glow overlay looks trash, "fresnel overlay" is just glow i presume? if so i might add overlays later but maybe u should learn how to actually request a feature instead of going "me want fresnel glow on players mm yes"

**Comment by nofhdgtf778** [comment]
cant deny

**Comment by nofhdgtf778** [comment]
![image](https://user-images.githubusercontent.com/99003686/156836165-0403232e-a82e-4011-927c-d8d8661052aa.png)

CHECK

**Comment by xxmyn** [comment]
A) looks ugly
B) usually called glow overlay

**Comment by nofhdgtf778** [comment]
HOW LOOKS UGLY I DONT GET IT

**Comment by nofhdgtf778** [comment]
XD glow overlay is the glow on the edge of player

**Comment by nofhdgtf778** [comment]
add it man

**Comment by xxmyn** [comment]
glow overlay is an overlay like most csgo cheats use, and it sucks.

from memory to get it looking nice u render chams twice, once for the bottom material and once for the overlay material, doing it another way almost always looks bad

**Comment by xxmyn** [comment]
and as i already said earlier, i might add overlay chams LATER

**Comment by johnathon-walnut** [comment]
I think it looks very nice :)

**Comment by JAGNEmk** [comment]
First you need to render the original player material, then after that you need to render the fresnel material with [$additive](https://developer.valvesoftware.com/wiki/$translucent#Additional_parameters) to get the overlay glow effect as seen [here](https://streamable.com/y86y0p)

**Comment by johnathon-walnut** [comment]
You paste from me jagne. Gongleware owns you and all.

**Comment by nofhdgtf778** [comment]
> I think it looks very nice :)

**Comment by nofhdgtf778** [comment]
> You paste from me jagne. Gongleware owns you and all.

so

**Comment by nofhdgtf778** [comment]
gonna add it??

**Comment by johnathon-walnut** [comment]
Pay

**Comment by johnathon-walnut** [comment]
Alternatively, stop acting entitled to features. You could add this yourself. When all you say is stuff like "Add it man" it just makes me NOT want to add it out of spite. It's really quite annoying

**Comment by nofhdgtf778** [comment]
madpaster honestly

**Comment by nofhdgtf778** [comment]
> First you need to render the original player material, then after that you need to render the fresnel material with [$additive](https://developer.valvesoftware.com/wiki/$translucent#Additional_parameters) to get the overlay glow effect as seen [here](https://streamable.com/y86y0p)

and how you do that?

**Comment by xxmyn** [comment]
> > First you need to render the original player material, then after that you need to render the fresnel material with [$additive](https://developer.valvesoftware.com/wiki/$translucent#Additional_parameters) to get the overlay glow effect as seen [here](https://streamable.com/y86y0p)
> 
> and how you do that?

jagne literally told you exactly how to do it, the exact material parameter you needed for the overlay, everything else is pretty clear in the code if u wanted to actually look at it.

if ur srsly sitting here asking for us to spoonfeed u code only to call us madpasters right before ur just gonna get ur requests ignored

**Comment by nofhdgtf778** [comment]
> > > First you need to render the original player material, then after that you need to render the fresnel material with [$additive](https://developer.valvesoftware.com/wiki/$translucent#Additional_parameters) to get the overlay glow effect as seen [here](https://streamable.com/y86y0p)
> > 
> > 
> > and how you do that?
> 
> jagne literally told you exactly how to do it, the exact material parameter you needed for the overlay, everything else is pretty clear in the code if u wanted to actually look at it.
> 
> if ur srsly sitting here asking for us to spoonfeed u code only to call us madpasters right before ur just gonna get ur requests ignored

alr man you know, im sorry for that i just want to use good features but i dont know how to code tbh

**Comment by hyperventilation** [comment]
> i dont know how to code tbh
:trollface:

**Comment by nofhdgtf778** [comment]
> > i dont know how to code tbh
> 
> :trollface:

ofc

**Comment by xxmyn** [comment]
![unknown](https://user-images.githubusercontent.com/70382582/157416922-475e3545-ed89-41e1-98ec-78846543b387.png)
yes/no

**Comment by johnathon-walnut** [comment]
Yes yes yes

**Comment by xxmyn** [comment]
this is being worked on [here](https://github.com/tf2cheater2013/Fedoraware/tree/DME(WIP))
