### ISSUE TITLE
A small mistake in the menu

### ISSUE THREAD

**Issue by HeXz69** [tf2cheater2013/Fedoraware#61]
I am getting daun when trying to Pull requests so I am writing here. There is a bug in menu where selecting ignore Cloaked/Friends does nothing, fix it in menu.cpp at line 885, it looks like this &Vars::Aimbot::Global::IgnoreCloaked.m_Var and it should be &Vars::Triggerbot::Global::IgnoreCloaked.m_Var and same with IgnoreFriends, sorry in advance for my poor English

**Comment by johnathon-walnut** [comment]
Thanks, fixed in https://github.com/tf2cheater2013/Fedoraware/commit/b6cec58781ff19787b0388648681e61d1c6300f6
