### ISSUE TITLE
Tracers

### ISSUE THREAD

**Issue by Podssa** [tf2cheater2013/Fedoraware#62]
**Fedoraware Version Date:**  

## Steps to reproduce:  
- [ ] I am able to consistently reproduce this error

1. Enable X
2. Do Y
3. Notice Z

## Screenshot of cheats enabled  

- [ ] I have included the steps to reproduce to the best I am able to share.

**Comment by johnathon-walnut** [comment]
What a cool issue

**Comment by Podssa** [comment]
The tracers dsnt follow the player

**Comment by johnathon-walnut** [comment]
What do you mean "follow"?

**Comment by Podssa** [comment]
it dosnt follow the playyer when i have aimbot on it just shots straight forward also sorry very bad english

**Comment by Podssa** [comment]
it dosnt follow the playyer when i have aimbot on it just shots straight forward also sorry very bad english

**Comment by Podssa** [comment]
it dosnt follow the playyer when i have aimbot on it just shots straight forward also sorry very bad english

**Comment by johnathon-walnut** [comment]
I can't really tell what you're trying to say

**Comment by xxmyn** [comment]
user issue, send config & reopen.
