### ISSUE TITLE
Broken tracer

### ISSUE THREAD

**Issue by Podssa** [tf2cheater2013/Fedoraware#63]
![image](https://user-images.githubusercontent.com/101215838/157317737-41980842-d0da-4f28-8058-c1de852b3b13.png)

You see the tracer isent following the player it just shots forward plz fix sorry for bad english

**Comment by Podssa** [comment]
idk

**Comment by Podssa** [comment]
if u have viewmodel aimbot then it dosnt bug

**Comment by xxmyn** [comment]
Not a bug, this is how tracers work, so this is how particle tracers work + it would look weird imo if we set them to draw from the barrel of ur gun to somebody who's nowhere near where your gun is facing.
