### ISSUE TITLE
Add AA cycling feature.

### ISSUE THREAD

**Issue by Umbrozium** [tf2cheater2013/Fedoraware#64]
As mentioned before, I suggest adding an option to cycle through AA (and also, perhaps add an option to choose which angles to enable/disable in the cycle).

**Comment by xxmyn** [comment]
This sounds... bad.

Do you mean like manual angles like those in csgo hvh?

**Comment by johnathon-walnut** [comment]
Probably like controlling the angle with the arrow keys or something

**Comment by johnathon-walnut** [comment]
The idea in my head that comes from "cycling" would just be going through the list on a key, left, right, up, random, edge, spin, left, right, up, random, etc.. Doesn't seem particularly useful, if anything would seem inconvenient.

**Comment by xxmyn** [comment]
Cycling between angles just seems like it would yield the same result as the random yaw option...

**Comment by xxmyn** [comment]
well, thats bad, i dont know what else to tell you :/

**Comment by Umbrozium** [comment]
> well, thats bad, i dont know what else to tell you :/
I guess? I mean, I thought cycling through them would take longer for the enemy to resolve.

**Comment by xxmyn** [comment]
random pitch would have the exact same effect as cycling by that logic.

**Comment by Umbrozium** [comment]
> random pitch would have the exact same effect as cycling by that logic.

Hm, I see. Random got resolved by rathook instantly, though.

**Comment by xxmyn** [comment]
yes as I already said, changing pitch does not make u unresolvable or anything, if anything, its worse than having a static fake pitch.

**Comment by Umbrozium** [comment]
> yes as I already said, changing pitch does not make u unresolvable or anything, if anything, its worse than having a static fake pitch.

I know AA isn't godmode, but it got resolved unusually fast. Alright, guess this can be closed then.

**Comment by Fowgzu** [comment]
Please add manual angles tho, i think it would be very nice

**Comment by electrospaz** [comment]
> > yes as I already said, changing pitch does not make u unresolvable or anything, if anything, its worse than having a static fake pitch.
> 
> I know AA isn't godmode, but it got resolved unusually fast. Alright, guess this can be closed then.

you dont need good aa, just use edge.
