### ISSUE TITLE
Add a A-Pose character in Misc

### ISSUE THREAD

**Issue by LukeHenson18** [tf2cheater2013/Fedoraware#65]
Add it so we can just skip the steps on how to make a class A-pose

**Comment by johnathon-walnut** [comment]
This isn't really something I could implement unless you literally want me to try and make it 1) killbind, 2) respawn by changing classes twice 3) emptying the ammo and holding the attack key and then 4) walking to and picking up the dropped weapon from where you kill binded. This also doesn't work on all classes, and there's also the dispenser option. It just isn't worth the time investment to add this no offense

**Comment by xxmyn** [comment]
no.
