### ISSUE TITLE
Add "Scoped only" option for triggerbot

### ISSUE THREAD

**Issue by Fowgzu** [tf2cheater2013/Fedoraware#66]
Would be convenient, ty

**Comment by Fowgzu** [comment]
Also ignore cloaked for autoshoot doesn't work or maybe i can't figure it out

**Comment by xxmyn** [comment]
This works for me, and the code I can find of it looks fine, please attach a video & ur config if the problem persists

**Comment by xxmyn** [comment]
as for the scoped only request, it just seems like it would bloat the menu more, you're better off setting a key for triggerbot if you want to control when it actually triggers.

**Comment by Fowgzu** [comment]
Honestly, when you're playing sniper and want a head only triggerbot, you'd assume it's to use it when scoped only, there is no point on in triggering to only do 50 damage, accidentally most of the time. Ofc you can use it manually, but then again I think it would be convenient to make it work efficiently. As for the menu, the triggerbot page is already relatively empty, I think just another box to tick wouldn't change much

**Comment by Fowgzu** [comment]
Anyone?

**Comment by Fowgzu** [comment]
Omfg why does it keep closing the issue

**Comment by lnx00** [comment]
> Omfg why does it keep closing the issue

user issue

**Comment by xxmyn** [comment]
I have had a long think about this, it's dumb.
