### ISSUE TITLE
Broken Fresnel Chams

### ISSUE THREAD

**Issue by xxmyn** [tf2cheater2013/Fedoraware#67]
if your fresnel chams look like the attached image, please respond to this issue.
![unknown](https://user-images.githubusercontent.com/70382582/157634995-dd626a7c-bd07-48e8-9c5c-2d1beabde699.png)

**Comment by johnathon-walnut** [comment]
what on earth

**Comment by xxmyn** [comment]
i fixed it for myself, but i just wanna see if other people might still get it.

**Comment by nofhdgtf778** [comment]
my chams are not working

**Comment by johnathon-walnut** [comment]
very descriptive

**Comment by wayven** [comment]
my balls itch

**Comment by nofhdgtf778** [comment]
> very descriptive

my chams does not load or the dt bar color i restarted the game and injected the cheat again and still nothing

**Comment by wayven** [comment]
we got it we know it don't work stop talking you donkey we will fix and add negro esp

**Comment by nofhdgtf778** [comment]
> we got it we know it don't work stop talking you donkey we will fix and add negro esp

who are you nigger

**Comment by wayven** [comment]
> > we got it we know it don't work stop talking you donkey we will fix and add negro esp
> 
> who are you nigger

your mom's lover + watch yo tone faggot i fuck yo mama long dick style bitchass boy angolan manure salesman

**Comment by nofhdgtf778** [comment]
fix chams guysssssssssss

**Comment by tf2cheater2013** [comment]
> > very descriptive
> 
> my chams does not load or the dt bar color i restarted the game and injected the cheat again and still nothing

This is not what this thread is for, please only respond if your fresnel chams look like the one I showed in the image.

If you are having separate issues, please open an issue for them.
