### ISSUE TITLE
Crash when im on a game

### ISSUE THREAD

**Issue by nofhdgtf778** [tf2cheater2013/Fedoraware#70]
wtf is going on, now i crash when i load into a game

**Comment by nofhdgtf778** [comment]
and also Glow esp is broken too

**Comment by xxmyn** [comment]
endlessly complaining doesnt help, setup glow and chams correctly, save it to a config, and then load the config.

if it doesnt work, show it in a video and attach it here, stop making posts for issues that are only seeming to happen to you :D
