### ISSUE TITLE
Suggestion: Warp peek

### ISSUE THREAD

**Issue by canedoly** [tf2cheater2013/Fedoraware#71]
Something like [here](https://www.youtube.com/watch?v=KEkEtHAwzgE&t=80s)
I think it works like
Shifts 24 ticks, uses 12 ticks to move right/left waits a tick so aimbot can fire and then uses the rest of ticks to hide.
You could probably use keys for manual directions for ex. h to warp peek to the left and j to warp peek to the right or somehow use edge detection for this.

**Comment by lnx00** [comment]
I have added auto peek in #78.
If you combine this with warp/DT then you can probably get the effect your explained.
