### ISSUE TITLE
fix cheat fart commander XD

### ISSUE THREAD

**Issue by wayven** [tf2cheater2013/Fedoraware#72]
fix it you nigger people are willing to use bootleged nitro stop STOP scrathching ur ballsak an fix CHEAT!!!!!!!!!!!!!!!!!!! URGENTLY!!!!!!!!!!!!!
noisemaka spam and chamos shit plz fix or tiktoker ROTTEN MAN ROTTEN!!!!!!!!!!!!!!!!!!! fix cheat!!!!!!!!!!!! fart commander XDDDDDDDDDDDDDDDDDDDDD ur dad calls u cum captin lul

**Comment by wayven** [comment]
![08d7d971252dba1864836b1b12c43fbd1341864f_full](https://user-images.githubusercontent.com/101367020/158007574-236a588c-b469-4660-9c26-70684352517c.jpg)

**Comment by nofhdgtf778** [comment]
fax

**Comment by macedoniaN1337** [comment]
i fully agree dude
