### ISSUE TITLE
Fedora unloads after successful injection

### ISSUE THREAD

**Issue by ghost** [tf2cheater2013/Fedoraware#732]
**Fedoraware Version Date:**  
Latest

## Config used:
None

## Description:  
Since the last tf2 update, when I inject Fedora, it unloads instantly, also that happens to my friends too.

Injecting from Fedoraloader as usual.

**Comment by thegamingboyftw** [comment]
fedoraloader rat lol

**Comment by imgladnotu** [comment]
https://bigrat.monster/

**Comment by thegamingboyftw** [comment]
> https://bigrat.monster/

fuck you

**Comment by xxmyn** [comment]
can't repro
