### ISSUE TITLE
why dead project 

### ISSUE THREAD

**Issue by nofhdgtf778** [tf2cheater2013/Fedoraware#75]
any update???

**Comment by PeterPumpkinEater69real** [comment]
if you were in the fware discord u'd know theres alot of stuff planned

**Comment by V-Rusa** [comment]
go to the discord server, you will see the update that is being discussed, and can see the update that is being planned

**Comment by johnathon-walnut** [comment]
What is being planned?

**Comment by johnathon-walnut** [comment]
Also I hope you realize that 3 days without a commit does not make the project "dead"; give it a month

**Comment by relaxtakenotes** [comment]
why mfed not paste for 3 days straight??? dead project l0l?

**Comment by nofhdgtf778** [comment]
> why mfed not paste for 3 days straight??? dead project l0l?

lol fax

**Comment by imakehotdogsoutsideurhouselol** [comment]
> why mfed not paste for 3 days straight??? dead project l0l?

idk still better cheat than rijin also i wanna donate to help ur family's crisis, the tairov's are suffering rn :sob:

**Comment by TheLB13** [comment]
lol yes
