### ISSUE TITLE
joking pooron the fourth

### ISSUE THREAD

**Issue by imakehotdogsoutsideurhouselol** [tf2cheater2013/Fedoraware#76]
Here's a real issue
jp4 (salavat) family is poor (his parents sleep on mattresses)
we need to raise money so that he can get good equipment for video clips...

**Comment by imakehotdogsoutsideurhouselol** [comment]
cope lol

**Comment by imakehotdogsoutsideurhouselol** [comment]
rage issue closure cuz low t?

**Comment by johnathon-walnut** [comment]
stop being mean to jp4 :(

**Comment by wayven** [comment]
sorry jpenis4!!!!!!!!!!!!!
