### ISSUE TITLE
Getting banned by SMAC on community servers with Fedoraware

### ISSUE THREAD

**Issue by snoopexe** [tf2cheater2013/Fedoraware#77]
I get banned when I enter community servers with fedoraware its something about fog violation, even though I have 0 fog on. It's really weird man.

**Comment by johnathon-walnut** [comment]
It's to do with the fog changer. Comment it out and rebuild. I don't know how to do anti SMAC and I don't really care enough as most community servers are pretty lame anyway, but there's probably a better way to do the fog stuff anyway

**Comment by wayven** [comment]
1

**Comment by electrospaz** [comment]
fog_enable should be set to 1. It's also a cheat cvar, so they are most likely banning you for cvar manipulation.

**Comment by snoopexe** [comment]
anyone know how i can remove the fog changer from the build?

**Comment by johnathon-walnut** [comment]
Comment it out

**Comment by snoopexe** [comment]
so remove it from the cpp?

**Comment by snoopexe** [comment]
namespace Fog
		{
			inline CVar<bool> CustomFog{ false, L"Fog" };
			inline Color_t FogColor{ 255,255,255,255 };
			inline Color_t FogColorSkybox{ 255,255,255,255 };
			inline CVar<float> FogDensity{ 0, L"fog" };
			inline CVar<float> FogDensitySkybox{ 0, L"fog" };
			inline CVar<float> FogStart{ 0, L"fog" };
			inline CVar<float> FogStartSkybox{ 0, L"fog" };
			inline CVar<float> FogEnd{ 0, L"fog" };
			inline CVar<float> FogEndSkybox{ 0, L"fog" };

**Comment by snoopexe** [comment]
> Comment it out

nvm i get what you mean thanks

**Comment by snoopexe** [comment]
> Comment it out

when i comment out the fog this happens when trying to build 
![image](https://user-images.githubusercontent.com/85544434/159089125-be202fab-6ffa-4f71-87ed-c001c5f730f9.png)

**Comment by snoopexe** [comment]
> > Comment it out
> 
> when i comment out the fog this happens when trying to build ![image](https://user-images.githubusercontent.com/85544434/159089125-be202fab-6ffa-4f71-87ed-c001c5f730f9.png)

![image](https://user-images.githubusercontent.com/85544434/159089311-fa2c5048-4573-4f51-8f5c-e606631832ea.png)

**Comment by johnathon-walnut** [comment]
Should be fixed
