### ISSUE TITLE
make fware that u can dual inject

### ISSUE THREAD

**Issue by nofhdgtf778** [tf2cheater2013/Fedoraware#79]
i injected fware and lbox and works but kicked me from the server
so wtf is going on

**Comment by PeterPumpkinEater69real** [comment]
Disconnect: client disconnect?

**Comment by canedoly** [comment]
some compatibility issues it used to work with lbox but some update caused it to break

**Comment by lnx00** [comment]
#69 #60 #52 #48
please stop asking already

**Comment by nofhdgtf778** [comment]
> #69 #60 #52 #48 please stop asking already

JUST MAKE IT DUAL INJECTABLE M8 XDD
