### ISSUE TITLE
It crashes randomly again.

### ISSUE THREAD

**Issue by LukeHenson18** [tf2cheater2013/Fedoraware#85]
Everytime I'm in the middle of a match in crashes randomly, Not tfghost's Crash.

**Comment by johnathon-walnut** [comment]
I hope you realise how little saying "It crashes randomly" does to help fix the random crashing...

**Comment by xxmyn** [comment]
> Everytime I'm in the middle of a match in crashes randomly, Not tfghost's Crash.

either u attach the shit we need to help fix the issue, or you shut the fuck up.
