### ISSUE TITLE
Assumingly random crashing mid-match while using Fedware.

### ISSUE THREAD

**Issue by Umbrozium** [tf2cheater2013/Fedoraware#86]
I used Fedoraloader as the injector.
https://anonfiles.com/nao6Q3Pdx1/sexer_fed
This is the config I used.

**Comment by TheLB13** [comment]
yea it is very annoying

**Comment by frel0** [comment]
I recommend using this injector because its fast and undetected: https://github.com/relaxtakenotes/xenos/releases/tag/1.1.2

and use the latest version of fedoraware (maybe try using lower graphics too)

**Comment by Dglacet** [comment]
i think its config issue, ive made a new one with basics settings (like no chams and other shit) and it didnt crash

**Comment by xxmyn** [comment]
use the previous build and tell me if issues still occur

**Comment by lnx00** [comment]
This seems to be causes by the new "Auto Vote" feature in Misc. Disable it to prevent crashing.

**Comment by xxmyn** [comment]
looks like it was fixed :D

**Comment by TheLB13** [comment]
idk
