### ISSUE TITLE
chams not working

### ISSUE THREAD

**Issue by nofhdgtf778** [tf2cheater2013/Fedoraware#91]
![image](https://user-images.githubusercontent.com/99003686/159572614-b3d9edfe-05dd-453d-81a6-ddba4d2483bf.png)
![image](https://user-images.githubusercontent.com/99003686/159572712-47026501-4b04-47c1-bf24-37a60ba2607a.png)

**Comment by Dglacet** [comment]
i had this issue, just make a new config,

**Comment by johnathon-walnut** [comment]
i blame baan

**Comment by nofhdgtf778** [comment]
![image](https://user-images.githubusercontent.com/99003686/159577279-89b66cfc-486a-408b-ba2d-b892dea086ad.png)
now fresnel glow overlay is fresnel

**Comment by xxmyn** [comment]
I KNEW U WERE ON DME GO BACK TO MAIN IT LITERALLY SAYS WIP NEXT TO DME U IDIOT GO BACK TO MAIN BRANCH LEGIT CHILD

**Comment by nofhdgtf778** [comment]
why making it public then l0l

**Comment by xxmyn** [comment]
because it is public, doesnt mean im gonna bugfix for u tho

**Comment by nofhdgtf778** [comment]
are you baan?

**Comment by xxmyn** [comment]
yes

**Comment by nofhdgtf778** [comment]
m8 why did you stop sending nudes to egh? m8

**Comment by xxmyn** [comment]
???
