### ISSUE TITLE
aimbot tries to anti warp while not dting

### ISSUE THREAD

**Issue by canedoly** [tf2cheater2013/Fedoraware#93]
This bug got fixed, I think and after some time it started happening again

this happens after some time of using the dt, when you have it charged, use aimbot, have anti warp enabled and using a hitscan weapon and you need to not hold the dt key then it will try to anti warp, disabling anti warp makes it work again ( I used 21 ticks and didn't change them to any other value)

I've also made a [demo](https://files.catbox.moe/1arh5z.dem) since I'm too lazy to record. This happens with every config that I have and even on the default fedoraware config

**Comment by xxmyn** [comment]
Thank you for reporting the issue, it has been fixed as of the latest build.

The bug that was fixed before had to do with something else while jumping.
