### ISSUE TITLE
Fix Crit hack 

### ISSUE THREAD

**Issue by TheLB13** [tf2cheater2013/Fedoraware#95]
Fix Crit hack Fix Crit hack Fix Crit hack Fix Crit hack Fix Crit hack Fix Crit hackFix Crit hackFix Crit hackFix Crit hackFix Crit hackFix Crit hackFix Crit hackFix Crit hackFix Crit hackFix Crit hack Fix Crit hackFix Crit hack Fix Crit hackFix Crit hack Fix Crit hack Fix Crit hackFix Crit hackFix Crit hackFix Crit hack Fix Crit hack 

OK

**Comment by johnathon-walnut** [comment]
How much you pay?

**Comment by TheLB13** [comment]
0

**Comment by wayven** [comment]
how he gonna fix if the crithack doesnt even exist in this paste llololollolol8 123456789

**Comment by nofhdgtf778** [comment]
LOL FACTS THEY CANT PASTE CRITHACK BCUZ THERE IS NO PUBLIC CODE TO PASTE IT LMFAO XD ATLEAST MAKE IT DUAL INJECTABLE IF YOU DONT WANT TO FIX CRITHACK PASTER

**Comment by wayven** [comment]
XDDDDDDDDDDDDDD SHIT PASTE OMG

**Comment by xxmyn** [comment]
no

**Comment by wayven** [comment]
don't fix if pedo 

> no

**Comment by nofhdgtf778** [comment]
LOL FACTS THEY CANT PASTE CRITHACK BCUZ THERE IS NO PUBLIC CODE TO PASTE IT LMFAO XD ATLEAST MAKE IT DUAL INJECTABLE IF YOU DONT WANT TO FIX CRITHACK PASTERLOL FACTS THEY CANT PASTE CRITHACK BCUZ THERE IS NO PUBLIC CODE TO PASTE IT LMFAO XD ATLEAST MAKE IT DUAL INJECTABLE IF YOU DONT WANT TO FIX CRITHACK PASTERLOL FACTS THEY CANT PASTE CRITHACK BCUZ THERE IS NO PUBLIC CODE TO PASTE IT LMFAO XD ATLEAST MAKE IT DUAL INJECTABLE IF YOU DONT WANT TO FIX CRITHACK PASTERLOL FACTS THEY CANT PASTE CRITHACK BCUZ THERE IS NO PUBLIC CODE TO PASTE IT LMFAO XD ATLEAST MAKE IT DUAL INJECTABLE IF YOU DONT WANT TO FIX CRITHACK PASTERLOL FACTS THEY CANT PASTE CRITHACK BCUZ THERE IS NO PUBLIC CODE TO PASTE IT LMFAO XD ATLEAST MAKE IT DUAL INJECTABLE IF YOU DONT WANT TO FIX CRITHACK PASTERLOL FACTS THEY CANT PASTE CRITHACK BCUZ THERE IS NO PUBLIC CODE TO PASTE IT LMFAO XD ATLEAST MAKE IT DUAL INJECTABLE IF YOU DONT WANT TO FIX CRITHACK PASTERLOL FACTS THEY CANT PASTE CRITHACK BCUZ THERE IS NO PUBLIC CODE TO PASTE IT LMFAO XD ATLEAST MAKE IT DUAL INJECTABLE IF YOU DONT WANT TO FIX CRITHACK PASTERLOL FACTS THEY CANT PASTE CRITHACK BCUZ THERE IS NO PUBLIC CODE TO PASTE IT LMFAO XD ATLEAST MAKE IT DUAL INJECTABLE IF YOU DONT WANT TO FIX CRITHACK PASTERLOL FACTS THEY CANT PASTE CRITHACK BCUZ THERE IS NO PUBLIC CODE TO PASTE IT LMFAO XD ATLEAST MAKE IT DUAL INJECTABLE IF YOU DONT WANT TO FIX CRITHACK PASTERLOL FACTS THEY CANT PASTE CRITHACK BCUZ THERE IS NO PUBLIC CODE TO PASTE IT LMFAO XD ATLEAST MAKE IT DUAL INJECTABLE IF YOU DONT WANT TO FIX CRITHACK PASTERLOL FACTS THEY CANT PASTE CRITHACK BCUZ THERE IS NO PUBLIC CODE TO PASTE IT LMFAO XD ATLEAST MAKE IT DUAL INJECTABLE IF YOU DONT WANT TO FIX CRITHACK PASTERLOL FACTS THEY CANT PASTE CRITHACK BCUZ THERE IS NO PUBLIC CODE TO PASTE IT LMFAO XD ATLEAST MAKE IT DUAL INJECTABLE IF YOU DONT WANT TO FIX CRITHACK PASTERLOL FACTS THEY CANT PASTE CRITHACK BCUZ THERE IS NO PUBLIC CODE TO PASTE IT LMFAO XD ATLEAST MAKE IT DUAL INJECTABLE IF YOU DONT WANT TO FIX CRITHACK PASTERLOL FACTS THEY CANT PASTE CRITHACK BCUZ THERE IS NO PUBLIC CODE TO PASTE IT LMFAO XD ATLEAST MAKE IT DUAL INJECTABLE IF YOU DONT WANT TO FIX CRITHACK PASTERLOL FACTS THEY CANT PASTE CRITHACK BCUZ THERE IS NO PUBLIC CODE TO PASTE IT LMFAO XD ATLEAST MAKE IT DUAL INJECTABLE IF YOU DONT WANT TO FIX CRITHACK PASTERLOL FACTS THEY CANT PASTE CRITHACK BCUZ THERE IS NO PUBLIC CODE TO PASTE IT LMFAO XD ATLEAST MAKE IT DUAL INJECTABLE IF YOU DONT WANT TO FIX CRITHACK PASTERLOL FACTS THEY CANT PASTE CRITHACK BCUZ THERE IS NO PUBLIC CODE TO PASTE IT LMFAO XD ATLEAST MAKE IT DUAL INJECTABLE IF YOU DONT WANT TO FIX CRITHACK PASTERLOL FACTS THEY CANT PASTE CRITHACK BCUZ THERE IS NO PUBLIC CODE TO PASTE IT LMFAO XD ATLEAST MAKE IT DUAL INJECTABLE IF YOU DONT WANT TO FIX CRITHACK PASTERLOL FACTS THEY CANT PASTE CRITHACK BCUZ THERE IS NO PUBLIC CODE TO PASTE IT LMFAO XD ATLEAST MAKE IT DUAL INJECTABLE IF YOU DONT WANT TO FIX CRITHACK PASTERLOL FACTS THEY CANT PASTE CRITHACK BCUZ THERE IS NO PUBLIC CODE TO PASTE IT LMFAO XD ATLEAST MAKE IT DUAL INJECTABLE IF YOU DONT WANT TO FIX CRITHACK PASTER

**Comment by gayblackirony** [comment]
shoot yourself in the head

> LOL FACTS THEY CANT PASTE CRITHACK BCUZ THERE IS NO PUBLIC CODE TO PASTE IT LMFAO XD ATLEAST MAKE IT DUAL INJECTABLE IF YOU DONT WANT TO FIX CRITHACK PASTERLOL FACTS THEY CANT PASTE CRITHACK BCUZ THERE IS NO PUBLIC CODE TO PASTE IT LMFAO XD ATLEAST MAKE IT DUAL INJECTABLE IF YOU DONT WANT TO FIX CRITHACK PASTERLOL FACTS THEY CANT PASTE CRITHACK BCUZ THERE IS NO PUBLIC CODE TO PASTE IT LMFAO XD ATLEAST MAKE IT DUAL INJECTABLE IF YOU DONT WANT TO FIX CRITHACK PASTERLOL FACTS THEY CANT PASTE CRITHACK BCUZ THERE IS NO PUBLIC CODE TO PASTE IT LMFAO XD ATLEAST MAKE IT DUAL INJECTABLE IF YOU DONT WANT TO FIX CRITHACK PASTERLOL FACTS THEY CANT PASTE CRITHACK BCUZ THERE IS NO PUBLIC CODE TO PASTE IT LMFAO XD ATLEAST MAKE IT DUAL INJECTABLE IF YOU DONT WANT TO FIX CRITHACK PASTERLOL FACTS THEY CANT PASTE CRITHACK BCUZ THERE IS NO PUBLIC CODE TO PASTE IT LMFAO XD ATLEAST MAKE IT DUAL INJECTABLE IF YOU DONT WANT TO FIX CRITHACK PASTERLOL FACTS THEY CANT PASTE CRITHACK BCUZ THERE IS NO PUBLIC CODE TO PASTE IT LMFAO XD ATLEAST MAKE IT DUAL INJECTABLE IF YOU DONT WANT TO FIX CRITHACK PASTERLOL FACTS THEY CANT PASTE CRITHACK BCUZ THERE IS NO PUBLIC CODE TO PASTE IT LMFAO XD ATLEAST MAKE IT DUAL INJECTABLE IF YOU DONT WANT TO FIX CRITHACK PASTERLOL FACTS THEY CANT PASTE CRITHACK BCUZ THERE IS NO PUBLIC CODE TO PASTE IT LMFAO XD ATLEAST MAKE IT DUAL INJECTABLE IF YOU DONT WANT TO FIX CRITHACK PASTERLOL FACTS THEY CANT PASTE CRITHACK BCUZ THERE IS NO PUBLIC CODE TO PASTE IT LMFAO XD ATLEAST MAKE IT DUAL INJECTABLE IF YOU DONT WANT TO FIX CRITHACK PASTERLOL FACTS THEY CANT PASTE CRITHACK BCUZ THERE IS NO PUBLIC CODE TO PASTE IT LMFAO XD ATLEAST MAKE IT DUAL INJECTABLE IF YOU DONT WANT TO FIX CRITHACK PASTERLOL FACTS THEY CANT PASTE CRITHACK BCUZ THERE IS NO PUBLIC CODE TO PASTE IT LMFAO XD ATLEAST MAKE IT DUAL INJECTABLE IF YOU DONT WANT TO FIX CRITHACK PASTERLOL FACTS THEY CANT PASTE CRITHACK BCUZ THERE IS NO PUBLIC CODE TO PASTE IT LMFAO XD ATLEAST MAKE IT DUAL INJECTABLE IF YOU DONT WANT TO FIX CRITHACK PASTERLOL FACTS THEY CANT PASTE CRITHACK BCUZ THERE IS NO PUBLIC CODE TO PASTE IT LMFAO XD ATLEAST MAKE IT DUAL INJECTABLE IF YOU DONT WANT TO FIX CRITHACK PASTERLOL FACTS THEY CANT PASTE CRITHACK BCUZ THERE IS NO PUBLIC CODE TO PASTE IT LMFAO XD ATLEAST MAKE IT DUAL INJECTABLE IF YOU DONT WANT TO FIX CRITHACK PASTERLOL FACTS THEY CANT PASTE CRITHACK BCUZ THERE IS NO PUBLIC CODE TO PASTE IT LMFAO XD ATLEAST MAKE IT DUAL INJECTABLE IF YOU DONT WANT TO FIX CRITHACK PASTERLOL FACTS THEY CANT PASTE CRITHACK BCUZ THERE IS NO PUBLIC CODE TO PASTE IT LMFAO XD ATLEAST MAKE IT DUAL INJECTABLE IF YOU DONT WANT TO FIX CRITHACK PASTERLOL FACTS THEY CANT PASTE CRITHACK BCUZ THERE IS NO PUBLIC CODE TO PASTE IT LMFAO XD ATLEAST MAKE IT DUAL INJECTABLE IF YOU DONT WANT TO FIX CRITHACK PASTERLOL FACTS THEY CANT PASTE CRITHACK BCUZ THERE IS NO PUBLIC CODE TO PASTE IT LMFAO XD ATLEAST MAKE IT DUAL INJECTABLE IF YOU DONT WANT TO FIX CRITHACK PASTERLOL FACTS THEY CANT PASTE CRITHACK BCUZ THERE IS NO PUBLIC CODE TO PASTE IT LMFAO XD ATLEAST MAKE IT DUAL INJECTABLE IF YOU DONT WANT TO FIX CRITHACK PASTER

**Comment by xxmyn** [comment]
cathook crithack is public i just dont care enough abt crothack to add it

**Comment by awesome20222** [comment]
@xxmyn try looking at this [code](https://www.unknowncheats.me/forum/team-fortress-2-a/430169-perfect-crithack-engine-manipulation.html) . Maybe something will work

**Comment by xxmyn** [comment]
Uhh, lnx fixed crithack a while ago, and I stay far away from it.

**Comment by awesome20222** [comment]
@xxmyn why doesn't it work for melee weapons?
Yesterday i tested it

**Comment by xxmyn** [comment]
Uhh, idk, it works perfectly for me.

**Comment by awesome20222** [comment]
@xxmyn sorry. now it works. if you can add "always for melee" (without bind)
